// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: achievements.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminAchievementStats = `-- name: AdminAchievementStats :many
SELECT achievement_id, count(*)::bigint AS granted, count(DISTINCT workspace_id)::bigint AS workspaces
FROM member_achievements WHERE revoked_at IS NULL
GROUP BY achievement_id
`

type AdminAchievementStatsRow struct {
	AchievementID uuid.UUID
	Granted       int64
	Workspaces    int64
}

// Live grants and the workspaces they are in, per catalog entry.
func (q *Queries) AdminAchievementStats(ctx context.Context) ([]AdminAchievementStatsRow, error) {
	rows, err := q.db.Query(ctx, adminAchievementStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminAchievementStatsRow{}
	for rows.Next() {
		var i AdminAchievementStatsRow
		if err := rows.Scan(&i.AchievementID, &i.Granted, &i.Workspaces); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAchievement = `-- name: DeleteAchievement :execrows
DELETE FROM achievements a WHERE a.id = $1
  AND NOT EXISTS (SELECT 1 FROM member_achievements m WHERE m.achievement_id = a.id)
`

// Only an entry that was never granted (revoked grants count): 0 rows = in use or gone.
func (q *Queries) DeleteAchievement(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAchievement, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAchievement = `-- name: GetAchievement :one
SELECT id, title, description, image_key, image_size, width, height, position, created_by, created_at, updated_at, archived_at FROM achievements WHERE id = $1
`

func (q *Queries) GetAchievement(ctx context.Context, id uuid.UUID) (Achievement, error) {
	row := q.db.QueryRow(ctx, getAchievement, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageKey,
		&i.ImageSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const getAnnouncementRoom = `-- name: GetAnnouncementRoom :one
SELECT r.id FROM rooms r WHERE r.id = announcement_room($1::uuid)
`

// The room of server cards of a workspace (birthdays, achievements): announcement_room(),
// migration 00061. No row = the workspace has no text room.
func (q *Queries) GetAnnouncementRoom(ctx context.Context, workspaceID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAnnouncementRoom, workspaceID)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertAchievement = `-- name: InsertAchievement :one
INSERT INTO achievements (title, description, image_key, image_size, width, height, position, created_by)
VALUES ($1, $2, $3, $4,
    $5, $6,
    (SELECT coalesce(max(position) + 1, 0) FROM achievements), $7)
RETURNING id, title, description, image_key, image_size, width, height, position, created_by, created_at, updated_at, archived_at
`

type InsertAchievementParams struct {
	Title       string
	Description string
	ImageKey    string
	ImageSize   int32
	Width       int32
	Height      int32
	CreatedBy   *uuid.UUID
}

// A new entry goes to the end of the catalog.
func (q *Queries) InsertAchievement(ctx context.Context, arg InsertAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, insertAchievement,
		arg.Title,
		arg.Description,
		arg.ImageKey,
		arg.ImageSize,
		arg.Width,
		arg.Height,
		arg.CreatedBy,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageKey,
		&i.ImageSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const insertCardMention = `-- name: InsertCardMention :exec
INSERT INTO message_mentions (user_id, message_id, room_id)
SELECT $1::uuid, $2::uuid, $3::uuid
WHERE EXISTS (SELECT 1 FROM workspace_members wm
    WHERE wm.user_id = $1::uuid AND wm.workspace_id = $4::uuid)
ON CONFLICT DO NOTHING
`

type InsertCardMentionParams struct {
	UserID      uuid.UUID
	MessageID   uuid.UUID
	RoomID      uuid.UUID
	WorkspaceID uuid.UUID
}

// A server card mentions the member it is about (its author): the mention inbox and counters
// treat it as an @-mention. Only a member of the room's workspace.
func (q *Queries) InsertCardMention(ctx context.Context, arg InsertCardMentionParams) error {
	_, err := q.db.Exec(ctx, insertCardMention,
		arg.UserID,
		arg.MessageID,
		arg.RoomID,
		arg.WorkspaceID,
	)
	return err
}

const insertMemberAchievement = `-- name: InsertMemberAchievement :one
INSERT INTO member_achievements (workspace_id, user_id, achievement_id, granted_by, note)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, user_id, achievement_id, granted_by, note, message_id, granted_at, revoked_at, revoked_by
`

type InsertMemberAchievementParams struct {
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	AchievementID uuid.UUID
	GrantedBy     *uuid.UUID
	Note          string
}

func (q *Queries) InsertMemberAchievement(ctx context.Context, arg InsertMemberAchievementParams) (MemberAchievement, error) {
	row := q.db.QueryRow(ctx, insertMemberAchievement,
		arg.WorkspaceID,
		arg.UserID,
		arg.AchievementID,
		arg.GrantedBy,
		arg.Note,
	)
	var i MemberAchievement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.AchievementID,
		&i.GrantedBy,
		&i.Note,
		&i.MessageID,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const listAchievements = `-- name: ListAchievements :many

SELECT id, title, description, image_key, image_size, width, height, position, created_by, created_at, updated_at, archived_at FROM achievements ORDER BY position, id
`

// Achievements (ADR-0061): the host catalog and grants to workspace members.
// The whole catalog in its order, archived entries included.
func (q *Queries) ListAchievements(ctx context.Context) ([]Achievement, error) {
	rows, err := q.db.Query(ctx, listAchievements)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Achievement{}
	for rows.Next() {
		var i Achievement
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.ImageKey,
			&i.ImageSize,
			&i.Width,
			&i.Height,
			&i.Position,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberAchievements = `-- name: ListMemberAchievements :many
SELECT a.id, a.workspace_id, a.user_id, a.achievement_id, a.granted_by, a.note, a.message_id, a.granted_at, a.revoked_at, a.revoked_by, m.room_id AS card_room_id
FROM member_achievements a
LEFT JOIN messages m ON m.id = a.message_id
WHERE a.workspace_id = $1 AND a.user_id = $2 AND a.revoked_at IS NULL
ORDER BY a.granted_at DESC, a.id DESC
`

type ListMemberAchievementsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type ListMemberAchievementsRow struct {
	MemberAchievement MemberAchievement
	CardRoomID        *uuid.UUID
}

// A member's live grants, newest first, with the room of each chat card.
func (q *Queries) ListMemberAchievements(ctx context.Context, arg ListMemberAchievementsParams) ([]ListMemberAchievementsRow, error) {
	rows, err := q.db.Query(ctx, listMemberAchievements, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberAchievementsRow{}
	for rows.Next() {
		var i ListMemberAchievementsRow
		if err := rows.Scan(
			&i.MemberAchievement.ID,
			&i.MemberAchievement.WorkspaceID,
			&i.MemberAchievement.UserID,
			&i.MemberAchievement.AchievementID,
			&i.MemberAchievement.GrantedBy,
			&i.MemberAchievement.Note,
			&i.MemberAchievement.MessageID,
			&i.MemberAchievement.GrantedAt,
			&i.MemberAchievement.RevokedAt,
			&i.MemberAchievement.RevokedBy,
			&i.CardRoomID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAchievement = `-- name: LockAchievement :one
SELECT id, title, description, image_key, image_size, width, height, position, created_by, created_at, updated_at, archived_at FROM achievements WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockAchievement(ctx context.Context, id uuid.UUID) (Achievement, error) {
	row := q.db.QueryRow(ctx, lockAchievement, id)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageKey,
		&i.ImageSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const recountMemberAchievements = `-- name: RecountMemberAchievements :one
UPDATE workspace_members wm SET achievement_count = (
    SELECT count(*) FROM member_achievements a
    WHERE a.workspace_id = wm.workspace_id AND a.user_id = wm.user_id AND a.revoked_at IS NULL)
WHERE wm.workspace_id = $1 AND wm.user_id = $2
RETURNING workspace_id, user_id, role, nickname, joined_at, badge_id, achievement_count
`

type RecountMemberAchievementsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Stores and returns the member's live grant count (WorkspaceMember.achievement_count).
func (q *Queries) RecountMemberAchievements(ctx context.Context, arg RecountMemberAchievementsParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, recountMemberAchievements, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
		&i.BadgeID,
		&i.AchievementCount,
	)
	return i, err
}

const revokeMemberAchievement = `-- name: RevokeMemberAchievement :one
UPDATE member_achievements SET revoked_at = now(), revoked_by = $1
WHERE id = $2 AND workspace_id = $3 AND user_id = $4
  AND revoked_at IS NULL
RETURNING id, workspace_id, user_id, achievement_id, granted_by, note, message_id, granted_at, revoked_at, revoked_by
`

type RevokeMemberAchievementParams struct {
	RevokedBy   *uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RevokeMemberAchievement(ctx context.Context, arg RevokeMemberAchievementParams) (MemberAchievement, error) {
	row := q.db.QueryRow(ctx, revokeMemberAchievement,
		arg.RevokedBy,
		arg.ID,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i MemberAchievement
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.UserID,
		&i.AchievementID,
		&i.GrantedBy,
		&i.Note,
		&i.MessageID,
		&i.GrantedAt,
		&i.RevokedAt,
		&i.RevokedBy,
	)
	return i, err
}

const setMemberAchievementMessage = `-- name: SetMemberAchievementMessage :exec
UPDATE member_achievements SET message_id = $2 WHERE id = $1
`

type SetMemberAchievementMessageParams struct {
	ID        uuid.UUID
	MessageID *uuid.UUID
}

func (q *Queries) SetMemberAchievementMessage(ctx context.Context, arg SetMemberAchievementMessageParams) error {
	_, err := q.db.Exec(ctx, setMemberAchievementMessage, arg.ID, arg.MessageID)
	return err
}

const updateAchievement = `-- name: UpdateAchievement :one
UPDATE achievements SET title = $2, description = $3, image_key = $4, image_size = $5, width = $6,
    height = $7, position = $8, archived_at = $9, updated_at = now()
WHERE id = $1
RETURNING id, title, description, image_key, image_size, width, height, position, created_by, created_at, updated_at, archived_at
`

type UpdateAchievementParams struct {
	ID          uuid.UUID
	Title       string
	Description string
	ImageKey    string
	ImageSize   int32
	Width       int32
	Height      int32
	Position    int32
	ArchivedAt  *time.Time
}

func (q *Queries) UpdateAchievement(ctx context.Context, arg UpdateAchievementParams) (Achievement, error) {
	row := q.db.QueryRow(ctx, updateAchievement,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.ImageKey,
		arg.ImageSize,
		arg.Width,
		arg.Height,
		arg.Position,
		arg.ArchivedAt,
	)
	var i Achievement
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.ImageKey,
		&i.ImageSize,
		&i.Width,
		&i.Height,
		&i.Position,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
