// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admissions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countPendingAdmissions = `-- name: CountPendingAdmissions :one
SELECT count(*)::integer FROM room_admissions WHERE room_id = $1 AND status = 'pending'
`

func (q *Queries) CountPendingAdmissions(ctx context.Context, roomID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countPendingAdmissions, roomID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countUserRoomInvites = `-- name: CountUserRoomInvites :one
SELECT count(*)::integer FROM room_invites WHERE room_id = $1 AND created_by = $2
`

type CountUserRoomInvitesParams struct {
	RoomID    uuid.UUID
	CreatedBy uuid.UUID
}

// Links of the room made by the user (they may decide on the knocks by them).
func (q *Queries) CountUserRoomInvites(ctx context.Context, arg CountUserRoomInvitesParams) (int32, error) {
	row := q.db.QueryRow(ctx, countUserRoomInvites, arg.RoomID, arg.CreatedBy)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const declineAdmission = `-- name: DeclineAdmission :one
UPDATE room_admissions SET status = 'declined', decided_by = $1, decided_at = $2::timestamptz
WHERE room_id = $3 AND user_id = $4 AND status = 'pending'
RETURNING room_id, user_id, invite_id, status, requested_at, decided_by, decided_at
`

type DeclineAdmissionParams struct {
	DecidedBy *uuid.UUID
	DecidedAt time.Time
	RoomID    uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) DeclineAdmission(ctx context.Context, arg DeclineAdmissionParams) (RoomAdmission, error) {
	row := q.db.QueryRow(ctx, declineAdmission,
		arg.DecidedBy,
		arg.DecidedAt,
		arg.RoomID,
		arg.UserID,
	)
	var i RoomAdmission
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.InviteID,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const declineStaleAdmissions = `-- name: DeclineStaleAdmissions :many
UPDATE room_admissions a SET status = 'declined', decided_at = $1::timestamptz
FROM (
    SELECT s.room_id, s.user_id FROM room_admissions s
    WHERE s.status = 'pending' AND s.requested_at < $2::timestamptz
    ORDER BY s.requested_at
    LIMIT 200
    FOR UPDATE SKIP LOCKED) stale
WHERE a.room_id = stale.room_id AND a.user_id = stale.user_id
RETURNING a.room_id, a.user_id, a.invite_id, a.status, a.requested_at, a.decided_by, a.decided_at
`

type DeclineStaleAdmissionsParams struct {
	Now    time.Time
	Cutoff time.Time
}

// Sweeper: pending knocks older than the cutoff are declined with nobody deciding.
func (q *Queries) DeclineStaleAdmissions(ctx context.Context, arg DeclineStaleAdmissionsParams) ([]RoomAdmission, error) {
	rows, err := q.db.Query(ctx, declineStaleAdmissions, arg.Now, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomAdmission{}
	for rows.Next() {
		var i RoomAdmission
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.InviteID,
			&i.Status,
			&i.RequestedAt,
			&i.DecidedBy,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAdmission = `-- name: DeleteAdmission :execrows
DELETE FROM room_admissions WHERE room_id = $1 AND user_id = $2
`

type DeleteAdmissionParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteAdmission(ctx context.Context, arg DeleteAdmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdmission, arg.RoomID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredDeclines = `-- name: DeleteExpiredDeclines :execrows
DELETE FROM room_admissions WHERE status = 'declined' AND decided_at < $1::timestamptz
`

func (q *Queries) DeleteExpiredDeclines(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredDeclines, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAdmissionForUpdate = `-- name: GetAdmissionForUpdate :one

SELECT room_id, user_id, invite_id, status, requested_at, decided_by, decided_at FROM room_admissions WHERE room_id = $1 AND user_id = $2 FOR UPDATE
`

type GetAdmissionForUpdateParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

// Guest admission (ADR-0040).
func (q *Queries) GetAdmissionForUpdate(ctx context.Context, arg GetAdmissionForUpdateParams) (RoomAdmission, error) {
	row := q.db.QueryRow(ctx, getAdmissionForUpdate, arg.RoomID, arg.UserID)
	var i RoomAdmission
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.InviteID,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}

const guestHasOtherAccess = `-- name: GuestHasOtherAccess :one
SELECT (EXISTS (
    SELECT 1 FROM room_permissions p JOIN rooms r ON r.id = p.room_id
    WHERE r.workspace_id = $1::uuid AND r.archived_at IS NULL AND r.id <> $2
      AND p.target_type = 'user' AND p.target_id = $3::uuid::text
) OR EXISTS (
    SELECT 1 FROM room_admissions a JOIN rooms r ON r.id = a.room_id
    WHERE r.workspace_id = $1::uuid AND a.room_id <> $2
      AND a.user_id = $3 AND a.status = 'pending'
))::boolean
`

type GuestHasOtherAccessParams struct {
	WorkspaceID uuid.UUID
	RoomID      uuid.UUID
	UserID      uuid.UUID
}

// Whether a guest keeps a reason to stay in the workspace besides this room: a personal
// override in another live room, or a pending knock on another room.
func (q *Queries) GuestHasOtherAccess(ctx context.Context, arg GuestHasOtherAccessParams) (bool, error) {
	row := q.db.QueryRow(ctx, guestHasOtherAccess, arg.WorkspaceID, arg.RoomID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listRoomPendingAdmissions = `-- name: ListRoomPendingAdmissions :many
SELECT a.room_id, a.user_id, a.invite_id, a.status, a.requested_at, a.decided_by, a.decided_at, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days, u.hide_message_text_in_notifications, i.created_by AS invite_created_by
FROM room_admissions a
JOIN users u ON u.id = a.user_id
LEFT JOIN room_invites i ON i.id = a.invite_id
WHERE a.room_id = $1 AND a.status = 'pending'
ORDER BY a.requested_at, a.user_id
`

type ListRoomPendingAdmissionsRow struct {
	RoomAdmission   RoomAdmission
	User            User
	InviteCreatedBy *uuid.UUID
}

// The room's pending knocks with the knocking users, oldest first (≤ 50 by the knock limit).
func (q *Queries) ListRoomPendingAdmissions(ctx context.Context, roomID uuid.UUID) ([]ListRoomPendingAdmissionsRow, error) {
	rows, err := q.db.Query(ctx, listRoomPendingAdmissions, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRoomPendingAdmissionsRow{}
	for rows.Next() {
		var i ListRoomPendingAdmissionsRow
		if err := rows.Scan(
			&i.RoomAdmission.RoomID,
			&i.RoomAdmission.UserID,
			&i.RoomAdmission.InviteID,
			&i.RoomAdmission.Status,
			&i.RoomAdmission.RequestedAt,
			&i.RoomAdmission.DecidedBy,
			&i.RoomAdmission.DecidedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.User.HideMessageTextInNotifications,
			&i.InviteCreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserAdmissions = `-- name: ListUserAdmissions :many
SELECT a.room_id, a.user_id, a.invite_id, a.status, a.requested_at, a.decided_by, a.decided_at, r.name AS room_name, r.workspace_id AS workspace_id, w.name AS workspace_name
FROM room_admissions a
JOIN rooms r ON r.id = a.room_id AND r.archived_at IS NULL
JOIN workspaces w ON w.id = r.workspace_id
WHERE a.user_id = $1 AND a.status IN ('pending', 'declined')
ORDER BY a.requested_at
`

type ListUserAdmissionsRow struct {
	RoomAdmission RoomAdmission
	RoomName      string
	WorkspaceID   *uuid.UUID
	WorkspaceName string
}

// The user's own knocks (READY): pending, and declined ones still kept, with the room and
// workspace names for the waiting screen.
func (q *Queries) ListUserAdmissions(ctx context.Context, userID uuid.UUID) ([]ListUserAdmissionsRow, error) {
	rows, err := q.db.Query(ctx, listUserAdmissions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserAdmissionsRow{}
	for rows.Next() {
		var i ListUserAdmissionsRow
		if err := rows.Scan(
			&i.RoomAdmission.RoomID,
			&i.RoomAdmission.UserID,
			&i.RoomAdmission.InviteID,
			&i.RoomAdmission.Status,
			&i.RoomAdmission.RequestedAt,
			&i.RoomAdmission.DecidedBy,
			&i.RoomAdmission.DecidedAt,
			&i.RoomName,
			&i.WorkspaceID,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesPendingAdmissions = `-- name: ListWorkspacesPendingAdmissions :many
SELECT a.room_id, a.user_id, a.invite_id, a.status, a.requested_at, a.decided_by, a.decided_at, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days, u.hide_message_text_in_notifications, r.workspace_id AS workspace_id, i.created_by AS invite_created_by
FROM room_admissions a
JOIN users u ON u.id = a.user_id
JOIN rooms r ON r.id = a.room_id AND r.archived_at IS NULL
LEFT JOIN room_invites i ON i.id = a.invite_id
WHERE r.workspace_id = ANY($1::uuid[]) AND a.status = 'pending'
ORDER BY a.requested_at, a.user_id
`

type ListWorkspacesPendingAdmissionsRow struct {
	RoomAdmission   RoomAdmission
	User            User
	WorkspaceID     *uuid.UUID
	InviteCreatedBy *uuid.UUID
}

// Pending knocks in the given workspaces (READY of a decider; filtered by the caller).
func (q *Queries) ListWorkspacesPendingAdmissions(ctx context.Context, workspaceIds []uuid.UUID) ([]ListWorkspacesPendingAdmissionsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesPendingAdmissions, workspaceIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspacesPendingAdmissionsRow{}
	for rows.Next() {
		var i ListWorkspacesPendingAdmissionsRow
		if err := rows.Scan(
			&i.RoomAdmission.RoomID,
			&i.RoomAdmission.UserID,
			&i.RoomAdmission.InviteID,
			&i.RoomAdmission.Status,
			&i.RoomAdmission.RequestedAt,
			&i.RoomAdmission.DecidedBy,
			&i.RoomAdmission.DecidedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.User.HideMessageTextInNotifications,
			&i.WorkspaceID,
			&i.InviteCreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRoomAdmissions = `-- name: LockRoomAdmissions :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.admissions:' || $1::uuid::text))
`

// Serializes knocks on one room between the pending count and the insert (limit 50).
func (q *Queries) LockRoomAdmissions(ctx context.Context, roomID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockRoomAdmissions, roomID)
	return err
}

const refundRoomInviteUse = `-- name: RefundRoomInviteUse :exec
UPDATE room_invites SET uses = greatest(uses - 1, 0) WHERE id = $1
`

// A knock that did not end in admission gives its use of the link back.
func (q *Queries) RefundRoomInviteUse(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, refundRoomInviteUse, id)
	return err
}

const removeGuestMember = `-- name: RemoveGuestMember :execrows
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2 AND role = 'guest'
`

type RemoveGuestMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

// Only a guest membership goes (a promoted member stays).
func (q *Queries) RemoveGuestMember(ctx context.Context, arg RemoveGuestMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeGuestMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setGuestDisplayName = `-- name: SetGuestDisplayName :one
UPDATE users SET display_name = $2 WHERE id = $1 AND is_guest RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone, email_verified_at, pending_email, locale, presence_status, presence_until, is_bot, birthday_day, birthday_month, birthday_year, birthday_hidden, event_reminders, event_reminders_dnd, storage_quota_bytes, work_start_min, work_end_min, work_days, hide_message_text_in_notifications
`

type SetGuestDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) SetGuestDisplayName(ctx context.Context, arg SetGuestDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, setGuestDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.PendingEmail,
		&i.Locale,
		&i.PresenceStatus,
		&i.PresenceUntil,
		&i.IsBot,
		&i.BirthdayDay,
		&i.BirthdayMonth,
		&i.BirthdayYear,
		&i.BirthdayHidden,
		&i.EventReminders,
		&i.EventRemindersDnd,
		&i.StorageQuotaBytes,
		&i.WorkStartMin,
		&i.WorkEndMin,
		&i.WorkDays,
		&i.HideMessageTextInNotifications,
	)
	return i, err
}

const upsertPendingAdmission = `-- name: UpsertPendingAdmission :one
INSERT INTO room_admissions (room_id, user_id, invite_id, status, requested_at)
VALUES ($1, $2, $3, 'pending', $4)
ON CONFLICT (room_id, user_id) DO UPDATE
    SET invite_id = EXCLUDED.invite_id, status = 'pending', requested_at = EXCLUDED.requested_at,
        decided_by = NULL, decided_at = NULL
RETURNING room_id, user_id, invite_id, status, requested_at, decided_by, decided_at
`

type UpsertPendingAdmissionParams struct {
	RoomID      uuid.UUID
	UserID      uuid.UUID
	InviteID    *uuid.UUID
	RequestedAt time.Time
}

// A new knock (or a knock again after a decline): pending from requested_at.
func (q *Queries) UpsertPendingAdmission(ctx context.Context, arg UpsertPendingAdmissionParams) (RoomAdmission, error) {
	row := q.db.QueryRow(ctx, upsertPendingAdmission,
		arg.RoomID,
		arg.UserID,
		arg.InviteID,
		arg.RequestedAt,
	)
	var i RoomAdmission
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.InviteID,
		&i.Status,
		&i.RequestedAt,
		&i.DecidedBy,
		&i.DecidedAt,
	)
	return i, err
}
