// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: badges.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const clearBadgeFromMembers = `-- name: ClearBadgeFromMembers :many
UPDATE workspace_members SET badge_id = NULL WHERE badge_id = $1
RETURNING workspace_id, user_id, role, nickname, joined_at, badge_id, achievement_count
`

// The members that had the badge, now without it (before the badge row goes).
func (q *Queries) ClearBadgeFromMembers(ctx context.Context, badgeID *uuid.UUID) ([]WorkspaceMember, error) {
	rows, err := q.db.Query(ctx, clearBadgeFromMembers, badgeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceMember{}
	for rows.Next() {
		var i WorkspaceMember
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.Role,
			&i.Nickname,
			&i.JoinedAt,
			&i.BadgeID,
			&i.AchievementCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWorkspaceBadges = `-- name: CountWorkspaceBadges :one
SELECT count(*)::integer FROM workspace_badges WHERE workspace_id = $1
`

func (q *Queries) CountWorkspaceBadges(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countWorkspaceBadges, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteWorkspaceBadge = `-- name: DeleteWorkspaceBadge :execrows
DELETE FROM workspace_badges WHERE id = $1 AND workspace_id = $2
`

type DeleteWorkspaceBadgeParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) DeleteWorkspaceBadge(ctx context.Context, arg DeleteWorkspaceBadgeParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceBadge, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getWorkspaceBadge = `-- name: GetWorkspaceBadge :one
SELECT id, workspace_id, name, file_id, position, created_at FROM workspace_badges WHERE id = $1 AND workspace_id = $2
`

type GetWorkspaceBadgeParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetWorkspaceBadge(ctx context.Context, arg GetWorkspaceBadgeParams) (WorkspaceBadge, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBadge, arg.ID, arg.WorkspaceID)
	var i WorkspaceBadge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const insertWorkspaceBadge = `-- name: InsertWorkspaceBadge :one
INSERT INTO workspace_badges (workspace_id, name, file_id, position)
VALUES ($1, $2, $3, (SELECT coalesce(max(b.position), -1) + 1 FROM workspace_badges b WHERE b.workspace_id = $1)::smallint)
RETURNING id, workspace_id, name, file_id, position, created_at
`

type InsertWorkspaceBadgeParams struct {
	WorkspaceID uuid.UUID
	Name        string
	FileID      uuid.UUID
}

func (q *Queries) InsertWorkspaceBadge(ctx context.Context, arg InsertWorkspaceBadgeParams) (WorkspaceBadge, error) {
	row := q.db.QueryRow(ctx, insertWorkspaceBadge, arg.WorkspaceID, arg.Name, arg.FileID)
	var i WorkspaceBadge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const isWorkspaceBadge = `-- name: IsWorkspaceBadge :one
SELECT EXISTS (SELECT 1 FROM workspace_badges WHERE file_id = $1)::boolean
`

// The file is the picture of a badge (files.CanRead: members of its workspace).
func (q *Queries) IsWorkspaceBadge(ctx context.Context, fileID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isWorkspaceBadge, fileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listWorkspaceBadges = `-- name: ListWorkspaceBadges :many
SELECT id, workspace_id, name, file_id, position, created_at FROM workspace_badges WHERE workspace_id = $1 ORDER BY position, id
`

func (q *Queries) ListWorkspaceBadges(ctx context.Context, workspaceID uuid.UUID) ([]WorkspaceBadge, error) {
	rows, err := q.db.Query(ctx, listWorkspaceBadges, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkspaceBadge{}
	for rows.Next() {
		var i WorkspaceBadge
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.FileID,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceBadges = `-- name: LockWorkspaceBadges :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.badges.' || $1::uuid::text))
`

// Member badges (docs/09 #82).
// Serializes badge creation of one workspace between the count and the insert.
func (q *Queries) LockWorkspaceBadges(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockWorkspaceBadges, workspaceID)
	return err
}

const setMemberBadge = `-- name: SetMemberBadge :one
UPDATE workspace_members SET badge_id = $1
WHERE workspace_id = $2 AND user_id = $3
RETURNING workspace_id, user_id, role, nickname, joined_at, badge_id, achievement_count
`

type SetMemberBadgeParams struct {
	BadgeID     *uuid.UUID
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) SetMemberBadge(ctx context.Context, arg SetMemberBadgeParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, setMemberBadge, arg.BadgeID, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
		&i.BadgeID,
		&i.AchievementCount,
	)
	return i, err
}

const updateWorkspaceBadge = `-- name: UpdateWorkspaceBadge :one
UPDATE workspace_badges SET
    name    = coalesce($1, name),
    file_id = coalesce($2, file_id)
WHERE id = $3 AND workspace_id = $4
RETURNING id, workspace_id, name, file_id, position, created_at
`

type UpdateWorkspaceBadgeParams struct {
	Name        *string
	FileID      *uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) UpdateWorkspaceBadge(ctx context.Context, arg UpdateWorkspaceBadgeParams) (WorkspaceBadge, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceBadge,
		arg.Name,
		arg.FileID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i WorkspaceBadge
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.FileID,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
