// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_autotopup.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const billingAutoTopupReconciled = `-- name: BillingAutoTopupReconciled :one
SELECT EXISTS (SELECT 1 FROM billing_audit
               WHERE action = 'auto_topup.reconcile' AND details->>'marker' = $1::text)::boolean
`

// The restore marker (BILLING_AUTO_TOPUP_REQUIRE_RECONCILE) was reconciled by an operator.
func (q *Queries) BillingAutoTopupReconciled(ctx context.Context, marker string) (bool, error) {
	row := q.db.QueryRow(ctx, billingAutoTopupReconciled, marker)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const failBillingAutoTopupAttemptPrepared = `-- name: FailBillingAutoTopupAttemptPrepared :one
UPDATE billing_autotopup_attempts SET status = 'failed', failure_code = $1,
    finished_at = $2::timestamptz
WHERE id = $3 AND status = 'prepared'
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type FailBillingAutoTopupAttemptPreparedParams struct {
	FailureCode string
	Now         time.Time
	ID          uuid.UUID
}

// A prepared attempt that will not be sent (consent revoked, need gone, abandoned by a crash).
func (q *Queries) FailBillingAutoTopupAttemptPrepared(ctx context.Context, arg FailBillingAutoTopupAttemptPreparedParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, failBillingAutoTopupAttemptPrepared, arg.FailureCode, arg.Now, arg.ID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const getBillingChargeByRequest = `-- name: GetBillingChargeByRequest :one
SELECT id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot FROM billing_autotopup_attempts WHERE account_id = $1 AND request_id = $2
`

type GetBillingChargeByRequestParams struct {
	AccountID uuid.UUID
	RequestID *uuid.UUID
}

func (q *Queries) GetBillingChargeByRequest(ctx context.Context, arg GetBillingChargeByRequestParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, getBillingChargeByRequest, arg.AccountID, arg.RequestID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const getBillingCustomerByID = `-- name: GetBillingCustomerByID :one
SELECT id, account_id, provider, provider_account, livemode, customer_id, created_at FROM billing_customers WHERE id = $1
`

func (q *Queries) GetBillingCustomerByID(ctx context.Context, id uuid.UUID) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, getBillingCustomerByID, id)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const getOpenBillingManualCharge = `-- name: GetOpenBillingManualCharge :one
SELECT id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot FROM billing_autotopup_attempts
WHERE account_id = $1 AND kind = 'manual' AND status IN ('prepared', 'dispatched', 'requires_action', 'unknown')
`

// The one-click top-up in flight, if any (the owner's summary shows it).
func (q *Queries) GetOpenBillingManualCharge(ctx context.Context, accountID uuid.UUID) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, getOpenBillingManualCharge, accountID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const insertBillingManualCharge = `-- name: InsertBillingManualCharge :one
INSERT INTO billing_autotopup_attempts (account_id, pm_id, amount_minor, currency, kind, request_id, body_hash, created_by, created_at)
VALUES ($1, $2, $3, $4, 'manual', $5, $6, $7, $8::timestamptz)
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type InsertBillingManualChargeParams struct {
	AccountID   uuid.UUID
	PmID        uuid.UUID
	AmountMinor int64
	Currency    string
	RequestID   *uuid.UUID
	BodyHash    []byte
	CreatedBy   *uuid.UUID
	Now         time.Time
}

// The owner's one-click top-up (kind manual). A second open charge of the account raises
// unique_violation (billing_autotopup_attempts_one_open_idx), a reused request id
// billing_autotopup_attempts_request_idx.
func (q *Queries) InsertBillingManualCharge(ctx context.Context, arg InsertBillingManualChargeParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, insertBillingManualCharge,
		arg.AccountID,
		arg.PmID,
		arg.AmountMinor,
		arg.Currency,
		arg.RequestID,
		arg.BodyHash,
		arg.CreatedBy,
		arg.Now,
	)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const listBillingAutoTopupAttemptsToRecover = `-- name: ListBillingAutoTopupAttemptsToRecover :many
SELECT id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot FROM billing_autotopup_attempts
WHERE status IN ('prepared', 'dispatched', 'requires_action', 'unknown') AND created_at < $1::timestamptz
ORDER BY created_at
LIMIT $2
`

type ListBillingAutoTopupAttemptsToRecoverParams struct {
	Before time.Time
	Lim    int32
}

// Open attempts older than `before`: prepared ones were never sent (abandoned), dispatched /
// unknown ones are resolved with the same idempotency key or a provider lookup.
func (q *Queries) ListBillingAutoTopupAttemptsToRecover(ctx context.Context, arg ListBillingAutoTopupAttemptsToRecoverParams) ([]BillingAutotopupAttempt, error) {
	rows, err := q.db.Query(ctx, listBillingAutoTopupAttemptsToRecover, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingAutotopupAttempt{}
	for rows.Next() {
		var i BillingAutotopupAttempt
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PmID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.ProviderPaymentID,
			&i.FailureCode,
			&i.CreatedAt,
			&i.DispatchedAt,
			&i.FinishedAt,
			&i.Kind,
			&i.RequestID,
			&i.BodyHash,
			&i.CreatedBy,
			&i.ActionUrl,
			&i.OrderSnapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAutoTopupCandidates = `-- name: ListBillingAutoTopupCandidates :many

SELECT t.account_id FROM billing_autotopup t
JOIN billing_accounts a ON a.id = t.account_id
WHERE t.revoked_at IS NULL
  AND t.account_id > $1::uuid
  AND (t.not_before IS NULL OR t.not_before <= $2::timestamptz)
  AND a.status = 'active' AND NOT a.dispute_hold
  AND (a.hold_until IS NULL OR a.hold_until <= $2::timestamptz)
  AND NOT EXISTS (SELECT 1 FROM billing_autotopup_attempts x
                  WHERE x.account_id = t.account_id AND x.status IN ('prepared', 'dispatched', 'requires_action', 'unknown'))
ORDER BY t.account_id
LIMIT $3
`

type ListBillingAutoTopupCandidatesParams struct {
	After uuid.UUID
	Now   time.Time
	Lim   int32
}

// Auto-topup (T7: internal/billing/autotopup, ADR-0080 §7 and v5 «v1 cut»). Same rules as
// billing.sql: every write runs in a transaction that locked the account first; time comes
// from billing.Clock as sqlc.arg('now').
// Accounts that may need an auto-topup now: active, consent not revoked, not_before passed,
// no open attempt, no dispute / incident hold. The need itself (balance under the threshold)
// is decided from the quote; everything is re-checked under the account lock. Keyset pages by
// account_id (after = the last id of the previous page, uuid nil first): a tick walks every
// live consent, so accounts that never needed a top-up cannot starve the others.
func (q *Queries) ListBillingAutoTopupCandidates(ctx context.Context, arg ListBillingAutoTopupCandidatesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBillingAutoTopupCandidates, arg.After, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var account_id uuid.UUID
		if err := rows.Scan(&account_id); err != nil {
			return nil, err
		}
		items = append(items, account_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingAutoTopupReconcileCustomers = `-- name: ListBillingAutoTopupReconcileCustomers :many
SELECT c.id, c.account_id, c.provider, c.provider_account, c.livemode, c.customer_id, c.created_at FROM billing_customers c
WHERE c.account_id IN (
    SELECT t.account_id FROM billing_autotopup t
    WHERE t.revoked_at IS NULL OR t.revoked_at > $1::timestamptz OR t.updated_at > $1::timestamptz
    UNION
    SELECT x.account_id FROM billing_autotopup_attempts x WHERE x.created_at > $1::timestamptz)
ORDER BY c.id
`

// Customers that may have auto-topup payments since `since` (restore reconcile): accounts with a
// consent live or changed since then, or an attempt since then.
func (q *Queries) ListBillingAutoTopupReconcileCustomers(ctx context.Context, since time.Time) ([]BillingCustomer, error) {
	rows, err := q.db.Query(ctx, listBillingAutoTopupReconcileCustomers, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingCustomer{}
	for rows.Next() {
		var i BillingCustomer
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.ProviderAccount,
			&i.Livemode,
			&i.CustomerID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspaceForBillingClose = `-- name: LockWorkspaceForBillingClose :one
SELECT id FROM workspaces WHERE id = $1 FOR UPDATE
`

// Workspace deletion locks the workspace row before the billing account (lock order of
// admission: workspace rows → account).
func (q *Queries) LockWorkspaceForBillingClose(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockWorkspaceForBillingClose, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const markBillingAutoTopupAttemptDispatched = `-- name: MarkBillingAutoTopupAttemptDispatched :one
UPDATE billing_autotopup_attempts SET status = 'dispatched', dispatched_at = $1::timestamptz,
    order_snapshot = $2::text[]
WHERE id = $3 AND status = 'prepared'
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type MarkBillingAutoTopupAttemptDispatchedParams struct {
	Now           time.Time
	OrderSnapshot []string
	ID            uuid.UUID
}

// prepared → dispatched, committed before the provider call: a prepared attempt was never sent.
// order_snapshot: the operations the card's subscription had before the call (providers without
// idempotency keys: the charge is the new one that appears after it).
func (q *Queries) MarkBillingAutoTopupAttemptDispatched(ctx context.Context, arg MarkBillingAutoTopupAttemptDispatchedParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, markBillingAutoTopupAttemptDispatched, arg.Now, arg.OrderSnapshot, arg.ID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const setBillingAttemptRequiresAction = `-- name: SetBillingAttemptRequiresAction :one
UPDATE billing_autotopup_attempts SET status = 'requires_action', provider_payment_id = $1,
    action_url = $2
WHERE id = $3 AND status IN ('dispatched', 'requires_action', 'unknown')
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type SetBillingAttemptRequiresActionParams struct {
	ProviderPaymentID *string
	ActionUrl         string
	ID                uuid.UUID
}

// A one-click charge waits for the payer's 3-D Secure: its payment and the confirmation page.
func (q *Queries) SetBillingAttemptRequiresAction(ctx context.Context, arg SetBillingAttemptRequiresActionParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, setBillingAttemptRequiresAction, arg.ProviderPaymentID, arg.ActionUrl, arg.ID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const setBillingAutoTopupAttemptPayment = `-- name: SetBillingAutoTopupAttemptPayment :one
UPDATE billing_autotopup_attempts SET provider_payment_id = $1,
    status = CASE WHEN status IN ('unknown', 'requires_action') THEN 'dispatched' ELSE status END
WHERE id = $2 AND status IN ('dispatched', 'requires_action', 'unknown')
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type SetBillingAutoTopupAttemptPaymentParams struct {
	ProviderPaymentID *string
	ID                uuid.UUID
}

// The provider answered with a payment of an open attempt that is not final yet (processing):
// keep its id; unknown / requires_action become dispatched again.
func (q *Queries) SetBillingAutoTopupAttemptPayment(ctx context.Context, arg SetBillingAutoTopupAttemptPaymentParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, setBillingAutoTopupAttemptPayment, arg.ProviderPaymentID, arg.ID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const setBillingAutoTopupNotBefore = `-- name: SetBillingAutoTopupNotBefore :exec
UPDATE billing_autotopup SET not_before = GREATEST(coalesce(not_before, $1::timestamptz), $1::timestamptz),
    updated_at = $2::timestamptz
WHERE account_id = $3
`

type SetBillingAutoTopupNotBeforeParams struct {
	NotBefore time.Time
	Now       time.Time
	AccountID uuid.UUID
}

// The next new attempt not earlier than not_before (never moved back).
func (q *Queries) SetBillingAutoTopupNotBefore(ctx context.Context, arg SetBillingAutoTopupNotBeforeParams) error {
	_, err := q.db.Exec(ctx, setBillingAutoTopupNotBefore, arg.NotBefore, arg.Now, arg.AccountID)
	return err
}

const settleBillingAutoTopupAttemptPaid = `-- name: SettleBillingAutoTopupAttemptPaid :one
UPDATE billing_autotopup_attempts SET status = 'succeeded', provider_payment_id = $1,
    failure_code = '', dispatched_at = coalesce(dispatched_at, $2::timestamptz),
    finished_at = coalesce(finished_at, $2::timestamptz)
WHERE id = $3 AND status <> 'succeeded'
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type SettleBillingAutoTopupAttemptPaidParams struct {
	ProviderPaymentID *string
	Now               time.Time
	ID                uuid.UUID
}

// The attempt's payment was credited: succeeded, also after failed (a late success is never
// hidden behind an old failure).
func (q *Queries) SettleBillingAutoTopupAttemptPaid(ctx context.Context, arg SettleBillingAutoTopupAttemptPaidParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, settleBillingAutoTopupAttemptPaid, arg.ProviderPaymentID, arg.Now, arg.ID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}
