// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const appendBillingLedgerEntry = `-- name: AppendBillingLedgerEntry :one
WITH acc AS (
    UPDATE billing_accounts
    SET balance_minor = balance_minor + $2::bigint, entry_seq = entry_seq + 1,
        revision = revision + 1, updated_at = $10::timestamptz
    WHERE billing_accounts.id = $11
    RETURNING id, entry_seq, balance_minor
)
INSERT INTO billing_ledger (account_id, seq, kind, amount_minor, balance_after, business_key,
    lot_id, charge_id, refund_id, dispute_id, actor_id, reason, created_at)
SELECT acc.id, acc.entry_seq, $1, $2::bigint, acc.balance_minor,
    $3, $4, $5, $6,
    $7, $8, $9, $10::timestamptz
FROM acc
RETURNING id, account_id, seq, kind, amount_minor, balance_after, business_key, lot_id, charge_id, refund_id, dispute_id, actor_id, reason, created_at
`

type AppendBillingLedgerEntryParams struct {
	Kind        string
	AmountMinor int64
	BusinessKey string
	LotID       *uuid.UUID
	ChargeID    *uuid.UUID
	RefundID    *uuid.UUID
	DisputeID   *uuid.UUID
	ActorID     *uuid.UUID
	Reason      string
	Now         time.Time
	AccountID   uuid.UUID
}

// Appends one entry and moves the balance cache and entry_seq in the same statement. The
// account must be locked by the caller. A duplicate business_key raises unique_violation
// (and rolls the balance back with the statement): check GetBillingLedgerEntryByKey first.
func (q *Queries) AppendBillingLedgerEntry(ctx context.Context, arg AppendBillingLedgerEntryParams) (BillingLedger, error) {
	row := q.db.QueryRow(ctx, appendBillingLedgerEntry,
		arg.Kind,
		arg.AmountMinor,
		arg.BusinessKey,
		arg.LotID,
		arg.ChargeID,
		arg.RefundID,
		arg.DisputeID,
		arg.ActorID,
		arg.Reason,
		arg.Now,
		arg.AccountID,
	)
	var i BillingLedger
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seq,
		&i.Kind,
		&i.AmountMinor,
		&i.BalanceAfter,
		&i.BusinessKey,
		&i.LotID,
		&i.ChargeID,
		&i.RefundID,
		&i.DisputeID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const billingAccountMarketFixed = `-- name: BillingAccountMarketFixed :one
SELECT (a.entry_seq > 0 OR a.balance_minor <> 0
        OR EXISTS (SELECT 1 FROM billing_payments p WHERE p.account_id = a.id)
        OR EXISTS (SELECT 1 FROM billing_checkouts c WHERE c.account_id = a.id AND c.status = 'open'))::boolean AS fixed
FROM billing_accounts a WHERE a.id = $1
`

// ADR-0083: the market of an account is fixed by its first money: a ledger entry, any payment
// row (even a processing one) or an open checkout. Read under the account lock.
func (q *Queries) BillingAccountMarketFixed(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, billingAccountMarketFixed, id)
	var fixed bool
	err := row.Scan(&fixed)
	return fixed, err
}

const billingNow = `-- name: BillingNow :one

SELECT clock_timestamp()::timestamptz AS now
`

// Balance billing v1 (ADR-0080 v5, migration 00074): the base queries of the foundation (T0).
//
// Ownership: this file is frozen after T0 so parallel tasks do not collide. Add new queries in
// your own file instead: billing_core.sql (T1 core / worker), billing_stripe.sql (T2),
// billing_http.sql (T5 HTTP / inbox / mail), billing_admin.sql (T6), billing_autotopup.sql
// (T7). Query names start with Billing… or a billing noun so they stay unique.
//
// Rules for every billing query:
//   - money mutations run inside one transaction that first locks the account
//     (LockBillingAccount / LockLiveBillingAccountByWorkspace) — no network inside it;
//   - time comes from billing.Clock (sqlc.arg('now')), not now(), so the fake clock drives
//     deadlines and renewals in tests; created_at / updated_at defaults are bookkeeping only;
//   - provider ids are idempotency keys: inserts use ON CONFLICT … DO NOTHING RETURNING and
//     treat "no row" as "already there" (then Get… the existing row).
//
// Database time for billing.DBClock: call it after taking the account lock.
func (q *Queries) BillingNow(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, billingNow)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const claimBillingAccountsDue = `-- name: ClaimBillingAccountsDue :many
SELECT id FROM billing_accounts
WHERE status = 'active' AND next_due_at <= $1::timestamptz
ORDER BY next_due_at
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type ClaimBillingAccountsDueParams struct {
	Now time.Time
	Lim int32
}

// Active accounts whose seat lots are due for renewal, oldest first. Run it in the renewal
// transaction of a small batch: SKIP LOCKED lets parallel workers take different accounts (the
// rows stay locked until that transaction ends; re-check next_due_at on each row).
func (q *Queries) ClaimBillingAccountsDue(ctx context.Context, arg ClaimBillingAccountsDueParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimBillingAccountsDue, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimBillingProviderEvents = `-- name: ClaimBillingProviderEvents :many
UPDATE billing_provider_events SET next_attempt_at = $1::timestamptz + $2::interval,
    attempts = attempts + 1
WHERE id IN (
    SELECT e.id FROM billing_provider_events e
    WHERE e.processed_at IS NULL AND e.next_attempt_at <= $1::timestamptz
    ORDER BY e.next_attempt_at, e.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, provider, provider_account, livemode, event_id, kind, object_id, payload, received_at, next_attempt_at, attempts, processed_at, error
`

type ClaimBillingProviderEventsParams struct {
	Now   time.Time
	Lease pgtype.Interval
	Lim   int32
}

// Due unprocessed events, oldest first; next_attempt_at moves one lease ahead so a crashed
// worker's events are retried and a second worker skips them.
func (q *Queries) ClaimBillingProviderEvents(ctx context.Context, arg ClaimBillingProviderEventsParams) ([]BillingProviderEvent, error) {
	rows, err := q.db.Query(ctx, claimBillingProviderEvents, arg.Now, arg.Lease, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingProviderEvent{}
	for rows.Next() {
		var i BillingProviderEvent
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.ProviderAccount,
			&i.Livemode,
			&i.EventID,
			&i.Kind,
			&i.ObjectID,
			&i.Payload,
			&i.ReceivedAt,
			&i.NextAttemptAt,
			&i.Attempts,
			&i.ProcessedAt,
			&i.Error,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const compensateBillingCharge = `-- name: CompensateBillingCharge :one
UPDATE billing_charges SET compensated_minor = compensated_minor + $1::bigint,
    unfunded_minor = unfunded_minor - $2::bigint
WHERE id = $3
RETURNING id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us
`

type CompensateBillingChargeParams struct {
	Delta     int64
	DebtDelta int64
	ID        uuid.UUID
}

// Unused part returned (seat removed / plan change); debt_delta cancels debt first.
func (q *Queries) CompensateBillingCharge(ctx context.Context, arg CompensateBillingChargeParams) (BillingCharge, error) {
	row := q.db.QueryRow(ctx, compensateBillingCharge, arg.Delta, arg.DebtDelta, arg.ID)
	var i BillingCharge
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sku,
		&i.Plan,
		&i.PriceID,
		&i.Qty,
		&i.UnitMinor,
		&i.DiscountBps,
		&i.StartsAt,
		&i.EndsAt,
		&i.AmountMinor,
		&i.UnfundedMinor,
		&i.CompensatedMinor,
		&i.Reason,
		&i.BusinessKey,
		&i.ActorID,
		&i.CreatedAt,
		&i.CanceledQty,
		&i.CanceledSeatUs,
	)
	return i, err
}

const consumeBillingFundingLot = `-- name: ConsumeBillingFundingLot :one
UPDATE billing_funding_lots SET consumed_minor = consumed_minor + $1::bigint
WHERE id = $2
RETURNING id, account_id, source, payment_id, amount_minor, consumed_minor, refunded_minor, actor_id, reason, created_at
`

type ConsumeBillingFundingLotParams struct {
	Delta int64
	ID    uuid.UUID
}

// delta may be negative (reversal). The CHECK keeps consumed + refunded within the amount.
func (q *Queries) ConsumeBillingFundingLot(ctx context.Context, arg ConsumeBillingFundingLotParams) (BillingFundingLot, error) {
	row := q.db.QueryRow(ctx, consumeBillingFundingLot, arg.Delta, arg.ID)
	var i BillingFundingLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.PaymentID,
		&i.AmountMinor,
		&i.ConsumedMinor,
		&i.RefundedMinor,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const countBillableMembers = `-- name: CountBillableMembers :one
SELECT count(*)::integer FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.role <> 'guest' AND NOT u.is_bot
`

// Paid seats: members except guests and bots (the owner included). plans.KindMembers, which
// counts bots, stays the hard plan limit.
func (q *Queries) CountBillableMembers(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBillableMembers, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const fundBillingCharge = `-- name: FundBillingCharge :one
UPDATE billing_charges SET unfunded_minor = unfunded_minor - $1::bigint
WHERE id = $2 AND unfunded_minor >= $1::bigint
RETURNING id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us
`

type FundBillingChargeParams struct {
	Delta int64
	ID    uuid.UUID
}

// A top-up paid delta of the charge's debt part.
func (q *Queries) FundBillingCharge(ctx context.Context, arg FundBillingChargeParams) (BillingCharge, error) {
	row := q.db.QueryRow(ctx, fundBillingCharge, arg.Delta, arg.ID)
	var i BillingCharge
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sku,
		&i.Plan,
		&i.PriceID,
		&i.Qty,
		&i.UnitMinor,
		&i.DiscountBps,
		&i.StartsAt,
		&i.EndsAt,
		&i.AmountMinor,
		&i.UnfundedMinor,
		&i.CompensatedMinor,
		&i.Reason,
		&i.BusinessKey,
		&i.ActorID,
		&i.CreatedAt,
		&i.CanceledQty,
		&i.CanceledSeatUs,
	)
	return i, err
}

const getBillingAccount = `-- name: GetBillingAccount :one
SELECT id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at FROM billing_accounts WHERE id = $1
`

func (q *Queries) GetBillingAccount(ctx context.Context, id uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getBillingAccount, id)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getBillingAuditByRequest = `-- name: GetBillingAuditByRequest :one
SELECT id, request_id, body_hash, account_id, workspace_id, actor_id, action, reason, details, created_at FROM billing_audit WHERE request_id = $1
`

func (q *Queries) GetBillingAuditByRequest(ctx context.Context, requestID uuid.UUID) (BillingAudit, error) {
	row := q.db.QueryRow(ctx, getBillingAuditByRequest, requestID)
	var i BillingAudit
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.BodyHash,
		&i.AccountID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Action,
		&i.Reason,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingAutoTopup = `-- name: GetBillingAutoTopup :one
SELECT account_id, pm_id, max_minor, consent_version, consent_at, consent_by, revoked_at, revoked_reason, not_before, updated_at FROM billing_autotopup WHERE account_id = $1
`

func (q *Queries) GetBillingAutoTopup(ctx context.Context, accountID uuid.UUID) (BillingAutotopup, error) {
	row := q.db.QueryRow(ctx, getBillingAutoTopup, accountID)
	var i BillingAutotopup
	err := row.Scan(
		&i.AccountID,
		&i.PmID,
		&i.MaxMinor,
		&i.ConsentVersion,
		&i.ConsentAt,
		&i.ConsentBy,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.NotBefore,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingCheckout = `-- name: GetBillingCheckout :one
SELECT id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls FROM billing_checkouts WHERE id = $1
`

func (q *Queries) GetBillingCheckout(ctx context.Context, id uuid.UUID) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, getBillingCheckout, id)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const getBillingCheckoutByRequest = `-- name: GetBillingCheckoutByRequest :one
SELECT id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls FROM billing_checkouts WHERE account_id = $1 AND request_id = $2
`

type GetBillingCheckoutByRequestParams struct {
	AccountID uuid.UUID
	RequestID uuid.UUID
}

func (q *Queries) GetBillingCheckoutByRequest(ctx context.Context, arg GetBillingCheckoutByRequestParams) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, getBillingCheckoutByRequest, arg.AccountID, arg.RequestID)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const getBillingCheckoutBySession = `-- name: GetBillingCheckoutBySession :one
SELECT id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls FROM billing_checkouts WHERE provider_session_id = $1
`

func (q *Queries) GetBillingCheckoutBySession(ctx context.Context, providerSessionID *string) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, getBillingCheckoutBySession, providerSessionID)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const getBillingCustomer = `-- name: GetBillingCustomer :one
SELECT id, account_id, provider, provider_account, livemode, customer_id, created_at FROM billing_customers WHERE account_id = $1 AND provider = $2 AND livemode = $3
`

type GetBillingCustomerParams struct {
	AccountID uuid.UUID
	Provider  string
	Livemode  bool
}

func (q *Queries) GetBillingCustomer(ctx context.Context, arg GetBillingCustomerParams) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, getBillingCustomer, arg.AccountID, arg.Provider, arg.Livemode)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingCustomerByProviderID = `-- name: GetBillingCustomerByProviderID :one
SELECT id, account_id, provider, provider_account, livemode, customer_id, created_at FROM billing_customers
WHERE provider = $1 AND provider_account = $2 AND livemode = $3 AND customer_id = $4
`

type GetBillingCustomerByProviderIDParams struct {
	Provider        string
	ProviderAccount string
	Livemode        bool
	CustomerID      string
}

func (q *Queries) GetBillingCustomerByProviderID(ctx context.Context, arg GetBillingCustomerByProviderIDParams) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, getBillingCustomerByProviderID,
		arg.Provider,
		arg.ProviderAccount,
		arg.Livemode,
		arg.CustomerID,
	)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingDisputeByProviderID = `-- name: GetBillingDisputeByProviderID :one
SELECT id, account_id, payment_id, provider_dispute_id, amount_minor, currency, status, outcome, created_at, closed_at FROM billing_disputes WHERE provider_dispute_id = $1
`

func (q *Queries) GetBillingDisputeByProviderID(ctx context.Context, providerDisputeID string) (BillingDispute, error) {
	row := q.db.QueryRow(ctx, getBillingDisputeByProviderID, providerDisputeID)
	var i BillingDispute
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PaymentID,
		&i.ProviderDisputeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Outcome,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getBillingLedgerEntryByKey = `-- name: GetBillingLedgerEntryByKey :one
SELECT id, account_id, seq, kind, amount_minor, balance_after, business_key, lot_id, charge_id, refund_id, dispute_id, actor_id, reason, created_at FROM billing_ledger WHERE business_key = $1
`

func (q *Queries) GetBillingLedgerEntryByKey(ctx context.Context, businessKey string) (BillingLedger, error) {
	row := q.db.QueryRow(ctx, getBillingLedgerEntryByKey, businessKey)
	var i BillingLedger
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Seq,
		&i.Kind,
		&i.AmountMinor,
		&i.BalanceAfter,
		&i.BusinessKey,
		&i.LotID,
		&i.ChargeID,
		&i.RefundID,
		&i.DisputeID,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingPayer = `-- name: GetBillingPayer :one
SELECT account_id, type, name, country, email, tax_id, updated_by, updated_at FROM billing_payers WHERE account_id = $1
`

func (q *Queries) GetBillingPayer(ctx context.Context, accountID uuid.UUID) (BillingPayer, error) {
	row := q.db.QueryRow(ctx, getBillingPayer, accountID)
	var i BillingPayer
	err := row.Scan(
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.Country,
		&i.Email,
		&i.TaxID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingPayment = `-- name: GetBillingPayment :one
SELECT id, account_id, provider, provider_account, livemode, provider_payment_id, provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url, refunded_minor, succeeded_at, created_at, updated_at FROM billing_payments WHERE id = $1
`

func (q *Queries) GetBillingPayment(ctx context.Context, id uuid.UUID) (BillingPayment, error) {
	row := q.db.QueryRow(ctx, getBillingPayment, id)
	var i BillingPayment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.ProviderPaymentID,
		&i.ProviderChargeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.CheckoutID,
		&i.AttemptID,
		&i.ReceiptUrl,
		&i.RefundedMinor,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingPaymentByProviderID = `-- name: GetBillingPaymentByProviderID :one
SELECT id, account_id, provider, provider_account, livemode, provider_payment_id, provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url, refunded_minor, succeeded_at, created_at, updated_at FROM billing_payments
WHERE provider = $1 AND provider_account = $2 AND livemode = $3 AND provider_payment_id = $4
`

type GetBillingPaymentByProviderIDParams struct {
	Provider          string
	ProviderAccount   string
	Livemode          bool
	ProviderPaymentID string
}

func (q *Queries) GetBillingPaymentByProviderID(ctx context.Context, arg GetBillingPaymentByProviderIDParams) (BillingPayment, error) {
	row := q.db.QueryRow(ctx, getBillingPaymentByProviderID,
		arg.Provider,
		arg.ProviderAccount,
		arg.Livemode,
		arg.ProviderPaymentID,
	)
	var i BillingPayment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.ProviderPaymentID,
		&i.ProviderChargeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.CheckoutID,
		&i.AttemptID,
		&i.ReceiptUrl,
		&i.RefundedMinor,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBillingPriceAt = `-- name: GetBillingPriceAt :one
SELECT id, market, currency, sku, plan, unit_minor, effective_from, created_by, created_at FROM billing_prices
WHERE market = $1 AND sku = $2 AND effective_from <= $3::timestamptz
ORDER BY effective_from DESC
LIMIT 1
`

type GetBillingPriceAtParams struct {
	Market string
	Sku    string
	At     time.Time
}

// The price version of a SKU in effect at `at`.
func (q *Queries) GetBillingPriceAt(ctx context.Context, arg GetBillingPriceAtParams) (BillingPrice, error) {
	row := q.db.QueryRow(ctx, getBillingPriceAt, arg.Market, arg.Sku, arg.At)
	var i BillingPrice
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Currency,
		&i.Sku,
		&i.Plan,
		&i.UnitMinor,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getBillingRefundByIdemKey = `-- name: GetBillingRefundByIdemKey :one
SELECT id, account_id, payment_id, lot_id, amount_minor, currency, status, origin, provider_refund_id, idem_key, reason, requested_by, created_at, updated_at, succeeded_at, needs_review_at, dispatched_at FROM billing_refunds WHERE idem_key = $1
`

func (q *Queries) GetBillingRefundByIdemKey(ctx context.Context, idemKey string) (BillingRefund, error) {
	row := q.db.QueryRow(ctx, getBillingRefundByIdemKey, idemKey)
	var i BillingRefund
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PaymentID,
		&i.LotID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.ProviderRefundID,
		&i.IdemKey,
		&i.Reason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucceededAt,
		&i.NeedsReviewAt,
		&i.DispatchedAt,
	)
	return i, err
}

const getBillingRefundByProviderID = `-- name: GetBillingRefundByProviderID :one
SELECT id, account_id, payment_id, lot_id, amount_minor, currency, status, origin, provider_refund_id, idem_key, reason, requested_by, created_at, updated_at, succeeded_at, needs_review_at, dispatched_at FROM billing_refunds WHERE provider_refund_id = $1
`

func (q *Queries) GetBillingRefundByProviderID(ctx context.Context, providerRefundID *string) (BillingRefund, error) {
	row := q.db.QueryRow(ctx, getBillingRefundByProviderID, providerRefundID)
	var i BillingRefund
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PaymentID,
		&i.LotID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.ProviderRefundID,
		&i.IdemKey,
		&i.Reason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucceededAt,
		&i.NeedsReviewAt,
		&i.DispatchedAt,
	)
	return i, err
}

const getLastBillingAutoTopupAttempt = `-- name: GetLastBillingAutoTopupAttempt :one
SELECT id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot FROM billing_autotopup_attempts WHERE account_id = $1 AND kind = 'auto' ORDER BY created_at DESC, id DESC LIMIT 1
`

func (q *Queries) GetLastBillingAutoTopupAttempt(ctx context.Context, accountID uuid.UUID) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, getLastBillingAutoTopupAttempt, accountID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const getLiveBillingAccountByWorkspace = `-- name: GetLiveBillingAccountByWorkspace :one
SELECT id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at FROM billing_accounts WHERE workspace_id = $1 AND status <> 'closed'
`

func (q *Queries) GetLiveBillingAccountByWorkspace(ctx context.Context, workspaceID *uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, getLiveBillingAccountByWorkspace, workspaceID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const getOpenBillingAutoTopupAttempt = `-- name: GetOpenBillingAutoTopupAttempt :one
SELECT id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot FROM billing_autotopup_attempts
WHERE account_id = $1 AND status IN ('prepared', 'dispatched', 'requires_action', 'unknown')
`

// The charge of a saved card in flight (auto or one-click): at most one per account.
func (q *Queries) GetOpenBillingAutoTopupAttempt(ctx context.Context, accountID uuid.UUID) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, getOpenBillingAutoTopupAttempt, accountID)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const getOpenBillingCheckout = `-- name: GetOpenBillingCheckout :one
SELECT id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls FROM billing_checkouts WHERE account_id = $1 AND status = 'open'
`

func (q *Queries) GetOpenBillingCheckout(ctx context.Context, accountID uuid.UUID) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, getOpenBillingCheckout, accountID)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const insertBillingAccount = `-- name: InsertBillingAccount :one
INSERT INTO billing_accounts (workspace_id, market, currency, provider, plan, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at
`

type InsertBillingAccountParams struct {
	WorkspaceID *uuid.UUID
	Market      string
	Currency    string
	Provider    string
	Plan        string
	CreatedBy   *uuid.UUID
}

func (q *Queries) InsertBillingAccount(ctx context.Context, arg InsertBillingAccountParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, insertBillingAccount,
		arg.WorkspaceID,
		arg.Market,
		arg.Currency,
		arg.Provider,
		arg.Plan,
		arg.CreatedBy,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const insertBillingAllocation = `-- name: InsertBillingAllocation :one
INSERT INTO billing_allocations (account_id, charge_id, lot_id, amount_minor)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, charge_id, lot_id, amount_minor, created_at
`

type InsertBillingAllocationParams struct {
	AccountID   uuid.UUID
	ChargeID    uuid.UUID
	LotID       uuid.UUID
	AmountMinor int64
}

func (q *Queries) InsertBillingAllocation(ctx context.Context, arg InsertBillingAllocationParams) (BillingAllocation, error) {
	row := q.db.QueryRow(ctx, insertBillingAllocation,
		arg.AccountID,
		arg.ChargeID,
		arg.LotID,
		arg.AmountMinor,
	)
	var i BillingAllocation
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ChargeID,
		&i.LotID,
		&i.AmountMinor,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingAudit = `-- name: InsertBillingAudit :one
INSERT INTO billing_audit (request_id, body_hash, account_id, workspace_id, actor_id, action, reason, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (request_id) DO NOTHING
RETURNING id, request_id, body_hash, account_id, workspace_id, actor_id, action, reason, details, created_at
`

type InsertBillingAuditParams struct {
	RequestID   uuid.UUID
	BodyHash    []byte
	AccountID   *uuid.UUID
	WorkspaceID *uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	Reason      string
	Details     []byte
}

// No row = request_id was used (GetBillingAuditByRequest: same body_hash = replay, else 409).
func (q *Queries) InsertBillingAudit(ctx context.Context, arg InsertBillingAuditParams) (BillingAudit, error) {
	row := q.db.QueryRow(ctx, insertBillingAudit,
		arg.RequestID,
		arg.BodyHash,
		arg.AccountID,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Action,
		arg.Reason,
		arg.Details,
	)
	var i BillingAudit
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.BodyHash,
		&i.AccountID,
		&i.WorkspaceID,
		&i.ActorID,
		&i.Action,
		&i.Reason,
		&i.Details,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingAutoTopupAttempt = `-- name: InsertBillingAutoTopupAttempt :one
INSERT INTO billing_autotopup_attempts (account_id, pm_id, amount_minor, currency, created_at)
VALUES ($1, $2, $3, $4, $5::timestamptz)
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type InsertBillingAutoTopupAttemptParams struct {
	AccountID   uuid.UUID
	PmID        uuid.UUID
	AmountMinor int64
	Currency    string
	Now         time.Time
}

// A second open attempt of the account raises unique_violation
// (billing_autotopup_attempts_one_open_idx): never two charges in flight.
func (q *Queries) InsertBillingAutoTopupAttempt(ctx context.Context, arg InsertBillingAutoTopupAttemptParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, insertBillingAutoTopupAttempt,
		arg.AccountID,
		arg.PmID,
		arg.AmountMinor,
		arg.Currency,
		arg.Now,
	)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const insertBillingCharge = `-- name: InsertBillingCharge :one
INSERT INTO billing_charges (account_id, sku, plan, price_id, qty, unit_minor, discount_bps,
    starts_at, ends_at, amount_minor, unfunded_minor, reason, business_key, actor_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (business_key) DO NOTHING
RETURNING id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us
`

type InsertBillingChargeParams struct {
	AccountID     uuid.UUID
	Sku           string
	Plan          string
	PriceID       uuid.UUID
	Qty           int32
	UnitMinor     int64
	DiscountBps   int32
	StartsAt      time.Time
	EndsAt        time.Time
	AmountMinor   int64
	UnfundedMinor int64
	Reason        string
	BusinessKey   string
	ActorID       *uuid.UUID
}

// No row = the business key exists (renew:{account}:{starts_at}, admit:{request_id}, …).
func (q *Queries) InsertBillingCharge(ctx context.Context, arg InsertBillingChargeParams) (BillingCharge, error) {
	row := q.db.QueryRow(ctx, insertBillingCharge,
		arg.AccountID,
		arg.Sku,
		arg.Plan,
		arg.PriceID,
		arg.Qty,
		arg.UnitMinor,
		arg.DiscountBps,
		arg.StartsAt,
		arg.EndsAt,
		arg.AmountMinor,
		arg.UnfundedMinor,
		arg.Reason,
		arg.BusinessKey,
		arg.ActorID,
	)
	var i BillingCharge
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Sku,
		&i.Plan,
		&i.PriceID,
		&i.Qty,
		&i.UnitMinor,
		&i.DiscountBps,
		&i.StartsAt,
		&i.EndsAt,
		&i.AmountMinor,
		&i.UnfundedMinor,
		&i.CompensatedMinor,
		&i.Reason,
		&i.BusinessKey,
		&i.ActorID,
		&i.CreatedAt,
		&i.CanceledQty,
		&i.CanceledSeatUs,
	)
	return i, err
}

const insertBillingCheckout = `-- name: InsertBillingCheckout :one
INSERT INTO billing_checkouts (account_id, request_id, body_hash, purpose, method_id, provider,
    amount_minor, currency, save_method, payer_snapshot, created_by, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (account_id, request_id) DO NOTHING
RETURNING id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls
`

type InsertBillingCheckoutParams struct {
	AccountID     uuid.UUID
	RequestID     uuid.UUID
	BodyHash      []byte
	Purpose       string
	MethodID      string
	Provider      string
	AmountMinor   int64
	Currency      string
	SaveMethod    bool
	PayerSnapshot []byte
	CreatedBy     *uuid.UUID
	ExpiresAt     *time.Time
}

// No row = this request_id exists (GetBillingCheckoutByRequest: same body_hash → same result,
// else 409). A second open checkout of the account raises unique_violation
// (billing_checkouts_one_open_idx): answer 409 BILLING_PAYMENT_PENDING with the open one.
func (q *Queries) InsertBillingCheckout(ctx context.Context, arg InsertBillingCheckoutParams) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, insertBillingCheckout,
		arg.AccountID,
		arg.RequestID,
		arg.BodyHash,
		arg.Purpose,
		arg.MethodID,
		arg.Provider,
		arg.AmountMinor,
		arg.Currency,
		arg.SaveMethod,
		arg.PayerSnapshot,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const insertBillingCustomer = `-- name: InsertBillingCustomer :one
INSERT INTO billing_customers (account_id, provider, provider_account, livemode, customer_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT DO NOTHING
RETURNING id, account_id, provider, provider_account, livemode, customer_id, created_at
`

type InsertBillingCustomerParams struct {
	AccountID       uuid.UUID
	Provider        string
	ProviderAccount string
	Livemode        bool
	CustomerID      string
}

// No row = the account already has a customer of this provider/mode (GetBillingCustomer).
func (q *Queries) InsertBillingCustomer(ctx context.Context, arg InsertBillingCustomerParams) (BillingCustomer, error) {
	row := q.db.QueryRow(ctx, insertBillingCustomer,
		arg.AccountID,
		arg.Provider,
		arg.ProviderAccount,
		arg.Livemode,
		arg.CustomerID,
	)
	var i BillingCustomer
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.CustomerID,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingDispute = `-- name: InsertBillingDispute :one
INSERT INTO billing_disputes (account_id, payment_id, provider_dispute_id, amount_minor, currency)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (provider_dispute_id) DO NOTHING
RETURNING id, account_id, payment_id, provider_dispute_id, amount_minor, currency, status, outcome, created_at, closed_at
`

type InsertBillingDisputeParams struct {
	AccountID         uuid.UUID
	PaymentID         uuid.UUID
	ProviderDisputeID string
	AmountMinor       int64
	Currency          string
}

func (q *Queries) InsertBillingDispute(ctx context.Context, arg InsertBillingDisputeParams) (BillingDispute, error) {
	row := q.db.QueryRow(ctx, insertBillingDispute,
		arg.AccountID,
		arg.PaymentID,
		arg.ProviderDisputeID,
		arg.AmountMinor,
		arg.Currency,
	)
	var i BillingDispute
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PaymentID,
		&i.ProviderDisputeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Outcome,
		&i.CreatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const insertBillingFundingLot = `-- name: InsertBillingFundingLot :one
INSERT INTO billing_funding_lots (account_id, source, payment_id, amount_minor, actor_id, reason)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (payment_id) DO NOTHING
RETURNING id, account_id, source, payment_id, amount_minor, consumed_minor, refunded_minor, actor_id, reason, created_at
`

type InsertBillingFundingLotParams struct {
	AccountID   uuid.UUID
	Source      string
	PaymentID   *uuid.UUID
	AmountMinor int64
	ActorID     *uuid.UUID
	Reason      string
}

// No row = the payment already has its lot (UNIQUE payment_id): never credit twice.
func (q *Queries) InsertBillingFundingLot(ctx context.Context, arg InsertBillingFundingLotParams) (BillingFundingLot, error) {
	row := q.db.QueryRow(ctx, insertBillingFundingLot,
		arg.AccountID,
		arg.Source,
		arg.PaymentID,
		arg.AmountMinor,
		arg.ActorID,
		arg.Reason,
	)
	var i BillingFundingLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.PaymentID,
		&i.AmountMinor,
		&i.ConsumedMinor,
		&i.RefundedMinor,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingNotification = `-- name: InsertBillingNotification :one
INSERT INTO billing_notifications (account_id, key, template, mail_id)
VALUES ($1, $2, $3, $4)
ON CONFLICT (account_id, key) DO NOTHING
RETURNING id, account_id, key, template, mail_id, created_at
`

type InsertBillingNotificationParams struct {
	AccountID uuid.UUID
	Key       string
	Template  string
	MailID    *uuid.UUID
}

// No row = this mail was already queued for the account (dedup by business key).
func (q *Queries) InsertBillingNotification(ctx context.Context, arg InsertBillingNotificationParams) (BillingNotification, error) {
	row := q.db.QueryRow(ctx, insertBillingNotification,
		arg.AccountID,
		arg.Key,
		arg.Template,
		arg.MailID,
	)
	var i BillingNotification
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Key,
		&i.Template,
		&i.MailID,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingPayment = `-- name: InsertBillingPayment :one
INSERT INTO billing_payments (account_id, provider, provider_account, livemode, provider_payment_id,
    provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url,
    succeeded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
ON CONFLICT (provider, provider_account, livemode, provider_payment_id) DO NOTHING
RETURNING id, account_id, provider, provider_account, livemode, provider_payment_id, provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url, refunded_minor, succeeded_at, created_at, updated_at
`

type InsertBillingPaymentParams struct {
	AccountID         uuid.UUID
	Provider          string
	ProviderAccount   string
	Livemode          bool
	ProviderPaymentID string
	ProviderChargeID  *string
	AmountMinor       int64
	Currency          string
	Status            string
	Origin            string
	CheckoutID        *uuid.UUID
	AttemptID         *uuid.UUID
	ReceiptUrl        string
	SucceededAt       *time.Time
}

// No row = this provider payment is already recorded (GetBillingPaymentByProviderID). The
// unique key is the one-credit-per-PaymentIntent guarantee.
func (q *Queries) InsertBillingPayment(ctx context.Context, arg InsertBillingPaymentParams) (BillingPayment, error) {
	row := q.db.QueryRow(ctx, insertBillingPayment,
		arg.AccountID,
		arg.Provider,
		arg.ProviderAccount,
		arg.Livemode,
		arg.ProviderPaymentID,
		arg.ProviderChargeID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.Origin,
		arg.CheckoutID,
		arg.AttemptID,
		arg.ReceiptUrl,
		arg.SucceededAt,
	)
	var i BillingPayment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.ProviderPaymentID,
		&i.ProviderChargeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.CheckoutID,
		&i.AttemptID,
		&i.ReceiptUrl,
		&i.RefundedMinor,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBillingPrice = `-- name: InsertBillingPrice :one
INSERT INTO billing_prices (market, currency, sku, plan, unit_minor, effective_from, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, market, currency, sku, plan, unit_minor, effective_from, created_by, created_at
`

type InsertBillingPriceParams struct {
	Market        string
	Currency      string
	Sku           string
	Plan          *string
	UnitMinor     int64
	EffectiveFrom time.Time
	CreatedBy     *uuid.UUID
}

func (q *Queries) InsertBillingPrice(ctx context.Context, arg InsertBillingPriceParams) (BillingPrice, error) {
	row := q.db.QueryRow(ctx, insertBillingPrice,
		arg.Market,
		arg.Currency,
		arg.Sku,
		arg.Plan,
		arg.UnitMinor,
		arg.EffectiveFrom,
		arg.CreatedBy,
	)
	var i BillingPrice
	err := row.Scan(
		&i.ID,
		&i.Market,
		&i.Currency,
		&i.Sku,
		&i.Plan,
		&i.UnitMinor,
		&i.EffectiveFrom,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBillingProviderEvent = `-- name: InsertBillingProviderEvent :one
INSERT INTO billing_provider_events (provider, provider_account, livemode, event_id, kind, object_id, payload)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (provider, provider_account, event_id) DO NOTHING
RETURNING id
`

type InsertBillingProviderEventParams struct {
	Provider        string
	ProviderAccount string
	Livemode        bool
	EventID         string
	Kind            string
	ObjectID        string
	Payload         []byte
}

// After the signature check; no row = duplicate delivery (ACK 200 all the same).
func (q *Queries) InsertBillingProviderEvent(ctx context.Context, arg InsertBillingProviderEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertBillingProviderEvent,
		arg.Provider,
		arg.ProviderAccount,
		arg.Livemode,
		arg.EventID,
		arg.Kind,
		arg.ObjectID,
		arg.Payload,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertBillingRefund = `-- name: InsertBillingRefund :one
INSERT INTO billing_refunds (account_id, payment_id, lot_id, amount_minor, currency, status, origin,
    provider_refund_id, idem_key, reason, requested_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT DO NOTHING
RETURNING id, account_id, payment_id, lot_id, amount_minor, currency, status, origin, provider_refund_id, idem_key, reason, requested_by, created_at, updated_at, succeeded_at, needs_review_at, dispatched_at
`

type InsertBillingRefundParams struct {
	AccountID        uuid.UUID
	PaymentID        uuid.UUID
	LotID            *uuid.UUID
	AmountMinor      int64
	Currency         string
	Status           string
	Origin           string
	ProviderRefundID *string
	IdemKey          string
	Reason           string
	RequestedBy      *uuid.UUID
}

// No row = idem_key / provider_refund_id exists (GetBillingRefundByIdemKey). Refundable
// amount is checked by the caller under the account lock.
func (q *Queries) InsertBillingRefund(ctx context.Context, arg InsertBillingRefundParams) (BillingRefund, error) {
	row := q.db.QueryRow(ctx, insertBillingRefund,
		arg.AccountID,
		arg.PaymentID,
		arg.LotID,
		arg.AmountMinor,
		arg.Currency,
		arg.Status,
		arg.Origin,
		arg.ProviderRefundID,
		arg.IdemKey,
		arg.Reason,
		arg.RequestedBy,
	)
	var i BillingRefund
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PaymentID,
		&i.LotID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.ProviderRefundID,
		&i.IdemKey,
		&i.Reason,
		&i.RequestedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SucceededAt,
		&i.NeedsReviewAt,
		&i.DispatchedAt,
	)
	return i, err
}

const insertBillingRefundRequest = `-- name: InsertBillingRefundRequest :one
INSERT INTO billing_refund_requests (account_id, request_id, amount_minor, reason, requested_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, request_id) DO NOTHING
RETURNING id, account_id, request_id, amount_minor, reason, status, requested_by, decided_by, created_at, decided_at
`

type InsertBillingRefundRequestParams struct {
	AccountID   uuid.UUID
	RequestID   uuid.UUID
	AmountMinor int64
	Reason      string
	RequestedBy *uuid.UUID
}

func (q *Queries) InsertBillingRefundRequest(ctx context.Context, arg InsertBillingRefundRequestParams) (BillingRefundRequest, error) {
	row := q.db.QueryRow(ctx, insertBillingRefundRequest,
		arg.AccountID,
		arg.RequestID,
		arg.AmountMinor,
		arg.Reason,
		arg.RequestedBy,
	)
	var i BillingRefundRequest
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.AmountMinor,
		&i.Reason,
		&i.Status,
		&i.RequestedBy,
		&i.DecidedBy,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const listBillingAccountsToSuspend = `-- name: ListBillingAccountsToSuspend :many
SELECT id FROM billing_accounts
WHERE status IN ('active', 'stopped') AND suspend_at <= $1::timestamptz
ORDER BY suspend_at
LIMIT $2
`

type ListBillingAccountsToSuspendParams struct {
	Now time.Time
	Lim int32
}

// Accounts whose debt deadline passed (still in debt is re-checked under the lock).
func (q *Queries) ListBillingAccountsToSuspend(ctx context.Context, arg ListBillingAccountsToSuspendParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBillingAccountsToSuspend, arg.Now, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingChargesActiveAt = `-- name: ListBillingChargesActiveAt :many
SELECT id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us FROM billing_charges
WHERE account_id = $1 AND starts_at <= $2::timestamptz AND ends_at > $2::timestamptz
ORDER BY ends_at, id
`

type ListBillingChargesActiveAtParams struct {
	AccountID uuid.UUID
	At        time.Time
}

// Seat lots covering `at` (capacity = sum(qty) of the current plan's SKU).
func (q *Queries) ListBillingChargesActiveAt(ctx context.Context, arg ListBillingChargesActiveAtParams) ([]BillingCharge, error) {
	rows, err := q.db.Query(ctx, listBillingChargesActiveAt, arg.AccountID, arg.At)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingCharge{}
	for rows.Next() {
		var i BillingCharge
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Sku,
			&i.Plan,
			&i.PriceID,
			&i.Qty,
			&i.UnitMinor,
			&i.DiscountBps,
			&i.StartsAt,
			&i.EndsAt,
			&i.AmountMinor,
			&i.UnfundedMinor,
			&i.CompensatedMinor,
			&i.Reason,
			&i.BusinessKey,
			&i.ActorID,
			&i.CreatedAt,
			&i.CanceledQty,
			&i.CanceledSeatUs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingChargesEndingBy = `-- name: ListBillingChargesEndingBy :many
SELECT id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us FROM billing_charges
WHERE account_id = $1 AND ends_at <= $2::timestamptz AND ends_at > $3::timestamptz
ORDER BY ends_at, id
`

type ListBillingChargesEndingByParams struct {
	AccountID uuid.UUID
	Due       time.Time
	Since     time.Time
}

// Seat lots that end at or before `due` and were not renewed yet are the renewal candidates;
// the core decides how many seats to renew from the current billable members.
func (q *Queries) ListBillingChargesEndingBy(ctx context.Context, arg ListBillingChargesEndingByParams) ([]BillingCharge, error) {
	rows, err := q.db.Query(ctx, listBillingChargesEndingBy, arg.AccountID, arg.Due, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingCharge{}
	for rows.Next() {
		var i BillingCharge
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Sku,
			&i.Plan,
			&i.PriceID,
			&i.Qty,
			&i.UnitMinor,
			&i.DiscountBps,
			&i.StartsAt,
			&i.EndsAt,
			&i.AmountMinor,
			&i.UnfundedMinor,
			&i.CompensatedMinor,
			&i.Reason,
			&i.BusinessKey,
			&i.ActorID,
			&i.CreatedAt,
			&i.CanceledQty,
			&i.CanceledSeatUs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingLedger = `-- name: ListBillingLedger :many
SELECT id, account_id, seq, kind, amount_minor, balance_after, business_key, lot_id, charge_id, refund_id, dispute_id, actor_id, reason, created_at FROM billing_ledger
WHERE account_id = $1
  AND ($2::bigint = 0 OR seq < $2::bigint)
ORDER BY seq DESC
LIMIT $3
`

type ListBillingLedgerParams struct {
	AccountID uuid.UUID
	BeforeSeq int64
	Lim       int32
}

// Newest first; before_seq = 0 starts at the newest entry.
func (q *Queries) ListBillingLedger(ctx context.Context, arg ListBillingLedgerParams) ([]BillingLedger, error) {
	rows, err := q.db.Query(ctx, listBillingLedger, arg.AccountID, arg.BeforeSeq, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingLedger{}
	for rows.Next() {
		var i BillingLedger
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Seq,
			&i.Kind,
			&i.AmountMinor,
			&i.BalanceAfter,
			&i.BusinessKey,
			&i.LotID,
			&i.ChargeID,
			&i.RefundID,
			&i.DisputeID,
			&i.ActorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingLedgerMismatches = `-- name: ListBillingLedgerMismatches :many
SELECT a.id, a.balance_minor, a.entry_seq,
    coalesce(l.total, 0)::bigint AS ledger_total, coalesce(l.last_seq, 0)::bigint AS ledger_seq
FROM billing_accounts a
LEFT JOIN (
    SELECT account_id, sum(amount_minor) AS total, max(seq) AS last_seq, count(*) AS n
    FROM billing_ledger GROUP BY account_id
) l ON l.account_id = a.id
WHERE a.balance_minor <> coalesce(l.total, 0) OR a.entry_seq <> coalesce(l.last_seq, 0)
   OR a.entry_seq <> coalesce(l.n, 0)
`

type ListBillingLedgerMismatchesRow struct {
	ID           uuid.UUID
	BalanceMinor int64
	EntrySeq     int64
	LedgerTotal  int64
	LedgerSeq    int64
}

// Nightly check: accounts whose balance cache or entry_seq disagrees with their ledger.
func (q *Queries) ListBillingLedgerMismatches(ctx context.Context) ([]ListBillingLedgerMismatchesRow, error) {
	rows, err := q.db.Query(ctx, listBillingLedgerMismatches)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBillingLedgerMismatchesRow{}
	for rows.Next() {
		var i ListBillingLedgerMismatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.BalanceMinor,
			&i.EntrySeq,
			&i.LedgerTotal,
			&i.LedgerSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingPayments = `-- name: ListBillingPayments :many
SELECT id, account_id, provider, provider_account, livemode, provider_payment_id, provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url, refunded_minor, succeeded_at, created_at, updated_at FROM billing_payments
WHERE account_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC
LIMIT $3
`

type ListBillingPaymentsParams struct {
	AccountID uuid.UUID
	BeforeID  *uuid.UUID
	Lim       int32
}

func (q *Queries) ListBillingPayments(ctx context.Context, arg ListBillingPaymentsParams) ([]BillingPayment, error) {
	rows, err := q.db.Query(ctx, listBillingPayments, arg.AccountID, arg.BeforeID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingPayment{}
	for rows.Next() {
		var i BillingPayment
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Provider,
			&i.ProviderAccount,
			&i.Livemode,
			&i.ProviderPaymentID,
			&i.ProviderChargeID,
			&i.AmountMinor,
			&i.Currency,
			&i.Status,
			&i.Origin,
			&i.CheckoutID,
			&i.AttemptID,
			&i.ReceiptUrl,
			&i.RefundedMinor,
			&i.SucceededAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBillingPrices = `-- name: ListBillingPrices :many
SELECT id, market, currency, sku, plan, unit_minor, effective_from, created_by, created_at FROM billing_prices ORDER BY market, sku, effective_from DESC
`

func (q *Queries) ListBillingPrices(ctx context.Context) ([]BillingPrice, error) {
	rows, err := q.db.Query(ctx, listBillingPrices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingPrice{}
	for rows.Next() {
		var i BillingPrice
		if err := rows.Scan(
			&i.ID,
			&i.Market,
			&i.Currency,
			&i.Sku,
			&i.Plan,
			&i.UnitMinor,
			&i.EffectiveFrom,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBillingAccount = `-- name: LockBillingAccount :one
SELECT id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at FROM billing_accounts WHERE id = $1 FOR UPDATE
`

// The single lock of every money mutation of the account (ADR-0080 §10).
func (q *Queries) LockBillingAccount(ctx context.Context, id uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, lockBillingAccount, id)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const lockLiveBillingAccountByWorkspace = `-- name: LockLiveBillingAccountByWorkspace :one
SELECT id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at FROM billing_accounts WHERE workspace_id = $1 AND status <> 'closed' FOR UPDATE
`

func (q *Queries) LockLiveBillingAccountByWorkspace(ctx context.Context, workspaceID *uuid.UUID) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, lockLiveBillingAccountByWorkspace, workspaceID)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const lockOpenBillingFundingLots = `-- name: LockOpenBillingFundingLots :many
SELECT id, account_id, source, payment_id, amount_minor, consumed_minor, refunded_minor, actor_id, reason, created_at FROM billing_funding_lots
WHERE account_id = $1 AND consumed_minor + refunded_minor < amount_minor
ORDER BY id
FOR UPDATE
`

// FIFO: lots with money left, oldest first (the account is locked already; FOR UPDATE keeps
// the lots consistent with it). Never SKIP LOCKED here: an older lot must not be skipped.
func (q *Queries) LockOpenBillingFundingLots(ctx context.Context, accountID uuid.UUID) ([]BillingFundingLot, error) {
	rows, err := q.db.Query(ctx, lockOpenBillingFundingLots, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingFundingLot{}
	for rows.Next() {
		var i BillingFundingLot
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Source,
			&i.PaymentID,
			&i.AmountMinor,
			&i.ConsumedMinor,
			&i.RefundedMinor,
			&i.ActorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUnfundedBillingCharges = `-- name: LockUnfundedBillingCharges :many
SELECT id, account_id, sku, plan, price_id, qty, unit_minor, discount_bps, starts_at, ends_at, amount_minor, unfunded_minor, compensated_minor, reason, business_key, actor_id, created_at, canceled_qty, canceled_seat_us FROM billing_charges
WHERE account_id = $1 AND unfunded_minor > 0
ORDER BY starts_at, id
FOR UPDATE
`

// Debt is paid first, oldest charge first.
func (q *Queries) LockUnfundedBillingCharges(ctx context.Context, accountID uuid.UUID) ([]BillingCharge, error) {
	rows, err := q.db.Query(ctx, lockUnfundedBillingCharges, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingCharge{}
	for rows.Next() {
		var i BillingCharge
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Sku,
			&i.Plan,
			&i.PriceID,
			&i.Qty,
			&i.UnitMinor,
			&i.DiscountBps,
			&i.StartsAt,
			&i.EndsAt,
			&i.AmountMinor,
			&i.UnfundedMinor,
			&i.CompensatedMinor,
			&i.Reason,
			&i.BusinessKey,
			&i.ActorID,
			&i.CreatedAt,
			&i.CanceledQty,
			&i.CanceledSeatUs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBillingPaymentSucceeded = `-- name: MarkBillingPaymentSucceeded :one
UPDATE billing_payments SET status = 'succeeded', amount_minor = $1,
    provider_charge_id = $2, receipt_url = $3,
    succeeded_at = $4::timestamptz, updated_at = $5::timestamptz
WHERE id = $6 AND status = 'processing'
RETURNING id, account_id, provider, provider_account, livemode, provider_payment_id, provider_charge_id, amount_minor, currency, status, origin, checkout_id, attempt_id, receipt_url, refunded_minor, succeeded_at, created_at, updated_at
`

type MarkBillingPaymentSucceededParams struct {
	AmountMinor      int64
	ProviderChargeID *string
	ReceiptUrl       string
	SucceededAt      time.Time
	Now              time.Time
	ID               uuid.UUID
}

// processing → succeeded (amount_received confirmed by a fresh provider read).
func (q *Queries) MarkBillingPaymentSucceeded(ctx context.Context, arg MarkBillingPaymentSucceededParams) (BillingPayment, error) {
	row := q.db.QueryRow(ctx, markBillingPaymentSucceeded,
		arg.AmountMinor,
		arg.ProviderChargeID,
		arg.ReceiptUrl,
		arg.SucceededAt,
		arg.Now,
		arg.ID,
	)
	var i BillingPayment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Provider,
		&i.ProviderAccount,
		&i.Livemode,
		&i.ProviderPaymentID,
		&i.ProviderChargeID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.Origin,
		&i.CheckoutID,
		&i.AttemptID,
		&i.ReceiptUrl,
		&i.RefundedMinor,
		&i.SucceededAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markBillingProviderEventProcessed = `-- name: MarkBillingProviderEventProcessed :exec
UPDATE billing_provider_events SET processed_at = $1::timestamptz, error = '' WHERE id = $2
`

type MarkBillingProviderEventProcessedParams struct {
	Now time.Time
	ID  uuid.UUID
}

func (q *Queries) MarkBillingProviderEventProcessed(ctx context.Context, arg MarkBillingProviderEventProcessedParams) error {
	_, err := q.db.Exec(ctx, markBillingProviderEventProcessed, arg.Now, arg.ID)
	return err
}

const markBillingProviderEventRetry = `-- name: MarkBillingProviderEventRetry :exec
UPDATE billing_provider_events SET next_attempt_at = $1::timestamptz, error = $2
WHERE id = $3
`

type MarkBillingProviderEventRetryParams struct {
	NextAttemptAt time.Time
	Error         string
	ID            uuid.UUID
}

func (q *Queries) MarkBillingProviderEventRetry(ctx context.Context, arg MarkBillingProviderEventRetryParams) error {
	_, err := q.db.Exec(ctx, markBillingProviderEventRetry, arg.NextAttemptAt, arg.Error, arg.ID)
	return err
}

const refundBillingFundingLot = `-- name: RefundBillingFundingLot :one
UPDATE billing_funding_lots SET refunded_minor = refunded_minor + $1::bigint
WHERE id = $2
RETURNING id, account_id, source, payment_id, amount_minor, consumed_minor, refunded_minor, actor_id, reason, created_at
`

type RefundBillingFundingLotParams struct {
	Delta int64
	ID    uuid.UUID
}

func (q *Queries) RefundBillingFundingLot(ctx context.Context, arg RefundBillingFundingLotParams) (BillingFundingLot, error) {
	row := q.db.QueryRow(ctx, refundBillingFundingLot, arg.Delta, arg.ID)
	var i BillingFundingLot
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Source,
		&i.PaymentID,
		&i.AmountMinor,
		&i.ConsumedMinor,
		&i.RefundedMinor,
		&i.ActorID,
		&i.Reason,
		&i.CreatedAt,
	)
	return i, err
}

const setBillingAutoTopupAttemptStatus = `-- name: SetBillingAutoTopupAttemptStatus :one
UPDATE billing_autotopup_attempts SET status = $1,
    provider_payment_id = coalesce($2, provider_payment_id),
    failure_code = $3,
    dispatched_at = CASE WHEN $1::text = 'dispatched' THEN $4::timestamptz ELSE dispatched_at END,
    finished_at = CASE WHEN $1::text IN ('succeeded', 'failed') THEN $4::timestamptz ELSE NULL END
WHERE id = $5 AND status NOT IN ('succeeded', 'failed')
RETURNING id, account_id, pm_id, amount_minor, currency, status, provider_payment_id, failure_code, created_at, dispatched_at, finished_at, kind, request_id, body_hash, created_by, action_url, order_snapshot
`

type SetBillingAutoTopupAttemptStatusParams struct {
	Status            string
	ProviderPaymentID *string
	FailureCode       string
	Now               time.Time
	ID                uuid.UUID
}

// prepared → dispatched → succeeded | failed | unknown | requires_action (one-click 3-D Secure);
// unknown / requires_action → succeeded | failed.
func (q *Queries) SetBillingAutoTopupAttemptStatus(ctx context.Context, arg SetBillingAutoTopupAttemptStatusParams) (BillingAutotopupAttempt, error) {
	row := q.db.QueryRow(ctx, setBillingAutoTopupAttemptStatus,
		arg.Status,
		arg.ProviderPaymentID,
		arg.FailureCode,
		arg.Now,
		arg.ID,
	)
	var i BillingAutotopupAttempt
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PmID,
		&i.AmountMinor,
		&i.Currency,
		&i.Status,
		&i.ProviderPaymentID,
		&i.FailureCode,
		&i.CreatedAt,
		&i.DispatchedAt,
		&i.FinishedAt,
		&i.Kind,
		&i.RequestID,
		&i.BodyHash,
		&i.CreatedBy,
		&i.ActionUrl,
		&i.OrderSnapshot,
	)
	return i, err
}

const setBillingCheckoutSession = `-- name: SetBillingCheckoutSession :one
UPDATE billing_checkouts SET provider_session_id = $1, url = $2,
    expires_at = $3, updated_at = $4::timestamptz
WHERE id = $5 AND status = 'open' AND (provider_session_id IS NULL OR provider_session_id = $1)
RETURNING id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls
`

type SetBillingCheckoutSessionParams struct {
	SessionID *string
	Url       *string
	ExpiresAt *time.Time
	Now       time.Time
	ID        uuid.UUID
}

// After the provider created the session (outside the transaction that inserted the row).
func (q *Queries) SetBillingCheckoutSession(ctx context.Context, arg SetBillingCheckoutSessionParams) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, setBillingCheckoutSession,
		arg.SessionID,
		arg.Url,
		arg.ExpiresAt,
		arg.Now,
		arg.ID,
	)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const setBillingCheckoutStatus = `-- name: SetBillingCheckoutStatus :one
UPDATE billing_checkouts SET status = $1, updated_at = $2::timestamptz
WHERE id = $3 AND status = 'open'
RETURNING id, account_id, request_id, body_hash, purpose, method_id, provider, amount_minor, currency, save_method, status, provider_session_id, url, payer_snapshot, created_by, expires_at, created_at, updated_at, next_poll_at, polls
`

type SetBillingCheckoutStatusParams struct {
	Status string
	Now    time.Time
	ID     uuid.UUID
}

// Leaves 'open' only: completed / expired / canceled / failed are final.
func (q *Queries) SetBillingCheckoutStatus(ctx context.Context, arg SetBillingCheckoutStatusParams) (BillingCheckout, error) {
	row := q.db.QueryRow(ctx, setBillingCheckoutStatus, arg.Status, arg.Now, arg.ID)
	var i BillingCheckout
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RequestID,
		&i.BodyHash,
		&i.Purpose,
		&i.MethodID,
		&i.Provider,
		&i.AmountMinor,
		&i.Currency,
		&i.SaveMethod,
		&i.Status,
		&i.ProviderSessionID,
		&i.Url,
		&i.PayerSnapshot,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.NextPollAt,
		&i.Polls,
	)
	return i, err
}

const switchBillingAccountMarket = `-- name: SwitchBillingAccountMarket :one
UPDATE billing_accounts
SET market = $1, currency = $2, provider = $3,
    revision = revision + 1, updated_at = $4
WHERE id = $5 AND status IN ('inactive', 'stopped') AND entry_seq = 0
RETURNING id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at
`

type SwitchBillingAccountMarketParams struct {
	Market   string
	Currency string
	Provider string
	Now      time.Time
	ID       uuid.UUID
}

// Moves an account without money history to another market (BillingAccountMarketFixed false,
// checked under the same lock).
func (q *Queries) SwitchBillingAccountMarket(ctx context.Context, arg SwitchBillingAccountMarketParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, switchBillingAccountMarket,
		arg.Market,
		arg.Currency,
		arg.Provider,
		arg.Now,
		arg.ID,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const updateBillingAccountState = `-- name: UpdateBillingAccountState :one
UPDATE billing_accounts SET
    status = $1, plan = $2,
    negative_since = $3, suspend_at = $4,
    next_due_at = $5,
    closed_at = CASE WHEN $1::text = 'closed' THEN coalesce(closed_at, $6::timestamptz) ELSE NULL END,
    revision = revision + 1, updated_at = $6::timestamptz
WHERE id = $7
RETURNING id, workspace_id, market, currency, provider, plan, status, balance_minor, entry_seq, negative_since, suspend_at, next_due_at, hold_until, dispute_hold, discount_bps, revision, created_by, created_at, updated_at, closed_at
`

type UpdateBillingAccountStateParams struct {
	Status        string
	Plan          string
	NegativeSince *time.Time
	SuspendAt     *time.Time
	NextDueAt     *time.Time
	Now           time.Time
	ID            uuid.UUID
}

// Status, debt episode, schedule and plan after a core operation (the row is locked). Bumps
// the revision; balance_minor / entry_seq change only through AppendBillingLedgerEntry.
func (q *Queries) UpdateBillingAccountState(ctx context.Context, arg UpdateBillingAccountStateParams) (BillingAccount, error) {
	row := q.db.QueryRow(ctx, updateBillingAccountState,
		arg.Status,
		arg.Plan,
		arg.NegativeSince,
		arg.SuspendAt,
		arg.NextDueAt,
		arg.Now,
		arg.ID,
	)
	var i BillingAccount
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Market,
		&i.Currency,
		&i.Provider,
		&i.Plan,
		&i.Status,
		&i.BalanceMinor,
		&i.EntrySeq,
		&i.NegativeSince,
		&i.SuspendAt,
		&i.NextDueAt,
		&i.HoldUntil,
		&i.DisputeHold,
		&i.DiscountBps,
		&i.Revision,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const upsertBillingPayer = `-- name: UpsertBillingPayer :one
INSERT INTO billing_payers (account_id, type, name, country, email, tax_id, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8::timestamptz)
ON CONFLICT (account_id) DO UPDATE SET
    type = EXCLUDED.type, name = EXCLUDED.name, country = EXCLUDED.country, email = EXCLUDED.email,
    tax_id = EXCLUDED.tax_id, updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
RETURNING account_id, type, name, country, email, tax_id, updated_by, updated_at
`

type UpsertBillingPayerParams struct {
	AccountID uuid.UUID
	Type      string
	Name      string
	Country   string
	Email     string
	TaxID     *string
	UpdatedBy *uuid.UUID
	Now       time.Time
}

func (q *Queries) UpsertBillingPayer(ctx context.Context, arg UpsertBillingPayerParams) (BillingPayer, error) {
	row := q.db.QueryRow(ctx, upsertBillingPayer,
		arg.AccountID,
		arg.Type,
		arg.Name,
		arg.Country,
		arg.Email,
		arg.TaxID,
		arg.UpdatedBy,
		arg.Now,
	)
	var i BillingPayer
	err := row.Scan(
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.Country,
		&i.Email,
		&i.TaxID,
		&i.UpdatedBy,
		&i.UpdatedAt,
	)
	return i, err
}
