// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_payer.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const insertBillingPayerVersion = `-- name: InsertBillingPayerVersion :exec
INSERT INTO billing_payer_versions (account_id, version, type, name, country, email, tax_id, requisites, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::timestamptz)
`

type InsertBillingPayerVersionParams struct {
	AccountID  uuid.UUID
	Version    int32
	Type       string
	Name       string
	Country    string
	Email      string
	TaxID      *string
	Requisites []byte
	CreatedBy  *uuid.UUID
	Now        time.Time
}

func (q *Queries) InsertBillingPayerVersion(ctx context.Context, arg InsertBillingPayerVersionParams) error {
	_, err := q.db.Exec(ctx, insertBillingPayerVersion,
		arg.AccountID,
		arg.Version,
		arg.Type,
		arg.Name,
		arg.Country,
		arg.Email,
		arg.TaxID,
		arg.Requisites,
		arg.CreatedBy,
		arg.Now,
	)
	return err
}

const listBillingPayerVersions = `-- name: ListBillingPayerVersions :many
SELECT account_id, version, type, name, country, email, tax_id, requisites, created_by, created_at FROM billing_payer_versions WHERE account_id = $1 ORDER BY version
`

func (q *Queries) ListBillingPayerVersions(ctx context.Context, accountID uuid.UUID) ([]BillingPayerVersion, error) {
	rows, err := q.db.Query(ctx, listBillingPayerVersions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BillingPayerVersion{}
	for rows.Next() {
		var i BillingPayerVersion
		if err := rows.Scan(
			&i.AccountID,
			&i.Version,
			&i.Type,
			&i.Name,
			&i.Country,
			&i.Email,
			&i.TaxID,
			&i.Requisites,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveBillingPayer = `-- name: SaveBillingPayer :one

INSERT INTO billing_payers (account_id, type, name, country, email, tax_id, requisites, version, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10::timestamptz)
ON CONFLICT (account_id) DO UPDATE SET
    type = EXCLUDED.type, name = EXCLUDED.name, country = EXCLUDED.country, email = EXCLUDED.email,
    tax_id = EXCLUDED.tax_id, requisites = EXCLUDED.requisites, version = EXCLUDED.version,
    updated_by = EXCLUDED.updated_by, updated_at = EXCLUDED.updated_at
RETURNING account_id, type, name, country, email, tax_id, updated_by, updated_at, requisites, version
`

type SaveBillingPayerParams struct {
	AccountID  uuid.UUID
	Type       string
	Name       string
	Country    string
	Email      string
	TaxID      *string
	Requisites []byte
	Version    int32
	UpdatedBy  *uuid.UUID
	Now        time.Time
}

// Payer requisites and versions (ADR-0080 §0.1, migration 00079).
// The caller holds the account lock (LockBillingAccount), passes the next version and inserts
// the same values into billing_payer_versions in the same transaction.
func (q *Queries) SaveBillingPayer(ctx context.Context, arg SaveBillingPayerParams) (BillingPayer, error) {
	row := q.db.QueryRow(ctx, saveBillingPayer,
		arg.AccountID,
		arg.Type,
		arg.Name,
		arg.Country,
		arg.Email,
		arg.TaxID,
		arg.Requisites,
		arg.Version,
		arg.UpdatedBy,
		arg.Now,
	)
	var i BillingPayer
	err := row.Scan(
		&i.AccountID,
		&i.Type,
		&i.Name,
		&i.Country,
		&i.Email,
		&i.TaxID,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Requisites,
		&i.Version,
	)
	return i, err
}
