// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: billing_admission.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getWorkspaceBillingStatus = `-- name: GetWorkspaceBillingStatus :one
SELECT
    COALESCE((SELECT wp.source FROM workspace_plans wp WHERE wp.workspace_id = w.id), 'manual')::text AS source,
    COALESCE(a.status, '')::text AS account_status,
    a.negative_since, a.suspend_at
FROM workspaces w
LEFT JOIN billing_accounts a ON a.workspace_id = w.id AND a.status <> 'closed'
WHERE w.id = $1
`

type GetWorkspaceBillingStatusRow struct {
	Source        string
	AccountStatus string
	NegativeSince *time.Time
	SuspendAt     *time.Time
}

// Workspace.billing (WorkspaceBillingStatus, no amounts): the plan source and the live
// account's state; account_status is empty without a live account.
func (q *Queries) GetWorkspaceBillingStatus(ctx context.Context, id uuid.UUID) (GetWorkspaceBillingStatusRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBillingStatus, id)
	var i GetWorkspaceBillingStatusRow
	err := row.Scan(
		&i.Source,
		&i.AccountStatus,
		&i.NegativeSince,
		&i.SuspendAt,
	)
	return i, err
}

const workspaceBillingSuspended = `-- name: WorkspaceBillingSuspended :one

SELECT EXISTS (
    SELECT 1 FROM billing_accounts
    WHERE workspace_id = $1 AND status = 'suspended'
)::boolean
`

// Balance billing v1 (ADR-0080 v5): admission and enforcement (T3). Owned by the admission
// side (workspaces, auth, guests, identitypolicy, plans); money queries live in billing*.sql.
// The seat count is CountBillableMembers (billing.sql).
// Whether the live billing account of a workspace is suspended for debt (false without one).
// Enforced only with BILLING_ENFORCEMENT_ENABLED; independent of the moderation suspension
// (workspaces.suspended_at).
func (q *Queries) WorkspaceBillingSuspended(ctx context.Context, workspaceID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceBillingSuspended, workspaceID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
