// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: birthdays.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimBirthdayGreeting = `-- name: ClaimBirthdayGreeting :execrows
INSERT INTO birthday_greetings (user_id, workspace_id, day) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimBirthdayGreetingParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Day         pgtype.Date
}

// One card per (user, workspace, the user's local date): 0 rows = already posted.
func (q *Queries) ClaimBirthdayGreeting(ctx context.Context, arg ClaimBirthdayGreetingParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimBirthdayGreeting, arg.UserID, arg.WorkspaceID, arg.Day)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldBirthdayGreetings = `-- name: DeleteOldBirthdayGreetings :execrows
DELETE FROM birthday_greetings WHERE day < $1::date
`

// The dedup only needs the last few days.
func (q *Queries) DeleteOldBirthdayGreetings(ctx context.Context, before pgtype.Date) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldBirthdayGreetings, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBirthdayCandidates = `-- name: ListBirthdayCandidates :many
SELECT id, timezone, birthday_day, birthday_month FROM users
WHERE birthday_day IS NOT NULL AND NOT birthday_hidden AND NOT is_guest AND NOT is_bot AND disabled_at IS NULL
  AND (birthday_month * 100 + birthday_day) = ANY($1::integer[])
`

type ListBirthdayCandidatesRow struct {
	ID            uuid.UUID
	Timezone      *string
	BirthdayDay   *int16
	BirthdayMonth *int16
}

// People whose month * 100 + day is one of the given dates (the worker passes the dates that
// are "today" somewhere on Earth); hidden birthdays, guests, bots and disabled accounts are out.
func (q *Queries) ListBirthdayCandidates(ctx context.Context, dates []int32) ([]ListBirthdayCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listBirthdayCandidates, dates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBirthdayCandidatesRow{}
	for rows.Next() {
		var i ListBirthdayCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Timezone,
			&i.BirthdayDay,
			&i.BirthdayMonth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBirthdayRooms = `-- name: ListBirthdayRooms :many
SELECT m.workspace_id, fr.id::uuid AS room_id, ow.timezone AS owner_timezone
FROM workspace_members m
JOIN workspaces w ON w.id = m.workspace_id AND w.suspended_at IS NULL
JOIN users ow ON ow.id = w.owner_id
JOIN LATERAL (SELECT announcement_room(m.workspace_id) AS id) fr ON fr.id IS NOT NULL
WHERE m.user_id = $1 AND m.role <> 'guest'
  AND EXISTS (
      SELECT 1 FROM workspace_members o JOIN users u ON u.id = o.user_id
      WHERE o.workspace_id = m.workspace_id AND o.user_id <> m.user_id AND NOT u.is_bot)
`

type ListBirthdayRoomsRow struct {
	WorkspaceID   uuid.UUID
	RoomID        uuid.UUID
	OwnerTimezone *string
}

// Where a user's birthday card goes: every workspace they are a non-guest member of that is
// not suspended and has someone else (not a bot) in it, with its first text room in sidebar
// order (top level first, then categories by position); a room everyone can see (not private)
// is preferred — announcement_room() (migration 00061), shared with achievement cards.
// Workspaces without a text room are skipped. owner_timezone: the workspace owner's zone, the
// fallback of the greeting time when the user has none (birthdays.GreetZone).
func (q *Queries) ListBirthdayRooms(ctx context.Context, userID uuid.UUID) ([]ListBirthdayRoomsRow, error) {
	rows, err := q.db.Query(ctx, listBirthdayRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBirthdayRoomsRow{}
	for rows.Next() {
		var i ListBirthdayRoomsRow
		if err := rows.Scan(&i.WorkspaceID, &i.RoomID, &i.OwnerTimezone); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberBirthdays = `-- name: ListMemberBirthdays :many
SELECT u.id, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden
FROM workspace_members m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND u.birthday_day IS NOT NULL AND NOT u.is_bot AND m.role <> 'guest'
`

type ListMemberBirthdaysRow struct {
	ID             uuid.UUID
	BirthdayDay    *int16
	BirthdayMonth  *int16
	BirthdayYear   *int16
	BirthdayHidden bool
}

// Every member's birthday, hidden ones included, for the admin table (docs/09 #77): bots and
// guests are left out.
func (q *Queries) ListMemberBirthdays(ctx context.Context, workspaceID uuid.UUID) ([]ListMemberBirthdaysRow, error) {
	rows, err := q.db.Query(ctx, listMemberBirthdays, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberBirthdaysRow{}
	for rows.Next() {
		var i ListMemberBirthdaysRow
		if err := rows.Scan(
			&i.ID,
			&i.BirthdayDay,
			&i.BirthdayMonth,
			&i.BirthdayYear,
			&i.BirthdayHidden,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceBirthdays = `-- name: ListWorkspaceBirthdays :many
SELECT u.id, u.birthday_day, u.birthday_month, u.birthday_year
FROM workspace_members m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND u.birthday_day IS NOT NULL AND NOT u.birthday_hidden AND NOT u.is_bot
`

type ListWorkspaceBirthdaysRow struct {
	ID            uuid.UUID
	BirthdayDay   *int16
	BirthdayMonth *int16
	BirthdayYear  *int16
}

// Members of a workspace with a visible birthday (GET /api/workspaces/{id}/birthdays).
func (q *Queries) ListWorkspaceBirthdays(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceBirthdaysRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceBirthdays, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceBirthdaysRow{}
	for rows.Next() {
		var i ListWorkspaceBirthdaysRow
		if err := rows.Scan(
			&i.ID,
			&i.BirthdayDay,
			&i.BirthdayMonth,
			&i.BirthdayYear,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBirthdayGreetingMessage = `-- name: SetBirthdayGreetingMessage :exec
UPDATE birthday_greetings SET message_id = $4 WHERE user_id = $1 AND workspace_id = $2 AND day = $3
`

type SetBirthdayGreetingMessageParams struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Day         pgtype.Date
	MessageID   *uuid.UUID
}

func (q *Queries) SetBirthdayGreetingMessage(ctx context.Context, arg SetBirthdayGreetingMessageParams) error {
	_, err := q.db.Exec(ctx, setBirthdayGreetingMessage,
		arg.UserID,
		arg.WorkspaceID,
		arg.Day,
		arg.MessageID,
	)
	return err
}
