// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: boards.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addTaskWatchers = `-- name: AddTaskWatchers :exec
INSERT INTO task_subscribers (task_id, user_id, watcher) SELECT $1, unnest($2::uuid[]), true
ON CONFLICT (task_id, user_id) DO UPDATE SET watcher = true
`

type AddTaskWatchersParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

// Makes users watchers (and subscribers) of a task; an existing row keeps its muted flag.
func (q *Queries) AddTaskWatchers(ctx context.Context, arg AddTaskWatchersParams) error {
	_, err := q.db.Exec(ctx, addTaskWatchers, arg.TaskID, arg.UserIds)
	return err
}

const archiveTasks = `-- name: ArchiveTasks :many
UPDATE tasks SET archived_at = now(), updated_at = now()
WHERE id = ANY($1::uuid[]) AND archived_at IS NULL
RETURNING id, board_id
`

type ArchiveTasksRow struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) ArchiveTasks(ctx context.Context, ids []uuid.UUID) ([]ArchiveTasksRow, error) {
	rows, err := q.db.Query(ctx, archiveTasks, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ArchiveTasksRow{}
	for rows.Next() {
		var i ArchiveTasksRow
		if err := rows.Scan(&i.ID, &i.BoardID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardApprovalNotifyDelay = `-- name: BoardApprovalNotifyDelay :one
SELECT approval_notify_delay_seconds FROM boards WHERE id = $1
`

func (q *Queries) BoardApprovalNotifyDelay(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, boardApprovalNotifyDelay, id)
	var approval_notify_delay_seconds int32
	err := row.Scan(&approval_notify_delay_seconds)
	return approval_notify_delay_seconds, err
}

const boardHasTasks = `-- name: BoardHasTasks :one
SELECT (next_number > 1)::boolean FROM boards WHERE id = $1
`

func (q *Queries) BoardHasTasks(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, boardHasTasks, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const boardKeyTaken = `-- name: BoardKeyTaken :one
SELECT EXISTS (SELECT 1 FROM boards WHERE workspace_id = $1 AND key = $2)::boolean
`

type BoardKeyTakenParams struct {
	WorkspaceID uuid.UUID
	Key         string
}

func (q *Queries) BoardKeyTaken(ctx context.Context, arg BoardKeyTakenParams) (bool, error) {
	row := q.db.QueryRow(ctx, boardKeyTaken, arg.WorkspaceID, arg.Key)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const boardOpenCounts = `-- name: BoardOpenCounts :many
SELECT t.board_id, count(*)::integer AS open,
    (count(*) FILTER (WHERE EXISTS (SELECT 1 FROM task_assignees a WHERE a.task_id = t.id AND a.user_id = $1::uuid)))::integer AS mine
FROM tasks t JOIN board_statuses st ON st.id = t.status_id
WHERE t.board_id = ANY($2::uuid[]) AND t.archived_at IS NULL AND st.type NOT IN ('completed', 'cancelled')
GROUP BY t.board_id
`

type BoardOpenCountsParams struct {
	UserID   uuid.UUID
	BoardIds []uuid.UUID
}

type BoardOpenCountsRow struct {
	BoardID uuid.UUID
	Open    int32
	Mine    int32
}

// Live tasks not in a finished status per board, and of them assigned to the user.
func (q *Queries) BoardOpenCounts(ctx context.Context, arg BoardOpenCountsParams) ([]BoardOpenCountsRow, error) {
	rows, err := q.db.Query(ctx, boardOpenCounts, arg.UserID, arg.BoardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardOpenCountsRow{}
	for rows.Next() {
		var i BoardOpenCountsRow
		if err := rows.Scan(&i.BoardID, &i.Open, &i.Mine); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const boardTaskRoomIDs = `-- name: BoardTaskRoomIDs :many
SELECT room_id FROM tasks WHERE board_id = $1
`

func (q *Queries) BoardTaskRoomIDs(ctx context.Context, boardID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, boardTaskRoomIDs, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var room_id uuid.UUID
		if err := rows.Scan(&room_id); err != nil {
			return nil, err
		}
		items = append(items, room_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimApprovalNotices = `-- name: ClaimApprovalNotices :many
WITH due AS (
    SELECT a.task_id, a.user_id FROM task_approvers a
    WHERE a.task_id = $1 AND a.notify_due_at IS NOT NULL AND a.notify_due_at <= now()
    FOR UPDATE SKIP LOCKED
)
UPDATE task_approvers a SET notify_due_at = NULL,
    requested_at = CASE WHEN a.state = 'pending' THEN now() ELSE a.requested_at END,
    reminders = CASE WHEN a.state = 'pending' THEN 0 ELSE a.reminders END,
    reminded_at = CASE WHEN a.state = 'pending' THEN NULL ELSE a.reminded_at END
FROM due WHERE a.task_id = due.task_id AND a.user_id = due.user_id
RETURNING a.user_id, a.state, a.notify_reason, a.added_by
`

type ClaimApprovalNoticesRow struct {
	UserID       uuid.UUID
	State        string
	NotifyReason string
	AddedBy      *uuid.UUID
}

// Claims the due approval notices of one task: clears notify_due_at under the row locks
// (SKIP LOCKED: another server instance's pass takes them, never both). A vote still pending
// is asked for from now on: the daily reminders count from the notice (ADR-0082). The caller
// sends only to pending votes.
func (q *Queries) ClaimApprovalNotices(ctx context.Context, taskID uuid.UUID) ([]ClaimApprovalNoticesRow, error) {
	rows, err := q.db.Query(ctx, claimApprovalNotices, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClaimApprovalNoticesRow{}
	for rows.Next() {
		var i ClaimApprovalNoticesRow
		if err := rows.Scan(
			&i.UserID,
			&i.State,
			&i.NotifyReason,
			&i.AddedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimApprovalReminders = `-- name: ClaimApprovalReminders :many
UPDATE task_approvers a SET reminders = a.reminders + 1, reminded_at = now()
FROM tasks t JOIN board_statuses st ON st.id = t.status_id JOIN boards b ON b.id = t.board_id
WHERE a.task_id = $1 AND a.user_id = ANY($2::uuid[])
  AND t.id = a.task_id AND t.archived_at IS NULL AND st.type NOT IN ('completed', 'cancelled')
  AND b.disabled_features & 512 = 0
  AND a.state = 'pending' AND a.reminders < 3 AND a.notify_due_at IS NULL
  AND coalesce(a.reminded_at, a.requested_at) <= now() - interval '24 hours'
  AND NOT EXISTS (SELECT 1 FROM task_approvers r WHERE r.task_id = a.task_id AND r.state = 'rejected')
RETURNING a.user_id
`

type ClaimApprovalRemindersParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

// Claims the reminders of one task: re-checks DueApprovalReminders' conditions under the row
// locks, so a vote cast since, or another server instance's pass, never gets a second notice.
func (q *Queries) ClaimApprovalReminders(ctx context.Context, arg ClaimApprovalRemindersParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, claimApprovalReminders, arg.TaskID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearDefaultBoardStatus = `-- name: ClearDefaultBoardStatus :exec
UPDATE board_statuses SET is_default = false WHERE board_id = $1 AND is_default
`

func (q *Queries) ClearDefaultBoardStatus(ctx context.Context, boardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearDefaultBoardStatus, boardID)
	return err
}

const countAllBoards = `-- name: CountAllBoards :one
SELECT count(*)::integer FROM boards WHERE workspace_id = $1
`

// Live and archived: the hard cap of 50 (ADR-0042 §6).
func (q *Queries) CountAllBoards(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAllBoards, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBoardViews = `-- name: CountBoardViews :one
SELECT count(*)::integer FROM board_views WHERE board_id = $1
`

func (q *Queries) CountBoardViews(ctx context.Context, boardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBoardViews, boardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBoards = `-- name: CountBoards :one
SELECT count(*)::integer FROM boards WHERE workspace_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountBoards(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBoards, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveSubtasks = `-- name: CountLiveSubtasks :one
SELECT count(*)::integer FROM tasks WHERE parent_id = $1 AND archived_at IS NULL
`

func (q *Queries) CountLiveSubtasks(ctx context.Context, parentID *uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveSubtasks, parentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLiveTasks = `-- name: CountLiveTasks :one

SELECT count(*)::integer FROM tasks WHERE board_id = $1 AND archived_at IS NULL
`

// ---- tasks ----
func (q *Queries) CountLiveTasks(ctx context.Context, boardID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countLiveTasks, boardID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBoard = `-- name: CreateBoard :one
INSERT INTO boards (workspace_id, name, key, emoji, icon_file_id, description, is_private, position, created_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7,
        (SELECT coalesce(max(position) + 1, 0) FROM boards WHERE workspace_id = $1),
        $8)
RETURNING id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds
`

type CreateBoardParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Key         string
	Emoji       string
	IconFileID  *uuid.UUID
	Description string
	IsPrivate   bool
	CreatedBy   *uuid.UUID
}

func (q *Queries) CreateBoard(ctx context.Context, arg CreateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, createBoard,
		arg.WorkspaceID,
		arg.Name,
		arg.Key,
		arg.Emoji,
		arg.IconFileID,
		arg.Description,
		arg.IsPrivate,
		arg.CreatedBy,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const createBoardLabel = `-- name: CreateBoardLabel :one
INSERT INTO board_labels (board_id, name, color, position) VALUES ($1, $2, $3, $4) RETURNING id, board_id, name, color, position
`

type CreateBoardLabelParams struct {
	BoardID  uuid.UUID
	Name     string
	Color    int32
	Position int32
}

func (q *Queries) CreateBoardLabel(ctx context.Context, arg CreateBoardLabelParams) (BoardLabel, error) {
	row := q.db.QueryRow(ctx, createBoardLabel,
		arg.BoardID,
		arg.Name,
		arg.Color,
		arg.Position,
	)
	var i BoardLabel
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const createBoardMilestone = `-- name: CreateBoardMilestone :one
INSERT INTO board_milestones (board_id, name, due_on, position) VALUES ($1, $2, $3, $4) RETURNING id, board_id, name, due_on, position
`

type CreateBoardMilestoneParams struct {
	BoardID  uuid.UUID
	Name     string
	DueOn    pgtype.Date
	Position int32
}

func (q *Queries) CreateBoardMilestone(ctx context.Context, arg CreateBoardMilestoneParams) (BoardMilestone, error) {
	row := q.db.QueryRow(ctx, createBoardMilestone,
		arg.BoardID,
		arg.Name,
		arg.DueOn,
		arg.Position,
	)
	var i BoardMilestone
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.DueOn,
		&i.Position,
	)
	return i, err
}

const createBoardStatus = `-- name: CreateBoardStatus :one
INSERT INTO board_statuses (board_id, name, type, color, position, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, board_id, name, type, color, position, is_default
`

type CreateBoardStatusParams struct {
	BoardID   uuid.UUID
	Name      string
	Type      string
	Color     int32
	Position  int32
	IsDefault bool
}

func (q *Queries) CreateBoardStatus(ctx context.Context, arg CreateBoardStatusParams) (BoardStatus, error) {
	row := q.db.QueryRow(ctx, createBoardStatus,
		arg.BoardID,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.Position,
		arg.IsDefault,
	)
	var i BoardStatus
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Position,
		&i.IsDefault,
	)
	return i, err
}

const createBoardView = `-- name: CreateBoardView :one
INSERT INTO board_views (board_id, name, kind, filter, group_by, sort, shared, created_by, position)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8,
        coalesce($9::integer, (SELECT coalesce(max(position) + 1, 0) FROM board_views WHERE board_id = $1)))
RETURNING id, board_id, name, kind, filter, group_by, sort, shared, created_by, position, created_at
`

type CreateBoardViewParams struct {
	BoardID   uuid.UUID
	Name      string
	Kind      string
	Filter    []byte
	GroupBy   string
	Sort      string
	Shared    bool
	CreatedBy uuid.UUID
	Position  *int32
}

func (q *Queries) CreateBoardView(ctx context.Context, arg CreateBoardViewParams) (BoardView, error) {
	row := q.db.QueryRow(ctx, createBoardView,
		arg.BoardID,
		arg.Name,
		arg.Kind,
		arg.Filter,
		arg.GroupBy,
		arg.Sort,
		arg.Shared,
		arg.CreatedBy,
		arg.Position,
	)
	var i BoardView
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Kind,
		&i.Filter,
		&i.GroupBy,
		&i.Sort,
		&i.Shared,
		&i.CreatedBy,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const createTaskRoom = `-- name: CreateTaskRoom :one
INSERT INTO rooms (workspace_id, type, name, position) VALUES ($1, 'task', $2, 0) RETURNING id
`

type CreateTaskRoomParams struct {
	WorkspaceID *uuid.UUID
	Name        string
}

func (q *Queries) CreateTaskRoom(ctx context.Context, arg CreateTaskRoomParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTaskRoom, arg.WorkspaceID, arg.Name)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteBoard = `-- name: DeleteBoard :execrows
DELETE FROM boards WHERE id = $1
`

func (q *Queries) DeleteBoard(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoard, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardLabel = `-- name: DeleteBoardLabel :execrows
DELETE FROM board_labels WHERE id = $1 AND board_id = $2
`

type DeleteBoardLabelParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) DeleteBoardLabel(ctx context.Context, arg DeleteBoardLabelParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardLabel, arg.ID, arg.BoardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardMilestone = `-- name: DeleteBoardMilestone :execrows
DELETE FROM board_milestones WHERE id = $1 AND board_id = $2
`

type DeleteBoardMilestoneParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) DeleteBoardMilestone(ctx context.Context, arg DeleteBoardMilestoneParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardMilestone, arg.ID, arg.BoardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardOverride = `-- name: DeleteBoardOverride :exec
DELETE FROM board_permissions WHERE board_id = $1 AND target_type = $2 AND target_id = $3
`

type DeleteBoardOverrideParams struct {
	BoardID    uuid.UUID
	TargetType string
	TargetID   string
}

func (q *Queries) DeleteBoardOverride(ctx context.Context, arg DeleteBoardOverrideParams) error {
	_, err := q.db.Exec(ctx, deleteBoardOverride, arg.BoardID, arg.TargetType, arg.TargetID)
	return err
}

const deleteBoardOverrides = `-- name: DeleteBoardOverrides :exec
DELETE FROM board_permissions WHERE board_id = $1
`

func (q *Queries) DeleteBoardOverrides(ctx context.Context, boardID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardOverrides, boardID)
	return err
}

const deleteBoardStatus = `-- name: DeleteBoardStatus :execrows
DELETE FROM board_statuses WHERE id = $1 AND board_id = $2
`

type DeleteBoardStatusParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) DeleteBoardStatus(ctx context.Context, arg DeleteBoardStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardStatus, arg.ID, arg.BoardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBoardTaskRooms = `-- name: DeleteBoardTaskRooms :exec
DELETE FROM rooms WHERE id = ANY($1::uuid[]) AND type = 'task'
`

// Purge: the comment rooms of the board's tasks (their messages cascade). Called after the
// board (and so its tasks) is deleted, with the room ids read before.
func (q *Queries) DeleteBoardTaskRooms(ctx context.Context, ids []uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBoardTaskRooms, ids)
	return err
}

const deleteBoardView = `-- name: DeleteBoardView :execrows
DELETE FROM board_views WHERE id = $1 AND board_id = $2
`

type DeleteBoardViewParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) DeleteBoardView(ctx context.Context, arg DeleteBoardViewParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBoardView, arg.ID, arg.BoardID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskApprovers = `-- name: DeleteTaskApprovers :exec
DELETE FROM task_approvers WHERE task_id = $1 AND user_id = ANY($2::uuid[])
`

type DeleteTaskApproversParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) DeleteTaskApprovers(ctx context.Context, arg DeleteTaskApproversParams) error {
	_, err := q.db.Exec(ctx, deleteTaskApprovers, arg.TaskID, arg.UserIds)
	return err
}

const deleteTaskAssignees = `-- name: DeleteTaskAssignees :exec
DELETE FROM task_assignees WHERE task_id = $1
`

func (q *Queries) DeleteTaskAssignees(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskAssignees, taskID)
	return err
}

const deleteTaskAttachments = `-- name: DeleteTaskAttachments :exec
DELETE FROM task_attachments WHERE task_id = $1
`

func (q *Queries) DeleteTaskAttachments(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskAttachments, taskID)
	return err
}

const deleteTaskLabels = `-- name: DeleteTaskLabels :exec
DELETE FROM task_labels WHERE task_id = $1
`

func (q *Queries) DeleteTaskLabels(ctx context.Context, taskID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTaskLabels, taskID)
	return err
}

const deleteTaskRelation = `-- name: DeleteTaskRelation :execrows
DELETE FROM task_relations
WHERE kind = $1 AND ((task_id = $2 AND related_id = $3)
    OR (kind <> 'blocks' AND task_id = $3 AND related_id = $2))
`

type DeleteTaskRelationParams struct {
	Kind string
	A    uuid.UUID
	B    uuid.UUID
}

// relates / duplicates read both ways: either direction is removed.
func (q *Queries) DeleteTaskRelation(ctx context.Context, arg DeleteTaskRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTaskRelation, arg.Kind, arg.A, arg.B)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTaskSubscription = `-- name: DeleteTaskSubscription :exec
DELETE FROM task_subscribers WHERE task_id = $1 AND user_id = $2
`

type DeleteTaskSubscriptionParams struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteTaskSubscription(ctx context.Context, arg DeleteTaskSubscriptionParams) error {
	_, err := q.db.Exec(ctx, deleteTaskSubscription, arg.TaskID, arg.UserID)
	return err
}

const detachSubtasks = `-- name: DetachSubtasks :exec
UPDATE tasks SET parent_id = NULL, task_milestone_id = NULL, updated_at = now() WHERE parent_id = $1
`

// The subtasks lose their parent and its milestone (ADR-0063).
func (q *Queries) DetachSubtasks(ctx context.Context, parentID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, detachSubtasks, parentID)
	return err
}

const dueApprovalNoticeTasks = `-- name: DueApprovalNoticeTasks :many
SELECT DISTINCT task_id FROM (
    SELECT task_id FROM task_approvers
    WHERE notify_due_at IS NOT NULL AND notify_due_at <= now()
    ORDER BY notify_due_at
    LIMIT $1
) d
`

// The tasks with an approval notice due (the partial index; cheap while none is due).
func (q *Queries) DueApprovalNoticeTasks(ctx context.Context, lim int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, dueApprovalNoticeTasks, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dueApprovalReminders = `-- name: DueApprovalReminders :many
SELECT a.task_id, a.user_id FROM task_approvers a
JOIN tasks t ON t.id = a.task_id AND t.archived_at IS NULL
JOIN boards b ON b.id = t.board_id AND b.archived_at IS NULL
    AND b.disabled_features & 512 = 0 -- BOARD_FEATURE_APPROVALS (9) off: no reminders (ADR-0058 §3)
JOIN board_statuses st ON st.id = t.status_id AND st.type NOT IN ('completed', 'cancelled')
WHERE a.state = 'pending' AND a.reminders < 3 AND a.notify_due_at IS NULL
  AND coalesce(a.reminded_at, a.requested_at) <= now() - interval '24 hours'
  AND NOT EXISTS (SELECT 1 FROM task_approvers r WHERE r.task_id = a.task_id AND r.state = 'rejected')
ORDER BY a.task_id, a.user_id
LIMIT $1
`

type DueApprovalRemindersRow struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

// Votes pending for 24 h since they were asked for or last reminded (≤ 3 reminders), on live
// tasks of live boards that are neither finished nor rejected.
func (q *Queries) DueApprovalReminders(ctx context.Context, lim int32) ([]DueApprovalRemindersRow, error) {
	rows, err := q.db.Query(ctx, dueApprovalReminders, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueApprovalRemindersRow{}
	for rows.Next() {
		var i DueApprovalRemindersRow
		if err := rows.Scan(&i.TaskID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dueAutoArchive = `-- name: DueAutoArchive :many

SELECT t.id, t.board_id, b.workspace_id FROM tasks t
JOIN boards b ON b.id = t.board_id AND b.archived_at IS NULL AND b.auto_archive_days > 0
JOIN board_statuses st ON st.id = t.status_id AND st.type IN ('completed', 'cancelled')
WHERE t.archived_at IS NULL AND t.completed_at IS NOT NULL
  AND t.completed_at < now() - make_interval(days => b.auto_archive_days)
ORDER BY t.completed_at
LIMIT $1
`

type DueAutoArchiveRow struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	WorkspaceID uuid.UUID
}

// ---- sweeper ----
// Live tasks finished longer ago than their board's auto_archive_days (0 = never), oldest first.
func (q *Queries) DueAutoArchive(ctx context.Context, lim int32) ([]DueAutoArchiveRow, error) {
	rows, err := q.db.Query(ctx, dueAutoArchive, lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueAutoArchiveRow{}
	for rows.Next() {
		var i DueAutoArchiveRow
		if err := rows.Scan(&i.ID, &i.BoardID, &i.WorkspaceID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const filesAttachable = `-- name: FilesAttachable :many
SELECT f.id FROM files f
WHERE f.id = ANY($1::uuid[]) AND f.uploader_id = $2 AND f.workspace_id = $3::uuid
  AND NOT EXISTS (SELECT 1 FROM message_attachments ma WHERE ma.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM task_attachments ta WHERE ta.file_id = f.id AND ta.task_id <> $4::uuid)
`

type FilesAttachableParams struct {
	Ids         []uuid.UUID
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	TaskID      uuid.UUID
}

// Uploads of the user in the workspace that are neither attached to a message nor to another
// task (task_id's own ones count as free).
func (q *Queries) FilesAttachable(ctx context.Context, arg FilesAttachableParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, filesAttachable,
		arg.Ids,
		arg.UserID,
		arg.WorkspaceID,
		arg.TaskID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoard = `-- name: GetBoard :one
SELECT id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds FROM boards WHERE id = $1
`

func (q *Queries) GetBoard(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoard, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const getBoardAccess = `-- name: GetBoardAccess :one

SELECT b.workspace_id,
       b.is_private,
       b.restricted,
       (b.archived_at IS NOT NULL)::boolean AS archived,
       m.role,
       coalesce(mr.ids, '{}')::uuid[] AS role_ids,
       coalesce(mr.positions, '{}')::integer[] AS role_positions,
       coalesce(mr.perms, '{}')::bigint[] AS role_permissions,
       coalesce(mr.allows, '{}')::bigint[] AS role_allows,
       coalesce(mr.denies, '{}')::bigint[] AS role_denies,
       uo.allow AS user_allow, uo.deny AS user_deny,
       (w.suspended_at IS NOT NULL)::boolean AS suspended,
       b.disabled_features,
       -- ADR-0059 / ADR-0076: the user (a human) is an assignee, an approver or a watcher of a
       -- live task of the board.
       (NOT coalesce(u.is_bot, true) AND (
           EXISTS (SELECT 1 FROM task_assignees x JOIN tasks t ON t.id = x.task_id
                   WHERE x.user_id = $1::uuid AND t.board_id = b.id AND t.archived_at IS NULL)
        OR EXISTS (SELECT 1 FROM task_approvers x JOIN tasks t ON t.id = x.task_id
                   WHERE x.user_id = $1::uuid AND t.board_id = b.id AND t.archived_at IS NULL)
        OR EXISTS (SELECT 1 FROM task_subscribers x JOIN tasks t ON t.id = x.task_id
                   WHERE x.user_id = $1::uuid AND x.watcher AND t.board_id = b.id AND t.archived_at IS NULL)
       ))::boolean AS invited
FROM boards b
JOIN workspaces w ON w.id = b.workspace_id
LEFT JOIN users u ON u.id = $1::uuid
LEFT JOIN workspace_members m ON m.workspace_id = b.workspace_id AND m.user_id = $1
LEFT JOIN LATERAL (
    SELECT array_agg(wr.id ORDER BY wr.position) AS ids,
           array_agg(wr.position ORDER BY wr.position) AS positions,
           array_agg(wr.permissions ORDER BY wr.position) AS perms,
           array_agg(coalesce(bo.allow, 0) ORDER BY wr.position) AS allows,
           array_agg(coalesce(bo.deny, 0) ORDER BY wr.position) AS denies
    FROM member_roles x
    JOIN workspace_roles wr ON wr.id = x.role_id
    LEFT JOIN board_permissions bo ON bo.board_id = b.id AND bo.target_type = 'role' AND bo.target_id = wr.id::text
    WHERE x.workspace_id = m.workspace_id AND x.user_id = m.user_id
) mr ON true
LEFT JOIN board_permissions uo ON uo.board_id = b.id AND uo.target_type = 'user' AND uo.target_id = $1::text
WHERE b.id = $2
`

type GetBoardAccessParams struct {
	UserID  uuid.UUID
	BoardID uuid.UUID
}

type GetBoardAccessRow struct {
	WorkspaceID      uuid.UUID
	IsPrivate        bool
	Restricted       bool
	Archived         bool
	Role             *string
	RoleIds          []uuid.UUID
	RolePositions    []int32
	RolePermissions  []int64
	RoleAllows       []int64
	RoleDenies       []int64
	UserAllow        *int64
	UserDeny         *int64
	Suspended        bool
	DisabledFeatures int64
	Invited          bool
}

// Task boards (ADR-0042). Task lists with filters are built dynamically in internal/boards
// (TaskFilter → SQL); everything else is here.
// Everything needed to compute a user's board bits, in one round trip: the membership (role
// NULL = not a member), the member's roles lowest position first with each role's board
// override (0/0 = none), the user's own override, the disabled board features (ADR-0058 §3:
// COMMENTS off makes the task rooms read-only) and whether the user is invited on a task.
func (q *Queries) GetBoardAccess(ctx context.Context, arg GetBoardAccessParams) (GetBoardAccessRow, error) {
	row := q.db.QueryRow(ctx, getBoardAccess, arg.UserID, arg.BoardID)
	var i GetBoardAccessRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.IsPrivate,
		&i.Restricted,
		&i.Archived,
		&i.Role,
		&i.RoleIds,
		&i.RolePositions,
		&i.RolePermissions,
		&i.RoleAllows,
		&i.RoleDenies,
		&i.UserAllow,
		&i.UserDeny,
		&i.Suspended,
		&i.DisabledFeatures,
		&i.Invited,
	)
	return i, err
}

const getBoardForUpdate = `-- name: GetBoardForUpdate :one
SELECT id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds FROM boards WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetBoardForUpdate(ctx context.Context, id uuid.UUID) (Board, error) {
	row := q.db.QueryRow(ctx, getBoardForUpdate, id)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const getBoardView = `-- name: GetBoardView :one
SELECT id, board_id, name, kind, filter, group_by, sort, shared, created_by, position, created_at FROM board_views WHERE id = $1 AND board_id = $2
`

type GetBoardViewParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) GetBoardView(ctx context.Context, arg GetBoardViewParams) (BoardView, error) {
	row := q.db.QueryRow(ctx, getBoardView, arg.ID, arg.BoardID)
	var i BoardView
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Kind,
		&i.Filter,
		&i.GroupBy,
		&i.Sort,
		&i.Shared,
		&i.CreatedBy,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const getTaskByNumber = `-- name: GetTaskByNumber :one
SELECT t.id, t.board_id, t.number, t.title, t.description, t.status_id, t.priority, t.created_by, t.estimate, t.start_on, t.due_on, t.parent_id, t.milestone_id, t.position, t.room_id, t.created_at, t.updated_at, t.started_at, t.completed_at, t.completed_by, t.archived_at, t.approval_required, t.task_milestone_id FROM tasks t JOIN boards b ON b.id = t.board_id
WHERE b.workspace_id = $1 AND b.key = $2 AND t.number = $3 AND b.archived_at IS NULL
`

type GetTaskByNumberParams struct {
	WorkspaceID uuid.UUID
	Key         string
	Number      int32
}

func (q *Queries) GetTaskByNumber(ctx context.Context, arg GetTaskByNumberParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByNumber, arg.WorkspaceID, arg.Key, arg.Number)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedBy,
		&i.Estimate,
		&i.StartOn,
		&i.DueOn,
		&i.ParentID,
		&i.MilestoneID,
		&i.Position,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ArchivedAt,
		&i.ApprovalRequired,
		&i.TaskMilestoneID,
	)
	return i, err
}

const getTaskInvite = `-- name: GetTaskInvite :one
SELECT EXISTS (SELECT 1 FROM task_assignees x WHERE x.task_id = $1 AND x.user_id = $2)::boolean AS assignee,
       EXISTS (SELECT 1 FROM task_approvers x WHERE x.task_id = $1 AND x.user_id = $2)::boolean AS approver,
       EXISTS (SELECT 1 FROM task_subscribers x WHERE x.task_id = $1 AND x.user_id = $2 AND x.watcher)::boolean AS watcher
`

type GetTaskInviteParams struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

type GetTaskInviteRow struct {
	Assignee bool
	Approver bool
	Watcher  bool
}

// Whether the user is an assignee / approver / watcher of a task (ADR-0059, ADR-0076:
// perm.TaskBits).
func (q *Queries) GetTaskInvite(ctx context.Context, arg GetTaskInviteParams) (GetTaskInviteRow, error) {
	row := q.db.QueryRow(ctx, getTaskInvite, arg.TaskID, arg.UserID)
	var i GetTaskInviteRow
	err := row.Scan(&i.Assignee, &i.Approver, &i.Watcher)
	return i, err
}

const getTaskLevel = `-- name: GetTaskLevel :many
SELECT u.id::uuid AS user_id, coalesce(s.task_level, 'all')::text AS task_level,
    (s.muted_until IS NOT NULL AND s.muted_until > now())::boolean AS muted
FROM unnest($1::uuid[]) AS u (id)
LEFT JOIN workspace_notification_settings s ON s.user_id = u.id AND s.workspace_id = $2
`

type GetTaskLevelParams struct {
	UserIds     []uuid.UUID
	WorkspaceID uuid.UUID
}

type GetTaskLevelRow struct {
	UserID    uuid.UUID
	TaskLevel string
	Muted     bool
}

// The users' task notification level and workspace mute in the workspace ('all' when unset).
func (q *Queries) GetTaskLevel(ctx context.Context, arg GetTaskLevelParams) ([]GetTaskLevelRow, error) {
	rows, err := q.db.Query(ctx, getTaskLevel, arg.UserIds, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTaskLevelRow{}
	for rows.Next() {
		var i GetTaskLevelRow
		if err := rows.Scan(&i.UserID, &i.TaskLevel, &i.Muted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTaskRoomRef = `-- name: GetTaskRoomRef :one
SELECT t.id AS task_id, t.board_id, (t.archived_at IS NOT NULL)::boolean AS task_archived,
       EXISTS (SELECT 1 FROM task_assignees x WHERE x.task_id = t.id AND x.user_id = $1)::boolean AS assignee,
       EXISTS (SELECT 1 FROM task_approvers x WHERE x.task_id = t.id AND x.user_id = $1)::boolean AS approver,
       EXISTS (SELECT 1 FROM task_subscribers x WHERE x.task_id = t.id AND x.user_id = $1 AND x.watcher)::boolean AS watcher
FROM tasks t WHERE t.room_id = $2
`

type GetTaskRoomRefParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

type GetTaskRoomRefRow struct {
	TaskID       uuid.UUID
	BoardID      uuid.UUID
	TaskArchived bool
	Assignee     bool
	Approver     bool
	Watcher      bool
}

// The task and board of a task room and whether the user is its assignee / approver / watcher
// (perm.Resolver: RoomAccess.Task, ADR-0059, ADR-0076).
func (q *Queries) GetTaskRoomRef(ctx context.Context, arg GetTaskRoomRefParams) (GetTaskRoomRefRow, error) {
	row := q.db.QueryRow(ctx, getTaskRoomRef, arg.UserID, arg.RoomID)
	var i GetTaskRoomRefRow
	err := row.Scan(
		&i.TaskID,
		&i.BoardID,
		&i.TaskArchived,
		&i.Assignee,
		&i.Approver,
		&i.Watcher,
	)
	return i, err
}

const getTaskRow = `-- name: GetTaskRow :one
SELECT id, board_id, number, title, description, status_id, priority, created_by, estimate, start_on, due_on, parent_id, milestone_id, position, room_id, created_at, updated_at, started_at, completed_at, completed_by, archived_at, approval_required, task_milestone_id FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskRow(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskRow, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedBy,
		&i.Estimate,
		&i.StartOn,
		&i.DueOn,
		&i.ParentID,
		&i.MilestoneID,
		&i.Position,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ArchivedAt,
		&i.ApprovalRequired,
		&i.TaskMilestoneID,
	)
	return i, err
}

const getTaskRowForUpdate = `-- name: GetTaskRowForUpdate :one
SELECT id, board_id, number, title, description, status_id, priority, created_by, estimate, start_on, due_on, parent_id, milestone_id, position, room_id, created_at, updated_at, started_at, completed_at, completed_by, archived_at, approval_required, task_milestone_id FROM tasks WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTaskRowForUpdate(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskRowForUpdate, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.StatusID,
		&i.Priority,
		&i.CreatedBy,
		&i.Estimate,
		&i.StartOn,
		&i.DueOn,
		&i.ParentID,
		&i.MilestoneID,
		&i.Position,
		&i.RoomID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CompletedBy,
		&i.ArchivedAt,
		&i.ApprovalRequired,
		&i.TaskMilestoneID,
	)
	return i, err
}

const grantBoardUserOverride = `-- name: GrantBoardUserOverride :exec
INSERT INTO board_permissions (board_id, target_type, target_id, allow, deny)
VALUES ($1, 'user', $2::text, $3, 0)
ON CONFLICT (board_id, target_type, target_id) DO UPDATE
    SET allow = board_permissions.allow | (EXCLUDED.allow & ~board_permissions.deny)
`

type GrantBoardUserOverrideParams struct {
	BoardID uuid.UUID
	UserID  string
	Allow   int64
}

// A personal allow on a board (the caller who restricts it, ADR-0048): added to an existing
// override, never lifting its denies.
func (q *Queries) GrantBoardUserOverride(ctx context.Context, arg GrantBoardUserOverrideParams) error {
	_, err := q.db.Exec(ctx, grantBoardUserOverride, arg.BoardID, arg.UserID, arg.Allow)
	return err
}

const insertBoardOverride = `-- name: InsertBoardOverride :exec
INSERT INTO board_permissions (board_id, target_type, target_id, allow, deny)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (board_id, target_type, target_id) DO UPDATE SET allow = EXCLUDED.allow, deny = EXCLUDED.deny
`

type InsertBoardOverrideParams struct {
	BoardID    uuid.UUID
	TargetType string
	TargetID   string
	Allow      int64
	Deny       int64
}

func (q *Queries) InsertBoardOverride(ctx context.Context, arg InsertBoardOverrideParams) error {
	_, err := q.db.Exec(ctx, insertBoardOverride,
		arg.BoardID,
		arg.TargetType,
		arg.TargetID,
		arg.Allow,
		arg.Deny,
	)
	return err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (board_id, number, title, description, status_id, priority, created_by, estimate,
                   start_on, due_on, parent_id, milestone_id, position, room_id, started_at, completed_at, completed_by,
                   approval_required)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9, $10,
        $11, $12, $13, $14,
        $15, $16, $17, $18)
RETURNING id
`

type InsertTaskParams struct {
	BoardID          uuid.UUID
	Number           int32
	Title            string
	Description      string
	StatusID         uuid.UUID
	Priority         int16
	CreatedBy        *uuid.UUID
	Estimate         *int16
	StartOn          pgtype.Date
	DueOn            pgtype.Date
	ParentID         *uuid.UUID
	MilestoneID      *uuid.UUID
	Position         float64
	RoomID           uuid.UUID
	StartedAt        *time.Time
	CompletedAt      *time.Time
	CompletedBy      *uuid.UUID
	ApprovalRequired int16
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.BoardID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.CreatedBy,
		arg.Estimate,
		arg.StartOn,
		arg.DueOn,
		arg.ParentID,
		arg.MilestoneID,
		arg.Position,
		arg.RoomID,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.ApprovalRequired,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const insertTaskActivity = `-- name: InsertTaskActivity :one

INSERT INTO task_activity (task_id, board_id, actor_id, kind, before, after, rule_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, task_id, board_id, actor_id, kind, before, after, created_at, rule_id
`

type InsertTaskActivityParams struct {
	TaskID  uuid.UUID
	BoardID uuid.UUID
	ActorID *uuid.UUID
	Kind    string
	Before  []byte
	After   []byte
	RuleID  *uuid.UUID
}

// ---- activity ----
func (q *Queries) InsertTaskActivity(ctx context.Context, arg InsertTaskActivityParams) (TaskActivity, error) {
	row := q.db.QueryRow(ctx, insertTaskActivity,
		arg.TaskID,
		arg.BoardID,
		arg.ActorID,
		arg.Kind,
		arg.Before,
		arg.After,
		arg.RuleID,
	)
	var i TaskActivity
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.BoardID,
		&i.ActorID,
		&i.Kind,
		&i.Before,
		&i.After,
		&i.CreatedAt,
		&i.RuleID,
	)
	return i, err
}

const insertTaskApprover = `-- name: InsertTaskApprover :exec
INSERT INTO task_approvers (task_id, user_id, added_by, added_at) VALUES ($1, $2, $3, clock_timestamp())
ON CONFLICT DO NOTHING
`

type InsertTaskApproverParams struct {
	TaskID  uuid.UUID
	UserID  uuid.UUID
	AddedBy *uuid.UUID
}

// clock_timestamp: approvers added in one request keep their order (added_at).
func (q *Queries) InsertTaskApprover(ctx context.Context, arg InsertTaskApproverParams) error {
	_, err := q.db.Exec(ctx, insertTaskApprover, arg.TaskID, arg.UserID, arg.AddedBy)
	return err
}

const insertTaskAssignee = `-- name: InsertTaskAssignee :exec
INSERT INTO task_assignees (task_id, user_id, is_lead, note, assigned_by, assigned_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTaskAssigneeParams struct {
	TaskID     uuid.UUID
	UserID     uuid.UUID
	IsLead     bool
	Note       string
	AssignedBy *uuid.UUID
	AssignedAt time.Time
}

func (q *Queries) InsertTaskAssignee(ctx context.Context, arg InsertTaskAssigneeParams) error {
	_, err := q.db.Exec(ctx, insertTaskAssignee,
		arg.TaskID,
		arg.UserID,
		arg.IsLead,
		arg.Note,
		arg.AssignedBy,
		arg.AssignedAt,
	)
	return err
}

const insertTaskAttachment = `-- name: InsertTaskAttachment :exec
INSERT INTO task_attachments (task_id, file_id, position) VALUES ($1, $2, $3)
`

type InsertTaskAttachmentParams struct {
	TaskID   uuid.UUID
	FileID   uuid.UUID
	Position int16
}

func (q *Queries) InsertTaskAttachment(ctx context.Context, arg InsertTaskAttachmentParams) error {
	_, err := q.db.Exec(ctx, insertTaskAttachment, arg.TaskID, arg.FileID, arg.Position)
	return err
}

const insertTaskLabels = `-- name: InsertTaskLabels :exec
INSERT INTO task_labels (task_id, label_id) SELECT $1, unnest($2::uuid[])
`

type InsertTaskLabelsParams struct {
	TaskID   uuid.UUID
	LabelIds []uuid.UUID
}

func (q *Queries) InsertTaskLabels(ctx context.Context, arg InsertTaskLabelsParams) error {
	_, err := q.db.Exec(ctx, insertTaskLabels, arg.TaskID, arg.LabelIds)
	return err
}

const insertTaskRelation = `-- name: InsertTaskRelation :execrows
INSERT INTO task_relations (task_id, related_id, kind, created_by) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type InsertTaskRelationParams struct {
	TaskID    uuid.UUID
	RelatedID uuid.UUID
	Kind      string
	CreatedBy *uuid.UUID
}

func (q *Queries) InsertTaskRelation(ctx context.Context, arg InsertTaskRelationParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertTaskRelation,
		arg.TaskID,
		arg.RelatedID,
		arg.Kind,
		arg.CreatedBy,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listBoardActivity = `-- name: ListBoardActivity :many
SELECT a.id, a.task_id, a.board_id, a.actor_id, a.kind, a.before, a.after, a.created_at, a.rule_id, b.key AS board_key, t.number AS task_number FROM task_activity a
JOIN tasks t ON t.id = a.task_id
JOIN boards b ON b.id = t.board_id
WHERE a.board_id = $1
  AND ($2::timestamptz IS NULL OR a.created_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR a.created_at < $3::timestamptz)
  AND ($4::uuid IS NULL OR a.actor_id = $4::uuid)
  AND ($5::text IS NULL OR a.kind = $5::text)
  AND ($6::uuid IS NULL OR a.id > $6::uuid)
ORDER BY a.id
LIMIT $7
`

type ListBoardActivityParams struct {
	BoardID uuid.UUID
	Since   *time.Time
	Until   *time.Time
	Actor   *uuid.UUID
	Kind    *string
	AfterID *uuid.UUID
	Lim     int32
}

type ListBoardActivityRow struct {
	ID         uuid.UUID
	TaskID     uuid.UUID
	BoardID    uuid.UUID
	ActorID    *uuid.UUID
	Kind       string
	Before     []byte
	After      []byte
	CreatedAt  time.Time
	RuleID     *uuid.UUID
	BoardKey   string
	TaskNumber int32
}

func (q *Queries) ListBoardActivity(ctx context.Context, arg ListBoardActivityParams) ([]ListBoardActivityRow, error) {
	rows, err := q.db.Query(ctx, listBoardActivity,
		arg.BoardID,
		arg.Since,
		arg.Until,
		arg.Actor,
		arg.Kind,
		arg.AfterID,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBoardActivityRow{}
	for rows.Next() {
		var i ListBoardActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.BoardID,
			&i.ActorID,
			&i.Kind,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.RuleID,
			&i.BoardKey,
			&i.TaskNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardInvitees = `-- name: ListBoardInvitees :many
SELECT DISTINCT x.user_id FROM tasks t
JOIN (SELECT a.task_id, a.user_id FROM task_assignees a
      UNION ALL SELECT p.task_id, p.user_id FROM task_approvers p
      UNION ALL SELECT w.task_id, w.user_id FROM task_subscribers w WHERE w.watcher) x ON x.task_id = t.id
JOIN users u ON u.id = x.user_id AND NOT u.is_bot
WHERE t.board_id = $1 AND t.archived_at IS NULL
`

// The humans who are assignees, approvers or watchers of the live tasks of a board (ADR-0076:
// «Позванные по карточкам» counts those of them without VIEW_BOARD).
func (q *Queries) ListBoardInvitees(ctx context.Context, boardID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listBoardInvitees, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardLabels = `-- name: ListBoardLabels :many
SELECT id, board_id, name, color, position FROM board_labels WHERE board_id = ANY($1::uuid[]) ORDER BY board_id, position, id
`

func (q *Queries) ListBoardLabels(ctx context.Context, boardIds []uuid.UUID) ([]BoardLabel, error) {
	rows, err := q.db.Query(ctx, listBoardLabels, boardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardLabel{}
	for rows.Next() {
		var i BoardLabel
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Color,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardMilestones = `-- name: ListBoardMilestones :many
SELECT id, board_id, name, due_on, position FROM board_milestones WHERE board_id = ANY($1::uuid[]) ORDER BY board_id, position, id
`

func (q *Queries) ListBoardMilestones(ctx context.Context, boardIds []uuid.UUID) ([]BoardMilestone, error) {
	rows, err := q.db.Query(ctx, listBoardMilestones, boardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardMilestone{}
	for rows.Next() {
		var i BoardMilestone
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.DueOn,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardOverrides = `-- name: ListBoardOverrides :many
SELECT board_id, target_type, target_id, allow, deny FROM board_permissions WHERE board_id = $1 ORDER BY target_type, target_id
`

func (q *Queries) ListBoardOverrides(ctx context.Context, boardID uuid.UUID) ([]BoardPermission, error) {
	rows, err := q.db.Query(ctx, listBoardOverrides, boardID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardPermission{}
	for rows.Next() {
		var i BoardPermission
		if err := rows.Scan(
			&i.BoardID,
			&i.TargetType,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardStatuses = `-- name: ListBoardStatuses :many

SELECT id, board_id, name, type, color, position, is_default FROM board_statuses WHERE board_id = ANY($1::uuid[]) ORDER BY board_id, position, id
`

// ---- statuses, labels, milestones ----
func (q *Queries) ListBoardStatuses(ctx context.Context, boardIds []uuid.UUID) ([]BoardStatus, error) {
	rows, err := q.db.Query(ctx, listBoardStatuses, boardIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardStatus{}
	for rows.Next() {
		var i BoardStatus
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Type,
			&i.Color,
			&i.Position,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoardViews = `-- name: ListBoardViews :many

SELECT id, board_id, name, kind, filter, group_by, sort, shared, created_by, position, created_at FROM board_views
WHERE board_id = ANY($1::uuid[])
  AND (shared OR created_by = $2::uuid)
ORDER BY board_id, position, id
`

type ListBoardViewsParams struct {
	BoardIds []uuid.UUID
	UserID   *uuid.UUID
}

// ---- views ----
// Shared views of the boards and the user's own (user_id NULL: shared only).
func (q *Queries) ListBoardViews(ctx context.Context, arg ListBoardViewsParams) ([]BoardView, error) {
	rows, err := q.db.Query(ctx, listBoardViews, arg.BoardIds, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardView{}
	for rows.Next() {
		var i BoardView
		if err := rows.Scan(
			&i.ID,
			&i.BoardID,
			&i.Name,
			&i.Kind,
			&i.Filter,
			&i.GroupBy,
			&i.Sort,
			&i.Shared,
			&i.CreatedBy,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBoards = `-- name: ListBoards :many
SELECT id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds FROM boards WHERE workspace_id = $1 AND (archived_at IS NOT NULL) = $2::boolean
ORDER BY position, id
`

type ListBoardsParams struct {
	WorkspaceID uuid.UUID
	Archived    bool
}

func (q *Queries) ListBoards(ctx context.Context, arg ListBoardsParams) ([]Board, error) {
	rows, err := q.db.Query(ctx, listBoards, arg.WorkspaceID, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Board{}
	for rows.Next() {
		var i Board
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Key,
			&i.Emoji,
			&i.IconFileID,
			&i.Description,
			&i.IsPrivate,
			&i.Position,
			&i.NextNumber,
			&i.AutoArchiveDays,
			&i.DefaultViewID,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ArchivedAt,
			&i.Restricted,
			&i.CategoryID,
			&i.DisabledFeatures,
			&i.EstimateScale,
			&i.ApprovalNotifyDelaySeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInvitedTasks = `-- name: ListInvitedTasks :many
SELECT t.id, t.board_id
FROM tasks t JOIN boards b ON b.id = t.board_id
WHERE b.workspace_id = $1 AND b.archived_at IS NULL AND t.archived_at IS NULL
  AND t.id IN (SELECT x.task_id FROM task_assignees x WHERE x.user_id = $2
               UNION SELECT a.task_id FROM task_approvers a WHERE a.user_id = $2
               UNION SELECT w.task_id FROM task_subscribers w WHERE w.user_id = $2 AND w.watcher)
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.id = $2 AND u.is_bot)
`

type ListInvitedTasksParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type ListInvitedTasksRow struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

// The live tasks on live boards of a workspace where the user (a human) is an assignee, an
// approver or a watcher: the task-scoped boards of ADR-0059 (restricted ones too, ADR-0076).
func (q *Queries) ListInvitedTasks(ctx context.Context, arg ListInvitedTasksParams) ([]ListInvitedTasksRow, error) {
	rows, err := q.db.Query(ctx, listInvitedTasks, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListInvitedTasksRow{}
	for rows.Next() {
		var i ListInvitedTasksRow
		if err := rows.Scan(&i.ID, &i.BoardID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskActivity = `-- name: ListTaskActivity :many
SELECT id, task_id, board_id, actor_id, kind, before, after, created_at, rule_id FROM task_activity WHERE task_id = $1
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC LIMIT $3
`

type ListTaskActivityParams struct {
	TaskID uuid.UUID
	Before *uuid.UUID
	Lim    int32
}

func (q *Queries) ListTaskActivity(ctx context.Context, arg ListTaskActivityParams) ([]TaskActivity, error) {
	rows, err := q.db.Query(ctx, listTaskActivity, arg.TaskID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskActivity{}
	for rows.Next() {
		var i TaskActivity
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.BoardID,
			&i.ActorID,
			&i.Kind,
			&i.Before,
			&i.After,
			&i.CreatedAt,
			&i.RuleID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskApprovers = `-- name: ListTaskApprovers :many

SELECT task_id, user_id, state, comment, decided_at, added_by, added_at, requested_at, reminders, reminded_at, notify_due_at, notify_reason FROM task_approvers WHERE task_id = ANY($1::uuid[])
ORDER BY task_id, added_at, user_id
`

// ---- approvals (ADR-0049) ----
func (q *Queries) ListTaskApprovers(ctx context.Context, taskIds []uuid.UUID) ([]TaskApprover, error) {
	rows, err := q.db.Query(ctx, listTaskApprovers, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskApprover{}
	for rows.Next() {
		var i TaskApprover
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.State,
			&i.Comment,
			&i.DecidedAt,
			&i.AddedBy,
			&i.AddedAt,
			&i.RequestedAt,
			&i.Reminders,
			&i.RemindedAt,
			&i.NotifyDueAt,
			&i.NotifyReason,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAssignees = `-- name: ListTaskAssignees :many
SELECT task_id, user_id, is_lead, note, assigned_by, assigned_at FROM task_assignees WHERE task_id = ANY($1::uuid[])
ORDER BY task_id, is_lead DESC, assigned_at, user_id
`

func (q *Queries) ListTaskAssignees(ctx context.Context, taskIds []uuid.UUID) ([]TaskAssignee, error) {
	rows, err := q.db.Query(ctx, listTaskAssignees, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskAssignee{}
	for rows.Next() {
		var i TaskAssignee
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.IsLead,
			&i.Note,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskAttachments = `-- name: ListTaskAttachments :many
SELECT f.id, f.workspace_id, f.uploader_id, f.key, f.thumbnail_key, f.name, f.mime, f.size, f.width, f.height, f.sha256, f.created_at, f.voice_duration_ms, f.voice_waveform FROM task_attachments a JOIN files f ON f.id = a.file_id WHERE a.task_id = $1 ORDER BY a.position
`

func (q *Queries) ListTaskAttachments(ctx context.Context, taskID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listTaskAttachments, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploaderID,
			&i.Key,
			&i.ThumbnailKey,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.CreatedAt,
			&i.VoiceDurationMs,
			&i.VoiceWaveform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskInvites = `-- name: ListTaskInvites :many
SELECT x.task_id FROM task_assignees x WHERE x.task_id = ANY($1::uuid[]) AND x.user_id = $2
UNION
SELECT a.task_id FROM task_approvers a WHERE a.task_id = ANY($1::uuid[]) AND a.user_id = $2
UNION
SELECT w.task_id FROM task_subscribers w WHERE w.task_id = ANY($1::uuid[]) AND w.user_id = $2 AND w.watcher
`

type ListTaskInvitesParams struct {
	Ids    []uuid.UUID
	UserID uuid.UUID
}

// The tasks among ids where the user is an assignee, an approver or a watcher (ADR-0059,
// ADR-0076).
func (q *Queries) ListTaskInvites(ctx context.Context, arg ListTaskInvitesParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listTaskInvites, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var task_id uuid.UUID
		if err := rows.Scan(&task_id); err != nil {
			return nil, err
		}
		items = append(items, task_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskLabelIDs = `-- name: ListTaskLabelIDs :many
SELECT task_id, label_id FROM task_labels WHERE task_id = ANY($1::uuid[])
`

func (q *Queries) ListTaskLabelIDs(ctx context.Context, taskIds []uuid.UUID) ([]TaskLabel, error) {
	rows, err := q.db.Query(ctx, listTaskLabelIDs, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskLabel{}
	for rows.Next() {
		var i TaskLabel
		if err := rows.Scan(&i.TaskID, &i.LabelID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRelations = `-- name: ListTaskRelations :many
SELECT task_id, related_id, kind FROM task_relations
WHERE task_id = ANY($1::uuid[]) OR related_id = ANY($1::uuid[])
`

type ListTaskRelationsRow struct {
	TaskID    uuid.UUID
	RelatedID uuid.UUID
	Kind      string
}

func (q *Queries) ListTaskRelations(ctx context.Context, taskIds []uuid.UUID) ([]ListTaskRelationsRow, error) {
	rows, err := q.db.Query(ctx, listTaskRelations, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskRelationsRow{}
	for rows.Next() {
		var i ListTaskRelationsRow
		if err := rows.Scan(&i.TaskID, &i.RelatedID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskRoomMessages = `-- name: ListTaskRoomMessages :many
SELECT id, room_id, author_id, content, reply_to_id, nonce, created_at, edited_at, deleted_at, pinned_at, pinned_by, embeds_hidden, kind, payload, sticker_id, forwarded_from, forward_author_id, forward_sent_at, inline_keyboard, keyboard_revision FROM messages WHERE room_id = $1 AND deleted_at IS NULL
  AND ($2::uuid IS NULL OR id < $2::uuid)
ORDER BY id DESC LIMIT $3
`

type ListTaskRoomMessagesParams struct {
	RoomID uuid.UUID
	Before *uuid.UUID
	Lim    int32
}

func (q *Queries) ListTaskRoomMessages(ctx context.Context, arg ListTaskRoomMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listTaskRoomMessages, arg.RoomID, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.AuthorID,
			&i.Content,
			&i.ReplyToID,
			&i.Nonce,
			&i.CreatedAt,
			&i.EditedAt,
			&i.DeletedAt,
			&i.PinnedAt,
			&i.PinnedBy,
			&i.EmbedsHidden,
			&i.Kind,
			&i.Payload,
			&i.StickerID,
			&i.ForwardedFrom,
			&i.ForwardAuthorID,
			&i.ForwardSentAt,
			&i.InlineKeyboard,
			&i.KeyboardRevision,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskSubscribers = `-- name: ListTaskSubscribers :many

SELECT task_id, user_id, muted, notified_at, seen_at, watcher FROM task_subscribers WHERE task_id = $1
`

// ---- subscriptions, notifications ----
func (q *Queries) ListTaskSubscribers(ctx context.Context, taskID uuid.UUID) ([]TaskSubscriber, error) {
	rows, err := q.db.Query(ctx, listTaskSubscribers, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSubscriber{}
	for rows.Next() {
		var i TaskSubscriber
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Muted,
			&i.NotifiedAt,
			&i.SeenAt,
			&i.Watcher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskWatchers = `-- name: ListTaskWatchers :many
SELECT task_id, user_id FROM task_subscribers WHERE task_id = ANY($1::uuid[]) AND watcher
ORDER BY task_id, user_id
`

type ListTaskWatchersRow struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

// The watchers of tasks (ADR-0076), in a stable order.
func (q *Queries) ListTaskWatchers(ctx context.Context, taskIds []uuid.UUID) ([]ListTaskWatchersRow, error) {
	rows, err := q.db.Query(ctx, listTaskWatchers, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskWatchersRow{}
	for rows.Next() {
		var i ListTaskWatchersRow
		if err := rows.Scan(&i.TaskID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewerSubscriptions = `-- name: ListViewerSubscriptions :many
SELECT task_id, user_id, muted, notified_at, seen_at, watcher FROM task_subscribers WHERE user_id = $1 AND task_id = ANY($2::uuid[])
`

type ListViewerSubscriptionsParams struct {
	UserID  uuid.UUID
	TaskIds []uuid.UUID
}

func (q *Queries) ListViewerSubscriptions(ctx context.Context, arg ListViewerSubscriptionsParams) ([]TaskSubscriber, error) {
	rows, err := q.db.Query(ctx, listViewerSubscriptions, arg.UserID, arg.TaskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskSubscriber{}
	for rows.Next() {
		var i TaskSubscriber
		if err := rows.Scan(
			&i.TaskID,
			&i.UserID,
			&i.Muted,
			&i.NotifiedAt,
			&i.SeenAt,
			&i.Watcher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceBoardOverrides = `-- name: ListWorkspaceBoardOverrides :many
SELECT bp.board_id, bp.target_type, bp.target_id, bp.allow, bp.deny FROM board_permissions bp JOIN boards b ON b.id = bp.board_id
WHERE b.workspace_id = $1
ORDER BY bp.board_id, bp.target_type, bp.target_id
`

func (q *Queries) ListWorkspaceBoardOverrides(ctx context.Context, workspaceID uuid.UUID) ([]BoardPermission, error) {
	rows, err := q.db.Query(ctx, listWorkspaceBoardOverrides, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardPermission{}
	for rows.Next() {
		var i BoardPermission
		if err := rows.Scan(
			&i.BoardID,
			&i.TargetType,
			&i.TargetID,
			&i.Allow,
			&i.Deny,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTaskInvitees = `-- name: ListWorkspaceTaskInvitees :many
SELECT t.id AS task_id, t.board_id, x.user_id,
       bool_or(x.how = 1)::boolean AS assignee, bool_or(x.how = 2)::boolean AS approver, bool_or(x.how = 3)::boolean AS watcher
FROM tasks t
JOIN boards b ON b.id = t.board_id
JOIN (SELECT a.task_id, a.user_id, 1 AS how FROM task_assignees a
      UNION ALL SELECT p.task_id, p.user_id, 2 AS how FROM task_approvers p
      UNION ALL SELECT w.task_id, w.user_id, 3 AS how FROM task_subscribers w WHERE w.watcher) x ON x.task_id = t.id
JOIN users u ON u.id = x.user_id AND NOT u.is_bot
WHERE b.workspace_id = $1 AND b.archived_at IS NULL AND t.archived_at IS NULL
GROUP BY t.id, t.board_id, x.user_id
`

type ListWorkspaceTaskInviteesRow struct {
	TaskID   uuid.UUID
	BoardID  uuid.UUID
	UserID   uuid.UUID
	Assignee bool
	Approver bool
	Watcher  bool
}

// The assignees, approvers and watchers (humans) of the live tasks on live boards of a
// workspace: the gateway's invited map (ADR-0059, ADR-0076). how: 1 assignee, 2 approver,
// 3 watcher.
func (q *Queries) ListWorkspaceTaskInvitees(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceTaskInviteesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTaskInvitees, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceTaskInviteesRow{}
	for rows.Next() {
		var i ListWorkspaceTaskInviteesRow
		if err := rows.Scan(
			&i.TaskID,
			&i.BoardID,
			&i.UserID,
			&i.Assignee,
			&i.Approver,
			&i.Watcher,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceTaskRooms = `-- name: ListWorkspaceTaskRooms :many
SELECT t.id, t.room_id, t.board_id, (t.archived_at IS NOT NULL)::boolean AS archived
FROM tasks t JOIN boards b ON b.id = t.board_id
WHERE b.workspace_id = $1 AND b.archived_at IS NULL
`

type ListWorkspaceTaskRoomsRow struct {
	ID       uuid.UUID
	RoomID   uuid.UUID
	BoardID  uuid.UUID
	Archived bool
}

// The comment rooms of the tasks on live boards of a workspace (the gateway's task room map).
func (q *Queries) ListWorkspaceTaskRooms(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceTaskRoomsRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceTaskRooms, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceTaskRoomsRow{}
	for rows.Next() {
		var i ListWorkspaceTaskRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.BoardID,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBoards = `-- name: LockBoards :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.boards:' || $1::text))
`

// Serializes board creation / ordering of one workspace (count limit, positions).
func (q *Queries) LockBoards(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, lockBoards, workspaceID)
	return err
}

const markNotified = `-- name: MarkNotified :exec
UPDATE task_subscribers SET notified_at = now() WHERE task_id = $1 AND user_id = ANY($2::uuid[])
`

type MarkNotifiedParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) MarkNotified(ctx context.Context, arg MarkNotifiedParams) error {
	_, err := q.db.Exec(ctx, markNotified, arg.TaskID, arg.UserIds)
	return err
}

const markTaskSeen = `-- name: MarkTaskSeen :one
WITH old AS (
    SELECT (o.notified_at IS NOT NULL AND (o.seen_at IS NULL OR o.notified_at > o.seen_at)) AS unread
    FROM task_subscribers o WHERE o.task_id = $1 AND o.user_id = $2
), upd AS (
    UPDATE task_subscribers u SET seen_at = now() WHERE u.task_id = $1 AND u.user_id = $2
)
SELECT coalesce((SELECT old.unread FROM old), false)::boolean
`

type MarkTaskSeenParams struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

// Returns whether the task was unread.
func (q *Queries) MarkTaskSeen(ctx context.Context, arg MarkTaskSeenParams) (bool, error) {
	row := q.db.QueryRow(ctx, markTaskSeen, arg.TaskID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const maxStatusPosition = `-- name: MaxStatusPosition :one
SELECT coalesce(max(position), 0)::double precision FROM tasks WHERE status_id = $1 AND archived_at IS NULL
`

func (q *Queries) MaxStatusPosition(ctx context.Context, statusID uuid.UUID) (float64, error) {
	row := q.db.QueryRow(ctx, maxStatusPosition, statusID)
	var column_1 float64
	err := row.Scan(&column_1)
	return column_1, err
}

const moveStatusTasks = `-- name: MoveStatusTasks :many
UPDATE tasks t SET status_id = $1, updated_at = now(),
    position = coalesce((SELECT max(x.position) FROM tasks x WHERE x.status_id = $1), 0) + 1024 * t.number
WHERE t.status_id = $2
RETURNING t.id
`

type MoveStatusTasksParams struct {
	ToID   uuid.UUID
	FromID uuid.UUID
}

// Moves every task of a status (archived ones too) to another status of the board, at the end.
func (q *Queries) MoveStatusTasks(ctx context.Context, arg MoveStatusTasksParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, moveStatusTasks, arg.ToID, arg.FromID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTaskToBoard = `-- name: MoveTaskToBoard :exec
UPDATE tasks SET board_id = $1, number = $2, status_id = $3,
    milestone_id = NULL, parent_id = NULL, task_milestone_id = NULL, position = $4, updated_at = now()
WHERE id = $5
`

type MoveTaskToBoardParams struct {
	BoardID  uuid.UUID
	Number   int32
	StatusID uuid.UUID
	Position float64
	ID       uuid.UUID
}

func (q *Queries) MoveTaskToBoard(ctx context.Context, arg MoveTaskToBoardParams) error {
	_, err := q.db.Exec(ctx, moveTaskToBoard,
		arg.BoardID,
		arg.Number,
		arg.StatusID,
		arg.Position,
		arg.ID,
	)
	return err
}

const nextTaskNumber = `-- name: NextTaskNumber :one
UPDATE boards SET next_number = next_number + 1 WHERE id = $1 RETURNING next_number - 1
`

// Takes the next task number of a board (the row lock serializes concurrent creates).
func (q *Queries) NextTaskNumber(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextTaskNumber, id)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const resetTaskApprovals = `-- name: ResetTaskApprovals :many
UPDATE task_approvers SET state = 'pending', comment = '', decided_at = NULL, requested_at = now(),
    reminders = 0, reminded_at = NULL, notify_due_at = NULL
WHERE task_id = $1 AND state <> 'pending'
RETURNING user_id
`

// The task changed (title / description / its attachments): every decided vote is asked for
// again; pending ones keep their notice and reminder schedule (ADR-0082). Returns the
// approvers whose vote was reset.
func (q *Queries) ResetTaskApprovals(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, resetTaskApprovals, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scheduleApprovalNotices = `-- name: ScheduleApprovalNotices :exec
UPDATE task_approvers SET notify_due_at = now() + make_interval(secs => $1::integer),
    notify_reason = $2::text
WHERE task_id = $3 AND user_id = ANY($4::uuid[])
`

type ScheduleApprovalNoticesParams struct {
	Delay   int32
	Reason  string
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

// The approval notice of these approvers goes out in delay seconds (ADR-0082, DB time).
func (q *Queries) ScheduleApprovalNotices(ctx context.Context, arg ScheduleApprovalNoticesParams) error {
	_, err := q.db.Exec(ctx, scheduleApprovalNotices,
		arg.Delay,
		arg.Reason,
		arg.TaskID,
		arg.UserIds,
	)
	return err
}

const setApproverVote = `-- name: SetApproverVote :exec
UPDATE task_approvers SET state = $1::text, comment = $2::text,
    notify_due_at = CASE WHEN $1::text = 'pending' THEN notify_due_at ELSE NULL END,
    decided_at = CASE WHEN $1::text = 'pending' THEN NULL ELSE now() END,
    requested_at = CASE WHEN $1::text = 'pending' THEN now() ELSE requested_at END,
    reminders = CASE WHEN $1::text = 'pending' THEN 0 ELSE reminders END,
    reminded_at = CASE WHEN $1::text = 'pending' THEN NULL ELSE reminded_at END
WHERE task_id = $3 AND user_id = $4
`

type SetApproverVoteParams struct {
	State   string
	Comment string
	TaskID  uuid.UUID
	UserID  uuid.UUID
}

// A vote; pending (withdraw) asks for it again: the reminders start over. A cast vote drops its
// notice not sent yet (ADR-0082): a later reset or delay-0 request is then never sent twice.
func (q *Queries) SetApproverVote(ctx context.Context, arg SetApproverVoteParams) error {
	_, err := q.db.Exec(ctx, setApproverVote,
		arg.State,
		arg.Comment,
		arg.TaskID,
		arg.UserID,
	)
	return err
}

const setBoardArchived = `-- name: SetBoardArchived :one
UPDATE boards SET archived_at = CASE WHEN $1::boolean THEN now() ELSE NULL END
WHERE id = $2
RETURNING id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds
`

type SetBoardArchivedParams struct {
	Archived bool
	ID       uuid.UUID
}

func (q *Queries) SetBoardArchived(ctx context.Context, arg SetBoardArchivedParams) (Board, error) {
	row := q.db.QueryRow(ctx, setBoardArchived, arg.Archived, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const setBoardFeatures = `-- name: SetBoardFeatures :one
UPDATE boards SET
    disabled_features = coalesce($1, disabled_features),
    estimate_scale    = coalesce($2, estimate_scale)
WHERE id = $3
RETURNING id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds
`

type SetBoardFeaturesParams struct {
	DisabledFeatures *int64
	EstimateScale    *string
	ID               uuid.UUID
}

// Board features (ADR-0058 §3): the disabled BoardFeature bit mask and the estimate scale.
func (q *Queries) SetBoardFeatures(ctx context.Context, arg SetBoardFeaturesParams) (Board, error) {
	row := q.db.QueryRow(ctx, setBoardFeatures, arg.DisabledFeatures, arg.EstimateScale, arg.ID)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const setBoardLabelPosition = `-- name: SetBoardLabelPosition :exec
UPDATE board_labels SET position = $2 WHERE id = $1
`

type SetBoardLabelPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetBoardLabelPosition(ctx context.Context, arg SetBoardLabelPositionParams) error {
	_, err := q.db.Exec(ctx, setBoardLabelPosition, arg.ID, arg.Position)
	return err
}

const setBoardMilestonePosition = `-- name: SetBoardMilestonePosition :exec
UPDATE board_milestones SET position = $2 WHERE id = $1
`

type SetBoardMilestonePositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetBoardMilestonePosition(ctx context.Context, arg SetBoardMilestonePositionParams) error {
	_, err := q.db.Exec(ctx, setBoardMilestonePosition, arg.ID, arg.Position)
	return err
}

const setBoardPosition = `-- name: SetBoardPosition :exec
UPDATE boards SET position = $2 WHERE id = $1
`

type SetBoardPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetBoardPosition(ctx context.Context, arg SetBoardPositionParams) error {
	_, err := q.db.Exec(ctx, setBoardPosition, arg.ID, arg.Position)
	return err
}

const setBoardStatusPosition = `-- name: SetBoardStatusPosition :exec
UPDATE board_statuses SET position = $2 WHERE id = $1
`

type SetBoardStatusPositionParams struct {
	ID       uuid.UUID
	Position int32
}

func (q *Queries) SetBoardStatusPosition(ctx context.Context, arg SetBoardStatusPositionParams) error {
	_, err := q.db.Exec(ctx, setBoardStatusPosition, arg.ID, arg.Position)
	return err
}

const setDefaultBoardStatus = `-- name: SetDefaultBoardStatus :exec
UPDATE board_statuses SET is_default = true WHERE id = $1 AND board_id = $2
`

type SetDefaultBoardStatusParams struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

// Call ClearDefaultBoardStatus first (the partial unique index allows one default per board).
func (q *Queries) SetDefaultBoardStatus(ctx context.Context, arg SetDefaultBoardStatusParams) error {
	_, err := q.db.Exec(ctx, setDefaultBoardStatus, arg.ID, arg.BoardID)
	return err
}

const setSubscription = `-- name: SetSubscription :one
INSERT INTO task_subscribers (task_id, user_id, muted) VALUES ($1, $2, $3)
ON CONFLICT (task_id, user_id) DO UPDATE SET muted = EXCLUDED.muted
RETURNING task_id, user_id, muted, notified_at, seen_at, watcher
`

type SetSubscriptionParams struct {
	TaskID uuid.UUID
	UserID uuid.UUID
	Muted  bool
}

func (q *Queries) SetSubscription(ctx context.Context, arg SetSubscriptionParams) (TaskSubscriber, error) {
	row := q.db.QueryRow(ctx, setSubscription, arg.TaskID, arg.UserID, arg.Muted)
	var i TaskSubscriber
	err := row.Scan(
		&i.TaskID,
		&i.UserID,
		&i.Muted,
		&i.NotifiedAt,
		&i.SeenAt,
		&i.Watcher,
	)
	return i, err
}

const setTaskApprovalRequired = `-- name: SetTaskApprovalRequired :exec
UPDATE tasks SET approval_required = $2, updated_at = now() WHERE id = $1
`

type SetTaskApprovalRequiredParams struct {
	ID               uuid.UUID
	ApprovalRequired int16
}

func (q *Queries) SetTaskApprovalRequired(ctx context.Context, arg SetTaskApprovalRequiredParams) error {
	_, err := q.db.Exec(ctx, setTaskApprovalRequired, arg.ID, arg.ApprovalRequired)
	return err
}

const setTaskArchived = `-- name: SetTaskArchived :exec
UPDATE tasks SET archived_at = CASE WHEN $1::boolean THEN now() ELSE NULL END, updated_at = now()
WHERE id = $2
`

type SetTaskArchivedParams struct {
	Archived bool
	ID       uuid.UUID
}

func (q *Queries) SetTaskArchived(ctx context.Context, arg SetTaskArchivedParams) error {
	_, err := q.db.Exec(ctx, setTaskArchived, arg.Archived, arg.ID)
	return err
}

const setTaskPosition = `-- name: SetTaskPosition :exec
UPDATE tasks SET position = $2 WHERE id = $1
`

type SetTaskPositionParams struct {
	ID       uuid.UUID
	Position float64
}

func (q *Queries) SetTaskPosition(ctx context.Context, arg SetTaskPositionParams) error {
	_, err := q.db.Exec(ctx, setTaskPosition, arg.ID, arg.Position)
	return err
}

const statusPositions = `-- name: StatusPositions :many
SELECT id, position FROM tasks WHERE status_id = $1 AND archived_at IS NULL ORDER BY position, id
`

type StatusPositionsRow struct {
	ID       uuid.UUID
	Position float64
}

// Live tasks of a status by position (the neighbours of a kanban move, renormalisation).
func (q *Queries) StatusPositions(ctx context.Context, statusID uuid.UUID) ([]StatusPositionsRow, error) {
	rows, err := q.db.Query(ctx, statusPositions, statusID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []StatusPositionsRow{}
	for rows.Next() {
		var i StatusPositionsRow
		if err := rows.Scan(&i.ID, &i.Position); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const subscribe = `-- name: Subscribe :exec
INSERT INTO task_subscribers (task_id, user_id) SELECT $1, unnest($2::uuid[])
ON CONFLICT DO NOTHING
`

type SubscribeParams struct {
	TaskID  uuid.UUID
	UserIds []uuid.UUID
}

// Auto-subscription: keeps an existing row (a muted one stays muted).
func (q *Queries) Subscribe(ctx context.Context, arg SubscribeParams) error {
	_, err := q.db.Exec(ctx, subscribe, arg.TaskID, arg.UserIds)
	return err
}

const taskAttachmentIDs = `-- name: TaskAttachmentIDs :many
SELECT file_id FROM task_attachments WHERE task_id = $1 ORDER BY position
`

func (q *Queries) TaskAttachmentIDs(ctx context.Context, taskID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, taskAttachmentIDs, taskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var file_id uuid.UUID
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const taskCounts = `-- name: TaskCounts :many
SELECT t.id,
    (SELECT count(*) FROM tasks s WHERE s.parent_id = t.id AND s.archived_at IS NULL)::integer AS subtasks,
    (SELECT count(*) FROM tasks s JOIN board_statuses st ON st.id = s.status_id
        WHERE s.parent_id = t.id AND s.archived_at IS NULL AND st.type IN ('completed', 'cancelled'))::integer AS subtasks_done,
    (SELECT count(*) FROM messages m WHERE m.room_id = t.room_id AND m.deleted_at IS NULL)::integer AS comments,
    (SELECT count(*) FROM task_attachments a WHERE a.task_id = t.id)::integer AS attachments,
    (SELECT count(*) FROM task_checklist_items ci WHERE ci.task_id = t.id)::integer AS checklist_total,
    (SELECT count(*) FROM task_checklist_items ci WHERE ci.task_id = t.id AND ci.done)::integer AS checklist_done,
    (SELECT count(*) FROM task_git_links g WHERE g.task_id = t.id)::integer AS git_links
FROM tasks t WHERE t.id = ANY($1::uuid[])
`

type TaskCountsRow struct {
	ID             uuid.UUID
	Subtasks       int32
	SubtasksDone   int32
	Comments       int32
	Attachments    int32
	ChecklistTotal int32
	ChecklistDone  int32
	GitLinks       int32
}

// Per task: live subtasks and finished ones, live comments, attachments, checklist items and
// done ones (ADR-0058 §2), Git links (ADR-0060).
func (q *Queries) TaskCounts(ctx context.Context, taskIds []uuid.UUID) ([]TaskCountsRow, error) {
	rows, err := q.db.Query(ctx, taskCounts, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskCountsRow{}
	for rows.Next() {
		var i TaskCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Subtasks,
			&i.SubtasksDone,
			&i.Comments,
			&i.Attachments,
			&i.ChecklistTotal,
			&i.ChecklistDone,
			&i.GitLinks,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchTask = `-- name: TouchTask :exec
UPDATE tasks SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchTask, id)
	return err
}

const unreadTaskIDs = `-- name: UnreadTaskIDs :many
SELECT t.id, t.board_id FROM task_subscribers s
JOIN tasks t ON t.id = s.task_id AND t.archived_at IS NULL
JOIN board_statuses st ON st.id = t.status_id AND st.type NOT IN ('completed', 'cancelled')
JOIN boards b ON b.id = t.board_id AND b.archived_at IS NULL AND b.workspace_id = $1
WHERE s.user_id = $2 AND s.notified_at IS NOT NULL AND (s.seen_at IS NULL OR s.notified_at > s.seen_at)
ORDER BY s.notified_at DESC
LIMIT 999
`

type UnreadTaskIDsParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type UnreadTaskIDsRow struct {
	ID      uuid.UUID
	BoardID uuid.UUID
}

// Open tasks with something unseen for the user on live boards of the workspace (≤ 999); the
// caller keeps those on boards the user sees. Closed ones are left out: the badge counts what
// «Мои задачи» lists (GET /api/me/tasks?open=1), a closed task keeps its own unread mark.
func (q *Queries) UnreadTaskIDs(ctx context.Context, arg UnreadTaskIDsParams) ([]UnreadTaskIDsRow, error) {
	rows, err := q.db.Query(ctx, unreadTaskIDs, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnreadTaskIDsRow{}
	for rows.Next() {
		var i UnreadTaskIDsRow
		if err := rows.Scan(&i.ID, &i.BoardID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unsetTaskWatcher = `-- name: UnsetTaskWatcher :one
WITH upd AS (
    UPDATE task_subscribers SET watcher = false WHERE task_id = $1 AND user_id = $2 AND watcher
    RETURNING 1
)
SELECT EXISTS (SELECT 1 FROM upd)::boolean
`

type UnsetTaskWatcherParams struct {
	TaskID uuid.UUID
	UserID uuid.UUID
}

// Removes the watcher role (the subscription stays); false when the user was not a watcher.
func (q *Queries) UnsetTaskWatcher(ctx context.Context, arg UnsetTaskWatcherParams) (bool, error) {
	row := q.db.QueryRow(ctx, unsetTaskWatcher, arg.TaskID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const updateBoard = `-- name: UpdateBoard :one
UPDATE boards SET
    name              = coalesce($1, name),
    key               = coalesce($2, key),
    emoji             = coalesce($3, emoji),
    icon_file_id      = CASE WHEN $4::boolean THEN $5::uuid ELSE icon_file_id END,
    description       = coalesce($6, description),
    is_private        = coalesce($7, is_private),
    auto_archive_days = coalesce($8, auto_archive_days),
    default_view_id   = CASE WHEN $9::boolean THEN $10::uuid ELSE default_view_id END,
    restricted        = coalesce($11, restricted),
    approval_notify_delay_seconds = coalesce($12, approval_notify_delay_seconds)
WHERE id = $13
RETURNING id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds
`

type UpdateBoardParams struct {
	Name                       *string
	Key                        *string
	Emoji                      *string
	SetIcon                    bool
	IconFileID                 *uuid.UUID
	Description                *string
	IsPrivate                  *bool
	AutoArchiveDays            *int32
	SetDefaultView             bool
	DefaultViewID              *uuid.UUID
	Restricted                 *bool
	ApprovalNotifyDelaySeconds *int32
	ID                         uuid.UUID
}

func (q *Queries) UpdateBoard(ctx context.Context, arg UpdateBoardParams) (Board, error) {
	row := q.db.QueryRow(ctx, updateBoard,
		arg.Name,
		arg.Key,
		arg.Emoji,
		arg.SetIcon,
		arg.IconFileID,
		arg.Description,
		arg.IsPrivate,
		arg.AutoArchiveDays,
		arg.SetDefaultView,
		arg.DefaultViewID,
		arg.Restricted,
		arg.ApprovalNotifyDelaySeconds,
		arg.ID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const updateBoardLabel = `-- name: UpdateBoardLabel :one
UPDATE board_labels SET
    name  = coalesce($1, name),
    color = coalesce($2, color)
WHERE id = $3 AND board_id = $4
RETURNING id, board_id, name, color, position
`

type UpdateBoardLabelParams struct {
	Name    *string
	Color   *int32
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) UpdateBoardLabel(ctx context.Context, arg UpdateBoardLabelParams) (BoardLabel, error) {
	row := q.db.QueryRow(ctx, updateBoardLabel,
		arg.Name,
		arg.Color,
		arg.ID,
		arg.BoardID,
	)
	var i BoardLabel
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Color,
		&i.Position,
	)
	return i, err
}

const updateBoardMilestone = `-- name: UpdateBoardMilestone :one
UPDATE board_milestones SET
    name   = coalesce($1, name),
    due_on = CASE WHEN $2::boolean THEN $3::date ELSE due_on END
WHERE id = $4 AND board_id = $5
RETURNING id, board_id, name, due_on, position
`

type UpdateBoardMilestoneParams struct {
	Name    *string
	SetDue  bool
	DueOn   pgtype.Date
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) UpdateBoardMilestone(ctx context.Context, arg UpdateBoardMilestoneParams) (BoardMilestone, error) {
	row := q.db.QueryRow(ctx, updateBoardMilestone,
		arg.Name,
		arg.SetDue,
		arg.DueOn,
		arg.ID,
		arg.BoardID,
	)
	var i BoardMilestone
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.DueOn,
		&i.Position,
	)
	return i, err
}

const updateBoardStatus = `-- name: UpdateBoardStatus :one
UPDATE board_statuses SET
    name  = coalesce($1, name),
    type  = coalesce($2, type),
    color = coalesce($3, color)
WHERE id = $4 AND board_id = $5
RETURNING id, board_id, name, type, color, position, is_default
`

type UpdateBoardStatusParams struct {
	Name    *string
	Type    *string
	Color   *int32
	ID      uuid.UUID
	BoardID uuid.UUID
}

func (q *Queries) UpdateBoardStatus(ctx context.Context, arg UpdateBoardStatusParams) (BoardStatus, error) {
	row := q.db.QueryRow(ctx, updateBoardStatus,
		arg.Name,
		arg.Type,
		arg.Color,
		arg.ID,
		arg.BoardID,
	)
	var i BoardStatus
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Type,
		&i.Color,
		&i.Position,
		&i.IsDefault,
	)
	return i, err
}

const updateBoardView = `-- name: UpdateBoardView :one
UPDATE board_views SET
    name     = coalesce($1, name),
    kind     = coalesce($2, kind),
    filter   = coalesce($3, filter),
    group_by = coalesce($4, group_by),
    sort     = coalesce($5, sort),
    shared   = coalesce($6, shared),
    position = coalesce($7, position)
WHERE id = $8
RETURNING id, board_id, name, kind, filter, group_by, sort, shared, created_by, position, created_at
`

type UpdateBoardViewParams struct {
	Name     *string
	Kind     *string
	Filter   []byte
	GroupBy  *string
	Sort     *string
	Shared   *bool
	Position *int32
	ID       uuid.UUID
}

func (q *Queries) UpdateBoardView(ctx context.Context, arg UpdateBoardViewParams) (BoardView, error) {
	row := q.db.QueryRow(ctx, updateBoardView,
		arg.Name,
		arg.Kind,
		arg.Filter,
		arg.GroupBy,
		arg.Sort,
		arg.Shared,
		arg.Position,
		arg.ID,
	)
	var i BoardView
	err := row.Scan(
		&i.ID,
		&i.BoardID,
		&i.Name,
		&i.Kind,
		&i.Filter,
		&i.GroupBy,
		&i.Sort,
		&i.Shared,
		&i.CreatedBy,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const updateTaskFields = `-- name: UpdateTaskFields :exec
UPDATE tasks SET
    title = $1, description = $2, status_id = $3,
    priority = $4, estimate = $5, start_on = $6,
    due_on = $7, parent_id = $8, milestone_id = $9,
    task_milestone_id = $10, position = $11,
    started_at = $12, completed_at = $13, completed_by = $14, updated_at = now()
WHERE id = $15
`

type UpdateTaskFieldsParams struct {
	Title           string
	Description     string
	StatusID        uuid.UUID
	Priority        int16
	Estimate        *int16
	StartOn         pgtype.Date
	DueOn           pgtype.Date
	ParentID        *uuid.UUID
	MilestoneID     *uuid.UUID
	TaskMilestoneID *uuid.UUID
	Position        float64
	StartedAt       *time.Time
	CompletedAt     *time.Time
	CompletedBy     *uuid.UUID
	ID              uuid.UUID
}

// Writes the whole mutable row (internal/boards computes the new values).
func (q *Queries) UpdateTaskFields(ctx context.Context, arg UpdateTaskFieldsParams) error {
	_, err := q.db.Exec(ctx, updateTaskFields,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.Estimate,
		arg.StartOn,
		arg.DueOn,
		arg.ParentID,
		arg.MilestoneID,
		arg.TaskMilestoneID,
		arg.Position,
		arg.StartedAt,
		arg.CompletedAt,
		arg.CompletedBy,
		arg.ID,
	)
	return err
}
