// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: board_categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countBoardCategories = `-- name: CountBoardCategories :one
SELECT count(*)::integer FROM board_categories WHERE workspace_id = $1
`

func (q *Queries) CountBoardCategories(ctx context.Context, workspaceID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBoardCategories, workspaceID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBoardCategory = `-- name: CreateBoardCategory :one
INSERT INTO board_categories (workspace_id, name, position)
VALUES ($1, $2,
        coalesce($3::integer,
                 (SELECT coalesce(max(position) + 1, 0) FROM board_categories WHERE workspace_id = $1)))
RETURNING id, workspace_id, name, position, created_at
`

type CreateBoardCategoryParams struct {
	WorkspaceID uuid.UUID
	Name        string
	Position    *int32
}

// position NULL = last. Serialize with LockBoards (count limit, positions).
func (q *Queries) CreateBoardCategory(ctx context.Context, arg CreateBoardCategoryParams) (BoardCategory, error) {
	row := q.db.QueryRow(ctx, createBoardCategory, arg.WorkspaceID, arg.Name, arg.Position)
	var i BoardCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBoardCategory = `-- name: DeleteBoardCategory :many
WITH base AS (
    SELECT coalesce(max(b.position) + 1, 0) AS p FROM boards b
    WHERE b.workspace_id = (SELECT c.workspace_id FROM board_categories c WHERE c.id = $1::uuid)
      AND b.category_id IS NULL
), ordered AS (
    SELECT b.id, row_number() OVER (ORDER BY b.position, b.id) - 1 AS n FROM boards b
    WHERE b.category_id = $1::uuid
), moved AS (
    UPDATE boards SET category_id = NULL, position = base.p + ordered.n
    FROM base, ordered
    WHERE boards.id = ordered.id
    RETURNING boards.id
), gone AS (
    DELETE FROM board_categories WHERE board_categories.id = $1::uuid
)
SELECT id FROM moved
`

// Deletes a category; returns the boards that were in it (live and archived). They move to
// «без категории» after the boards already there, in their order: no position ties.
func (q *Queries) DeleteBoardCategory(ctx context.Context, id uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteBoardCategory, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBoardCategory = `-- name: GetBoardCategory :one
SELECT id, workspace_id, name, position, created_at FROM board_categories WHERE id = $1
`

func (q *Queries) GetBoardCategory(ctx context.Context, id uuid.UUID) (BoardCategory, error) {
	row := q.db.QueryRow(ctx, getBoardCategory, id)
	var i BoardCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const listBoardCategories = `-- name: ListBoardCategories :many

SELECT id, workspace_id, name, position, created_at FROM board_categories WHERE workspace_id = $1 ORDER BY position, id
`

// ADR-0058 §1: categories of the boards list (separate from room_categories).
func (q *Queries) ListBoardCategories(ctx context.Context, workspaceID uuid.UUID) ([]BoardCategory, error) {
	rows, err := q.db.Query(ctx, listBoardCategories, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BoardCategory{}
	for rows.Next() {
		var i BoardCategory
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Position,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBoardCategoryPosition = `-- name: SetBoardCategoryPosition :one
UPDATE board_categories SET position = $1
WHERE id = $2 AND workspace_id = $3
RETURNING id, workspace_id, name, position, created_at
`

type SetBoardCategoryPositionParams struct {
	Position    int32
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) SetBoardCategoryPosition(ctx context.Context, arg SetBoardCategoryPositionParams) (BoardCategory, error) {
	row := q.db.QueryRow(ctx, setBoardCategoryPosition, arg.Position, arg.ID, arg.WorkspaceID)
	var i BoardCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}

const setBoardPlacement = `-- name: SetBoardPlacement :one
UPDATE boards SET position = $1, category_id = $2
WHERE id = $3 AND workspace_id = $4::uuid
RETURNING id, workspace_id, name, key, emoji, icon_file_id, description, is_private, position, next_number, auto_archive_days, default_view_id, created_by, created_at, archived_at, restricted, category_id, disabled_features, estimate_scale, approval_notify_delay_seconds
`

type SetBoardPlacementParams struct {
	Position    int32
	CategoryID  *uuid.UUID
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

// Puts a board into a category of its workspace (NULL = none) at a position (boards/order,
// PUT /boards/{id}/position with category_id).
func (q *Queries) SetBoardPlacement(ctx context.Context, arg SetBoardPlacementParams) (Board, error) {
	row := q.db.QueryRow(ctx, setBoardPlacement,
		arg.Position,
		arg.CategoryID,
		arg.ID,
		arg.WorkspaceID,
	)
	var i Board
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Key,
		&i.Emoji,
		&i.IconFileID,
		&i.Description,
		&i.IsPrivate,
		&i.Position,
		&i.NextNumber,
		&i.AutoArchiveDays,
		&i.DefaultViewID,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.Restricted,
		&i.CategoryID,
		&i.DisabledFeatures,
		&i.EstimateScale,
		&i.ApprovalNotifyDelaySeconds,
	)
	return i, err
}

const updateBoardCategory = `-- name: UpdateBoardCategory :one
UPDATE board_categories SET
    name     = coalesce($1, name),
    position = coalesce($2, position)
WHERE id = $3
RETURNING id, workspace_id, name, position, created_at
`

type UpdateBoardCategoryParams struct {
	Name     *string
	Position *int32
	ID       uuid.UUID
}

func (q *Queries) UpdateBoardCategory(ctx context.Context, arg UpdateBoardCategoryParams) (BoardCategory, error) {
	row := q.db.QueryRow(ctx, updateBoardCategory, arg.Name, arg.Position, arg.ID)
	var i BoardCategory
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Position,
		&i.CreatedAt,
	)
	return i, err
}
