// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dms.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDMMembers = `-- name: AddDMMembers :exec
INSERT INTO dm_members (room_id, user_id)
SELECT $1::uuid, u FROM unnest($2::uuid[]) AS u
`

type AddDMMembersParams struct {
	RoomID  uuid.UUID
	UserIds []uuid.UUID
}

func (q *Queries) AddDMMembers(ctx context.Context, arg AddDMMembersParams) error {
	_, err := q.db.Exec(ctx, addDMMembers, arg.RoomID, arg.UserIds)
	return err
}

const clearDM = `-- name: ClearDM :one
INSERT INTO dm_state (user_id, room_id, cleared_before)
VALUES ($1, $2, uuidv7())
ON CONFLICT (user_id, room_id) DO UPDATE SET archived_at = NULL, cleared_before = uuidv7()
RETURNING user_id, room_id, archived_at, cleared_before
`

type ClearDMParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

// «Удалить чат» for the user only: hides the history up to now (uuidv7() orders after every
// message created before) and takes the DM out of the archive.
func (q *Queries) ClearDM(ctx context.Context, arg ClearDMParams) (DmState, error) {
	row := q.db.QueryRow(ctx, clearDM, arg.UserID, arg.RoomID)
	var i DmState
	err := row.Scan(
		&i.UserID,
		&i.RoomID,
		&i.ArchivedAt,
		&i.ClearedBefore,
	)
	return i, err
}

const createDMRoom = `-- name: CreateDMRoom :one
INSERT INTO rooms (workspace_id, type, name, dm_key)
VALUES (NULL, 'dm', 'dm', $1)
ON CONFLICT (dm_key) WHERE dm_key IS NOT NULL DO NOTHING
RETURNING id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval, expires_at, created_by
`

// No row = a concurrent request created the pair's DM first (read it with GetDMByKey).
func (q *Queries) CreateDMRoom(ctx context.Context, dmKey *string) (Room, error) {
	row := q.db.QueryRow(ctx, createDMRoom, dmKey)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDMByKey = `-- name: GetDMByKey :one

SELECT id, workspace_id, type, name, topic, position, is_private, audio_bitrate_kbps, max_stream_preset, max_streams, created_at, archived_at, category_id, user_limit, voice_status, camera_limit, dm_key, allow_recording, restricted, emoji, guest_approval, expires_at, created_by FROM rooms WHERE dm_key = $1 AND archived_at IS NULL
`

// Direct messages (ADR-0020). A DM is a room with type 'dm', no workspace and two rows in
// dm_members; dm_key = least(a, b) || ':' || greatest(a, b) makes it unique per pair.
func (q *Queries) GetDMByKey(ctx context.Context, dmKey *string) (Room, error) {
	row := q.db.QueryRow(ctx, getDMByKey, dmKey)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Name,
		&i.Topic,
		&i.Position,
		&i.IsPrivate,
		&i.AudioBitrateKbps,
		&i.MaxStreamPreset,
		&i.MaxStreams,
		&i.CreatedAt,
		&i.ArchivedAt,
		&i.CategoryID,
		&i.UserLimit,
		&i.VoiceStatus,
		&i.CameraLimit,
		&i.DmKey,
		&i.AllowRecording,
		&i.Restricted,
		&i.Emoji,
		&i.GuestApproval,
		&i.ExpiresAt,
		&i.CreatedBy,
	)
	return i, err
}

const getDMClearedBefore = `-- name: GetDMClearedBefore :one
SELECT coalesce((SELECT ds.cleared_before FROM dm_state ds WHERE ds.user_id = $1 AND ds.room_id = $2),
                '00000000-0000-0000-0000-000000000000'::uuid)::uuid AS cleared_before
`

type GetDMClearedBeforeParams struct {
	UserID uuid.UUID
	RoomID uuid.UUID
}

// The user's «Удалить чат» mark in a room (the zero uuid = none, also for rooms that are no DM).
func (q *Queries) GetDMClearedBefore(ctx context.Context, arg GetDMClearedBeforeParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDMClearedBefore, arg.UserID, arg.RoomID)
	var cleared_before uuid.UUID
	err := row.Scan(&cleared_before)
	return cleared_before, err
}

const getDMPeer = `-- name: GetDMPeer :one
SELECT p.user_id FROM dm_members me
JOIN dm_members p ON p.room_id = me.room_id AND p.user_id <> me.user_id
JOIN rooms r ON r.id = me.room_id AND r.archived_at IS NULL
WHERE me.room_id = $1 AND me.user_id = $2
`

type GetDMPeerParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

// The other participant of a DM the user is in (no row = not a participant / not a DM).
func (q *Queries) GetDMPeer(ctx context.Context, arg GetDMPeerParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getDMPeer, arg.RoomID, arg.UserID)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const isAvatar = `-- name: IsAvatar :one
SELECT EXISTS (SELECT 1 FROM users WHERE avatar_file_id = $1)::boolean
`

func (q *Queries) IsAvatar(ctx context.Context, avatarFileID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAvatar, avatarFileID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listDMCandidates = `-- name: ListDMCandidates :many
SELECT u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days FROM users u
WHERE u.id <> $1 AND NOT u.is_guest AND u.disabled_at IS NULL
  AND EXISTS (
    SELECT 1 FROM workspace_members a
    JOIN workspace_members b ON b.workspace_id = a.workspace_id AND b.user_id = u.id AND b.role <> 'guest'
    WHERE a.user_id = $1 AND a.role <> 'guest'
      AND ($2::text = '' OR u.display_name ILIKE '%' || $2::text || '%'
           OR b.nickname ILIKE '%' || $2::text || '%')
  )
ORDER BY lower(u.display_name), u.id
LIMIT $3
`

type ListDMCandidatesParams struct {
	UserID uuid.UUID
	Q      string
	Lim    int32
}

// Users the caller may start a DM with: full members of a workspace the caller is a full
// member of; not guest accounts, not disabled, not the caller. q matches the display name
// or a workspace nickname (case-insensitive substring; ” = everyone).
func (q *Queries) ListDMCandidates(ctx context.Context, arg ListDMCandidatesParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listDMCandidates, arg.UserID, arg.Q, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.DisplayName,
			&i.AvatarFileID,
			&i.StatusText,
			&i.Settings,
			&i.CreatedAt,
			&i.DisabledAt,
			&i.StatusEmoji,
			&i.StatusExpiresAt,
			&i.IsGuest,
			&i.GuestExpiresAt,
			&i.Timezone,
			&i.EmailVerifiedAt,
			&i.PendingEmail,
			&i.Locale,
			&i.PresenceStatus,
			&i.PresenceUntil,
			&i.IsBot,
			&i.BirthdayDay,
			&i.BirthdayMonth,
			&i.BirthdayYear,
			&i.BirthdayHidden,
			&i.EventReminders,
			&i.EventRemindersDnd,
			&i.StorageQuotaBytes,
			&i.WorkStartMin,
			&i.WorkEndMin,
			&i.WorkDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMs = `-- name: ListDMs :many
SELECT r.id AS room_id, r.created_at AS room_created_at,
       u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days,
       rs.last_read_message_id,
       (lm.id IS NOT NULL)::boolean AS has_messages,
       coalesce(lm.id, r.id)::uuid AS last_message_id,
       coalesce(lm.created_at, r.created_at)::timestamptz AS last_message_at,
       coalesce(lm.author_id, me.user_id)::uuid AS last_author_id,
       coalesce(lm.preview, '')::text AS last_preview,
       coalesce(lm.attachments, 0)::integer AS last_attachments,
       coalesce(lm.sticker_emoji, '')::text AS last_sticker_emoji,
       (SELECT count(*) FROM (
           SELECT 1 FROM messages m
           WHERE m.room_id = r.id AND m.deleted_at IS NULL AND m.author_id <> me.user_id
             AND m.id > greatest(coalesce(rs.last_read_message_id, '00000000-0000-0000-0000-000000000000'::uuid),
                                 coalesce(ds.cleared_before, '00000000-0000-0000-0000-000000000000'::uuid))
           LIMIT 999) x)::integer AS unread_count,
       ds.archived_at, ds.cleared_before,
       prs.last_read_message_id AS peer_read_message_id
FROM dm_members me
JOIN rooms r ON r.id = me.room_id AND r.archived_at IS NULL
JOIN dm_members p ON p.room_id = me.room_id AND p.user_id <> me.user_id
JOIN users u ON u.id = p.user_id
LEFT JOIN read_states rs ON rs.user_id = me.user_id AND rs.room_id = r.id
LEFT JOIN read_states prs ON prs.user_id = p.user_id AND prs.room_id = r.id AND NOT u.is_bot
LEFT JOIN dm_state ds ON ds.user_id = me.user_id AND ds.room_id = r.id
LEFT JOIN LATERAL (
    SELECT m.id, m.created_at, m.author_id, left(m.content, 200) AS preview,
           (SELECT count(*) FROM message_attachments ma WHERE ma.message_id = m.id) AS attachments,
           (SELECT st.emoji FROM stickers st WHERE st.id = m.sticker_id) AS sticker_emoji
    FROM messages m
    WHERE m.room_id = r.id AND m.deleted_at IS NULL
      AND m.id > coalesce(ds.cleared_before, '00000000-0000-0000-0000-000000000000'::uuid)
    ORDER BY m.id DESC
    LIMIT 1
) lm ON true
WHERE me.user_id = $1
  AND ($2::uuid IS NULL OR r.id = $2::uuid)
ORDER BY coalesce(lm.id, r.id) DESC
LIMIT $3
`

type ListDMsParams struct {
	UserID uuid.UUID
	RoomID *uuid.UUID
	Lim    int32
}

type ListDMsRow struct {
	RoomID            uuid.UUID
	RoomCreatedAt     time.Time
	User              User
	LastReadMessageID *uuid.UUID
	HasMessages       bool
	LastMessageID     uuid.UUID
	LastMessageAt     time.Time
	LastAuthorID      uuid.UUID
	LastPreview       string
	LastAttachments   int32
	LastStickerEmoji  string
	UnreadCount       int32
	ArchivedAt        *time.Time
	ClearedBefore     *uuid.UUID
	PeerReadMessageID *uuid.UUID
}

// The user's DMs, most recent activity first: the peer, the read marker, the newest live
// message and the unread count (others' live messages after the marker, capped at 999; a
// DM never read counts from its start). Every lookup is an index probe per DM
// (dm_members_user_id_idx, messages_live_room_id_idx). room_id NULL = all DMs. Without
// messages (has_messages false) last_message_* are the room's id and creation time. The
// newest message's author, first 200 characters and attachment count are the list preview
// (DmSummary.last_message): the client needs no history request per DM. The user's own
// dm_state (item 51): archived_at, and cleared_before — the preview and the unread count start
// after it (the DM stays listed; the client hides a cleared DM without newer messages).
// peer_read_message_id: the peer's read marker for read receipts (docs/09 #92; a primary-key
// probe; NULL for a bot peer).
func (q *Queries) ListDMs(ctx context.Context, arg ListDMsParams) ([]ListDMsRow, error) {
	rows, err := q.db.Query(ctx, listDMs, arg.UserID, arg.RoomID, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDMsRow{}
	for rows.Next() {
		var i ListDMsRow
		if err := rows.Scan(
			&i.RoomID,
			&i.RoomCreatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.LastReadMessageID,
			&i.HasMessages,
			&i.LastMessageID,
			&i.LastMessageAt,
			&i.LastAuthorID,
			&i.LastPreview,
			&i.LastAttachments,
			&i.LastStickerEmoji,
			&i.UnreadCount,
			&i.ArchivedAt,
			&i.ClearedBefore,
			&i.PeerReadMessageID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSearchPersonalRooms = `-- name: ListSearchPersonalRooms :many
SELECT r.id, r.type, ds.cleared_before FROM dm_members d
JOIN rooms r ON r.id = d.room_id AND r.archived_at IS NULL AND r.type IN ('dm', 'notes')
LEFT JOIN dm_state ds ON ds.user_id = d.user_id AND ds.room_id = r.id
WHERE d.user_id = $1
`

type ListSearchPersonalRoomsRow struct {
	ID            uuid.UUID
	Type          string
	ClearedBefore *uuid.UUID
}

// The user's live DMs and notes shelves with their «Удалить чат» mark (unified search, ADR-0062:
// the user is a participant, as perm.ReadRoom checks for these rooms).
func (q *Queries) ListSearchPersonalRooms(ctx context.Context, userID uuid.UUID) ([]ListSearchPersonalRoomsRow, error) {
	rows, err := q.db.Query(ctx, listSearchPersonalRooms, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSearchPersonalRoomsRow{}
	for rows.Next() {
		var i ListSearchPersonalRoomsRow
		if err := rows.Scan(&i.ID, &i.Type, &i.ClearedBefore); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDMArchived = `-- name: SetDMArchived :one
INSERT INTO dm_state (user_id, room_id, archived_at)
VALUES ($1, $2, CASE WHEN $3::boolean THEN now() END)
ON CONFLICT (user_id, room_id) DO UPDATE
SET archived_at = CASE WHEN $3::boolean THEN coalesce(dm_state.archived_at, now()) END
RETURNING user_id, room_id, archived_at, cleared_before
`

type SetDMArchivedParams struct {
	UserID   uuid.UUID
	RoomID   uuid.UUID
	Archived bool
}

// Moves the user's DM to / out of their archive (archiving again keeps the first time).
func (q *Queries) SetDMArchived(ctx context.Context, arg SetDMArchivedParams) (DmState, error) {
	row := q.db.QueryRow(ctx, setDMArchived, arg.UserID, arg.RoomID, arg.Archived)
	var i DmState
	err := row.Scan(
		&i.UserID,
		&i.RoomID,
		&i.ArchivedAt,
		&i.ClearedBefore,
	)
	return i, err
}

const shareWorkspace = `-- name: ShareWorkspace :one
SELECT EXISTS (
    SELECT 1 FROM workspace_members a
    JOIN workspace_members b ON b.workspace_id = a.workspace_id AND b.user_id = $1
    WHERE a.user_id = $2 AND a.role <> 'guest' AND b.role <> 'guest'
)::boolean
`

type ShareWorkspaceParams struct {
	OtherID uuid.UUID
	UserID  uuid.UUID
}

// Both users are full members (not the guest role) of at least one common workspace.
func (q *Queries) ShareWorkspace(ctx context.Context, arg ShareWorkspaceParams) (bool, error) {
	row := q.db.QueryRow(ctx, shareWorkspace, arg.OtherID, arg.UserID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const unarchiveDMForRecipients = `-- name: UnarchiveDMForRecipients :many
UPDATE dm_state SET archived_at = NULL
WHERE room_id = $1 AND user_id <> $2 AND archived_at IS NOT NULL
RETURNING user_id, room_id, archived_at, cleared_before
`

type UnarchiveDMForRecipientsParams struct {
	RoomID   uuid.UUID
	AuthorID uuid.UUID
}

// A new message takes the DM out of the archive of the participants other than its author.
func (q *Queries) UnarchiveDMForRecipients(ctx context.Context, arg UnarchiveDMForRecipientsParams) ([]DmState, error) {
	rows, err := q.db.Query(ctx, unarchiveDMForRecipients, arg.RoomID, arg.AuthorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DmState{}
	for rows.Next() {
		var i DmState
		if err := rows.Scan(
			&i.UserID,
			&i.RoomID,
			&i.ArchivedAt,
			&i.ClearedBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unattachedUserBytes = `-- name: UnattachedUserBytes :one
SELECT coalesce(sum(f.size), 0)::bigint FROM files f
WHERE f.uploader_id = $1 AND f.workspace_id IS NULL
  AND NOT EXISTS (SELECT 1 FROM message_attachments ma WHERE ma.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_file_id = f.id)
`

// Bytes a user uploaded for DMs (user-scoped, not an avatar) not attached to a message yet.
func (q *Queries) UnattachedUserBytes(ctx context.Context, uploaderID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, unattachedUserBytes, uploaderID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}
