// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_invites.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const acceptEmailInvite = `-- name: AcceptEmailInvite :exec
UPDATE email_invites SET accepted_at = now() WHERE id = $1
`

func (q *Queries) AcceptEmailInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, acceptEmailInvite, id)
	return err
}

const createEmailInvite = `-- name: CreateEmailInvite :one
INSERT INTO email_invites (workspace_id, email, role, invited_by, invite_id, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at
`

type CreateEmailInviteParams struct {
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	InvitedBy   uuid.UUID
	InviteID    uuid.UUID
	ExpiresAt   time.Time
}

func (q *Queries) CreateEmailInvite(ctx context.Context, arg CreateEmailInviteParams) (EmailInvite, error) {
	row := q.db.QueryRow(ctx, createEmailInvite,
		arg.WorkspaceID,
		arg.Email,
		arg.Role,
		arg.InvitedBy,
		arg.InviteID,
		arg.ExpiresAt,
	)
	var i EmailInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviteID,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailInvite = `-- name: GetEmailInvite :one
SELECT id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at FROM email_invites WHERE id = $1 AND workspace_id = $2
`

type GetEmailInviteParams struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
}

func (q *Queries) GetEmailInvite(ctx context.Context, arg GetEmailInviteParams) (EmailInvite, error) {
	row := q.db.QueryRow(ctx, getEmailInvite, arg.ID, arg.WorkspaceID)
	var i EmailInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviteID,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getEmailInviteByInvite = `-- name: GetEmailInviteByInvite :one
SELECT id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at FROM email_invites WHERE invite_id = $1
`

func (q *Queries) GetEmailInviteByInvite(ctx context.Context, inviteID uuid.UUID) (EmailInvite, error) {
	row := q.db.QueryRow(ctx, getEmailInviteByInvite, inviteID)
	var i EmailInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviteID,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPendingEmailInvite = `-- name: GetPendingEmailInvite :one
SELECT id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at FROM email_invites WHERE workspace_id = $1 AND email = $2 AND accepted_at IS NULL
`

type GetPendingEmailInviteParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

func (q *Queries) GetPendingEmailInvite(ctx context.Context, arg GetPendingEmailInviteParams) (EmailInvite, error) {
	row := q.db.QueryRow(ctx, getPendingEmailInvite, arg.WorkspaceID, arg.Email)
	var i EmailInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviteID,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const hasPendingEmailInvite = `-- name: HasPendingEmailInvite :one
SELECT EXISTS (
  SELECT 1 FROM email_invites
  WHERE email = $1 AND accepted_at IS NULL AND expires_at > now()
)::bool
`

// Whether a live invitation waits for an address (ADR-0065: its join needs the confirmation).
func (q *Queries) HasPendingEmailInvite(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingEmailInvite, email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listEmailInvites = `-- name: ListEmailInvites :many
SELECT id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at FROM email_invites WHERE workspace_id = $1 AND accepted_at IS NULL ORDER BY created_at DESC
`

func (q *Queries) ListEmailInvites(ctx context.Context, workspaceID uuid.UUID) ([]EmailInvite, error) {
	rows, err := q.db.Query(ctx, listEmailInvites, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailInvite{}
	for rows.Next() {
		var i EmailInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.InviteID,
			&i.ExpiresAt,
			&i.LastSentAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupInvitee = `-- name: LookupInvitee :one

SELECT id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone, email_verified_at, pending_email, locale, presence_status, presence_until, is_bot, birthday_day, birthday_month, birthday_year, birthday_hidden, event_reminders, event_reminders_dnd, storage_quota_bytes, work_start_min, work_end_min, work_days, hide_message_text_in_notifications FROM users
WHERE email = $1 AND email_verified_at IS NOT NULL AND disabled_at IS NULL AND NOT is_guest
`

// ADR-0023: invitations by email.
// Verified, active, non-guest account with exactly this address (citext: case-insensitive).
func (q *Queries) LookupInvitee(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, lookupInvitee, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.PendingEmail,
		&i.Locale,
		&i.PresenceStatus,
		&i.PresenceUntil,
		&i.IsBot,
		&i.BirthdayDay,
		&i.BirthdayMonth,
		&i.BirthdayYear,
		&i.BirthdayHidden,
		&i.EventReminders,
		&i.EventRemindersDnd,
		&i.StorageQuotaBytes,
		&i.WorkStartMin,
		&i.WorkEndMin,
		&i.WorkDays,
		&i.HideMessageTextInNotifications,
	)
	return i, err
}

const pendingEmailInvitesFor = `-- name: PendingEmailInvitesFor :many
SELECT id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at FROM email_invites
WHERE email = $1 AND accepted_at IS NULL AND expires_at > now()
ORDER BY created_at
FOR UPDATE
`

// Live invitations of an address, locked for accepting them (auto-join after verification).
func (q *Queries) PendingEmailInvitesFor(ctx context.Context, email string) ([]EmailInvite, error) {
	rows, err := q.db.Query(ctx, pendingEmailInvitesFor, email)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EmailInvite{}
	for rows.Next() {
		var i EmailInvite
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Email,
			&i.Role,
			&i.InvitedBy,
			&i.InviteID,
			&i.ExpiresAt,
			&i.LastSentAt,
			&i.AcceptedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewEmailInvite = `-- name: RenewEmailInvite :one
UPDATE email_invites SET invite_id = $2, role = $3, invited_by = $4, expires_at = $5, last_sent_at = now()
WHERE id = $1
RETURNING id, workspace_id, email, role, invited_by, invite_id, expires_at, last_sent_at, accepted_at, created_at
`

type RenewEmailInviteParams struct {
	ID        uuid.UUID
	InviteID  uuid.UUID
	Role      string
	InvitedBy uuid.UUID
	ExpiresAt time.Time
}

// Sending again: a new link (the old invite row is deleted by the caller), new expiry.
func (q *Queries) RenewEmailInvite(ctx context.Context, arg RenewEmailInviteParams) (EmailInvite, error) {
	row := q.db.QueryRow(ctx, renewEmailInvite,
		arg.ID,
		arg.InviteID,
		arg.Role,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i EmailInvite
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Email,
		&i.Role,
		&i.InvitedBy,
		&i.InviteID,
		&i.ExpiresAt,
		&i.LastSentAt,
		&i.AcceptedAt,
		&i.CreatedAt,
	)
	return i, err
}

const useInvite = `-- name: UseInvite :exec
UPDATE workspace_invites SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) UseInvite(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, useInvite, id)
	return err
}
