// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const bumpEventSequence = `-- name: BumpEventSequence :one
UPDATE events SET sequence = sequence + 1, updated_at = now() WHERE id = $1 RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

func (q *Queries) BumpEventSequence(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, bumpEventSequence, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const cancelEvent = `-- name: CancelEvent :one
UPDATE events SET cancelled_at = now(), sequence = sequence + 1, updated_at = now()
WHERE id = $1 AND cancelled_at IS NULL
RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

func (q *Queries) CancelEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, cancelEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const claimEventReminder = `-- name: ClaimEventReminder :execrows
INSERT INTO event_reminders_sent (event_id, occurrence_at, user_id, minutes) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type ClaimEventReminderParams struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	UserID       uuid.UUID
	Minutes      int16
}

func (q *Queries) ClaimEventReminder(ctx context.Context, arg ClaimEventReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimEventReminder,
		arg.EventID,
		arg.OccurrenceAt,
		arg.UserID,
		arg.Minutes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimEventRoomSignal = `-- name: ClaimEventRoomSignal :execrows
INSERT INTO event_room_signals (event_id, occurrence_at, kind) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type ClaimEventRoomSignalParams struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	Kind         string
}

func (q *Queries) ClaimEventRoomSignal(ctx context.Context, arg ClaimEventRoomSignalParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimEventRoomSignal, arg.EventID, arg.OccurrenceAt, arg.Kind)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimExternalReminder = `-- name: ClaimExternalReminder :execrows
INSERT INTO external_reminders_sent (user_id, uid, occurrence_at, minutes) VALUES ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
`

type ClaimExternalReminderParams struct {
	UserID       uuid.UUID
	Uid          string
	OccurrenceAt time.Time
	Minutes      int16
}

// An imported event's reminder (ADR-0045 amendment 3), once per user, event, occurrence, minutes.
func (q *Queries) ClaimExternalReminder(ctx context.Context, arg ClaimExternalReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimExternalReminder,
		arg.UserID,
		arg.Uid,
		arg.OccurrenceAt,
		arg.Minutes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEventRoomInvite = `-- name: CreateEventRoomInvite :one
INSERT INTO room_invites (room_id, code, created_by, expires_at, max_uses, allow_guests, allow_bits, not_before, event_id)
VALUES ($1, $2, $3, $4, 1, true, $5, $6, $7)
RETURNING id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only
`

type CreateEventRoomInviteParams struct {
	RoomID    uuid.UUID
	Code      string
	CreatedBy uuid.UUID
	ExpiresAt *time.Time
	AllowBits int64
	NotBefore *time.Time
	EventID   *uuid.UUID
}

func (q *Queries) CreateEventRoomInvite(ctx context.Context, arg CreateEventRoomInviteParams) (RoomInvite, error) {
	row := q.db.QueryRow(ctx, createEventRoomInvite,
		arg.RoomID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.AllowBits,
		arg.NotBefore,
		arg.EventID,
	)
	var i RoomInvite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowGuests,
		&i.AllowBits,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NotBefore,
		&i.EventID,
		&i.RequireApproval,
		&i.MembersOnly,
	)
	return i, err
}

const deleteEventAttendee = `-- name: DeleteEventAttendee :exec
DELETE FROM event_attendees WHERE event_id = $1 AND user_id = $2
`

type DeleteEventAttendeeParams struct {
	EventID uuid.UUID
	UserID  *uuid.UUID
}

func (q *Queries) DeleteEventAttendee(ctx context.Context, arg DeleteEventAttendeeParams) error {
	_, err := q.db.Exec(ctx, deleteEventAttendee, arg.EventID, arg.UserID)
	return err
}

const deleteExternalAttendee = `-- name: DeleteExternalAttendee :exec
DELETE FROM event_attendees WHERE event_id = $1 AND email = $2
`

type DeleteExternalAttendeeParams struct {
	EventID uuid.UUID
	Email   *string
}

func (q *Queries) DeleteExternalAttendee(ctx context.Context, arg DeleteExternalAttendeeParams) error {
	_, err := q.db.Exec(ctx, deleteExternalAttendee, arg.EventID, arg.Email)
	return err
}

const deleteOldEventSignals = `-- name: DeleteOldEventSignals :exec
WITH r AS (DELETE FROM event_reminders_sent WHERE event_reminders_sent.sent_at < $1),
x AS (DELETE FROM external_reminders_sent WHERE external_reminders_sent.sent_at < $1)
DELETE FROM event_room_signals WHERE event_room_signals.sent_at < $1
`

func (q *Queries) DeleteOldEventSignals(ctx context.Context, before time.Time) error {
	_, err := q.db.Exec(ctx, deleteOldEventSignals, before)
	return err
}

const endEventAt = `-- name: EndEventAt :one
UPDATE events SET ends_at = $1, sequence = sequence + 1, updated_at = now()
WHERE id = $2 AND cancelled_at IS NULL AND starts_at < $1 AND ends_at > $1
RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

type EndEventAtParams struct {
	At time.Time
	ID uuid.UUID
}

// A running one-off meeting ends at `at` (its room closed).
func (q *Queries) EndEventAt(ctx context.Context, arg EndEventAtParams) (Event, error) {
	row := q.db.QueryRow(ctx, endEventAt, arg.At, arg.ID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const followRoomExpiryEvents = `-- name: FollowRoomExpiryEvents :many
UPDATE events SET ends_at = $1, sequence = sequence + 1, updated_at = now()
WHERE room_id = $2 AND cancelled_at IS NULL AND rrule IS NULL
  AND ends_at = $3 AND starts_at < $1
RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

type FollowRoomExpiryEventsParams struct {
	EndsAt    time.Time
	RoomID    *uuid.UUID
	OldEndsAt time.Time
}

// A temporary room was extended or shortened (ADR-0044): its one-off meetings that ended with the
// room (ends_at = the old end) follow the new end; a meeting moved by hand is left alone.
func (q *Queries) FollowRoomExpiryEvents(ctx context.Context, arg FollowRoomExpiryEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, followRoomExpiryEvents, arg.EndsAt, arg.RoomID, arg.OldEndsAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getEventForUpdate = `-- name: GetEventForUpdate :one
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events WHERE id = $1 AND cancelled_at IS NULL FOR UPDATE
`

func (q *Queries) GetEventForUpdate(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEventForUpdate, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const getRoomInvite = `-- name: GetRoomInvite :one
SELECT id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only FROM room_invites WHERE id = $1
`

func (q *Queries) GetRoomInvite(ctx context.Context, id uuid.UUID) (RoomInvite, error) {
	row := q.db.QueryRow(ctx, getRoomInvite, id)
	var i RoomInvite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowGuests,
		&i.AllowBits,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NotBefore,
		&i.EventID,
		&i.RequireApproval,
		&i.MembersOnly,
	)
	return i, err
}

const getUserEventReminders = `-- name: GetUserEventReminders :one
SELECT event_reminders, event_reminders_dnd FROM users WHERE id = $1
`

type GetUserEventRemindersRow struct {
	EventReminders    []int16
	EventRemindersDnd bool
}

func (q *Queries) GetUserEventReminders(ctx context.Context, id uuid.UUID) (GetUserEventRemindersRow, error) {
	row := q.db.QueryRow(ctx, getUserEventReminders, id)
	var i GetUserEventRemindersRow
	err := row.Scan(&i.EventReminders, &i.EventRemindersDnd)
	return i, err
}

const insertEvent = `-- name: InsertEvent :one

INSERT INTO events (workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

type InsertEventParams struct {
	WorkspaceID uuid.UUID
	RoomID      *uuid.UUID
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	AllDay      bool
	Tz          string
	OrganizerID uuid.UUID
	Record      bool
	Rrule       *string
	UntilAt     *time.Time
}

// Workspace calendar (ADR-0038).
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, insertEvent,
		arg.WorkspaceID,
		arg.RoomID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Tz,
		arg.OrganizerID,
		arg.Record,
		arg.Rrule,
		arg.UntilAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const insertEventAttendee = `-- name: InsertEventAttendee :exec
INSERT INTO event_attendees (event_id, user_id, email, required, status, responded_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertEventAttendeeParams struct {
	EventID     uuid.UUID
	UserID      *uuid.UUID
	Email       *string
	Required    bool
	Status      string
	RespondedAt *time.Time
}

func (q *Queries) InsertEventAttendee(ctx context.Context, arg InsertEventAttendeeParams) error {
	_, err := q.db.Exec(ctx, insertEventAttendee,
		arg.EventID,
		arg.UserID,
		arg.Email,
		arg.Required,
		arg.Status,
		arg.RespondedAt,
	)
	return err
}

const insertEventException = `-- name: InsertEventException :execrows
INSERT INTO event_exceptions (event_id, occurrence_at) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type InsertEventExceptionParams struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
}

func (q *Queries) InsertEventException(ctx context.Context, arg InsertEventExceptionParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEventException, arg.EventID, arg.OccurrenceAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertEventRecording = `-- name: InsertEventRecording :execrows
INSERT INTO event_recordings (event_id, occurrence_at, recording_id) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type InsertEventRecordingParams struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	RecordingID  uuid.UUID
}

func (q *Queries) InsertEventRecording(ctx context.Context, arg InsertEventRecordingParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertEventRecording, arg.EventID, arg.OccurrenceAt, arg.RecordingID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDueEvents = `-- name: ListDueEvents :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE cancelled_at IS NULL AND starts_at < $1 AND (until_at IS NULL OR until_at > $2)
ORDER BY starts_at, id
LIMIT 5000
`

type ListDueEventsParams struct {
	To   time.Time
	From *time.Time
}

// Events that may have an occurrence starting or ending in [from, to): the sweeper's input.
func (q *Queries) ListDueEvents(ctx context.Context, arg ListDueEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listDueEvents, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventAttendees = `-- name: ListEventAttendees :many
SELECT event_id, user_id, email, required, status, responded_at, invite_id FROM event_attendees WHERE event_id = ANY($1::uuid[])
ORDER BY event_id, (user_id IS NULL), user_id, email
`

func (q *Queries) ListEventAttendees(ctx context.Context, eventIds []uuid.UUID) ([]EventAttendee, error) {
	rows, err := q.db.Query(ctx, listEventAttendees, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventAttendee{}
	for rows.Next() {
		var i EventAttendee
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.Email,
			&i.Required,
			&i.Status,
			&i.RespondedAt,
			&i.InviteID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventExceptions = `-- name: ListEventExceptions :many
SELECT event_id, occurrence_at FROM event_exceptions WHERE event_id = ANY($1::uuid[]) ORDER BY event_id, occurrence_at
`

func (q *Queries) ListEventExceptions(ctx context.Context, eventIds []uuid.UUID) ([]EventException, error) {
	rows, err := q.db.Query(ctx, listEventExceptions, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventException{}
	for rows.Next() {
		var i EventException
		if err := rows.Scan(&i.EventID, &i.OccurrenceAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventRecordings = `-- name: ListEventRecordings :many
SELECT event_id, occurrence_at, recording_id FROM event_recordings WHERE event_id = ANY($1::uuid[])
`

func (q *Queries) ListEventRecordings(ctx context.Context, eventIds []uuid.UUID) ([]EventRecording, error) {
	rows, err := q.db.Query(ctx, listEventRecordings, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventRecording{}
	for rows.Next() {
		var i EventRecording
		if err := rows.Scan(&i.EventID, &i.OccurrenceAt, &i.RecordingID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventUsers = `-- name: ListEventUsers :many
SELECT id, display_name, email, email_verified_at, locale, is_bot, is_guest, timezone FROM users
WHERE id = ANY($1::uuid[])
`

type ListEventUsersRow struct {
	ID              uuid.UUID
	DisplayName     string
	Email           *string
	EmailVerifiedAt *time.Time
	Locale          *string
	IsBot           bool
	IsGuest         bool
	Timezone        *string
}

// Users for event cards and mail: names, emails (verified or not), locales.
func (q *Queries) ListEventUsers(ctx context.Context, ids []uuid.UUID) ([]ListEventUsersRow, error) {
	rows, err := q.db.Query(ctx, listEventUsers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventUsersRow{}
	for rows.Next() {
		var i ListEventUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.Locale,
			&i.IsBot,
			&i.IsGuest,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByIDs = `-- name: ListEventsByIDs :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events WHERE id = ANY($1::uuid[])
`

// Events of a search page (unified search, ADR-0062); the caller keeps its own order.
func (q *Queries) ListEventsByIDs(ctx context.Context, ids []uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForRecording = `-- name: ListEventsForRecording :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE room_id = $1 AND organizer_id = $2 AND cancelled_at IS NULL
  AND starts_at < $3 AND (until_at IS NULL OR until_at > $4)
`

type ListEventsForRecordingParams struct {
	RoomID      *uuid.UUID
	OrganizerID uuid.UUID
	To          time.Time
	From        *time.Time
}

// Live events of the room organized by the user that may have an occurrence around `at`.
func (q *Queries) ListEventsForRecording(ctx context.Context, arg ListEventsForRecordingParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsForRecording,
		arg.RoomID,
		arg.OrganizerID,
		arg.To,
		arg.From,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReminderTargets = `-- name: ListReminderTargets :many
SELECT e.id AS event_id, u.id AS user_id, u.event_reminders, u.event_reminders_dnd,
       coalesce(a.status, 'accepted')::text AS status
FROM events e
JOIN users u ON (u.id = e.organizer_id
                 OR u.id IN (SELECT ea.user_id FROM event_attendees ea WHERE ea.event_id = e.id AND ea.user_id IS NOT NULL))
JOIN workspace_members m ON m.workspace_id = e.workspace_id AND m.user_id = u.id AND m.role <> 'guest'
LEFT JOIN event_attendees a ON a.event_id = e.id AND a.user_id = u.id
WHERE e.id = ANY($1::uuid[]) AND u.disabled_at IS NULL AND NOT u.is_bot
`

type ListReminderTargetsRow struct {
	EventID           uuid.UUID
	UserID            uuid.UUID
	EventReminders    []int16
	EventRemindersDnd bool
	Status            string
}

// Attendees and organizers of the events who are still non-guest members of the event's
// workspace, with their reminder settings and answer (an organizer not on the list: accepted).
func (q *Queries) ListReminderTargets(ctx context.Context, eventIds []uuid.UUID) ([]ListReminderTargetsRow, error) {
	rows, err := q.db.Query(ctx, listReminderTargets, eventIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReminderTargetsRow{}
	for rows.Next() {
		var i ListReminderTargetsRow
		if err := rows.Scan(
			&i.EventID,
			&i.UserID,
			&i.EventReminders,
			&i.EventRemindersDnd,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomEventsNear = `-- name: ListRoomEventsNear :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE workspace_id = ANY($1::uuid[]) AND cancelled_at IS NULL AND room_id IS NOT NULL
  AND starts_at < $2 AND (until_at IS NULL OR until_at > $3)
ORDER BY starts_at, id
`

type ListRoomEventsNearParams struct {
	WorkspaceIds []uuid.UUID
	To           time.Time
	From         *time.Time
}

// Live events with a room in the workspaces that may have an occurrence around now (the room
// badge of the snapshots of a READY, ADR-0038 §6).
func (q *Queries) ListRoomEventsNear(ctx context.Context, arg ListRoomEventsNearParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRoomEventsNear, arg.WorkspaceIds, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomLiveEvents = `-- name: ListRoomLiveEvents :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE room_id = $1 AND cancelled_at IS NULL AND rrule IS NULL AND ends_at > $2
ORDER BY starts_at
FOR UPDATE
`

type ListRoomLiveEventsParams struct {
	RoomID *uuid.UUID
	Now    time.Time
}

// One-off meetings of a room that have not ended at `now` (ADR-0044: a temporary room closes
// them).
func (q *Queries) ListRoomLiveEvents(ctx context.Context, arg ListRoomLiveEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRoomLiveEvents, arg.RoomID, arg.Now)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserEvents = `-- name: ListUserEvents :many
SELECT e.id, e.workspace_id, e.room_id, e.title, e.description, e.starts_at, e.ends_at, e.all_day, e.tz, e.organizer_id, e.record, e.rrule, e.until_at, e.sequence, e.created_at, e.updated_at, e.cancelled_at FROM events e
JOIN workspace_members m ON m.workspace_id = e.workspace_id AND m.user_id = $1 AND m.role <> 'guest'
WHERE e.cancelled_at IS NULL
  AND e.starts_at < $2 AND (e.until_at IS NULL OR e.until_at > $3)
  AND (e.organizer_id = $1
       OR EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = e.id AND a.user_id = $1))
ORDER BY e.starts_at, e.id
`

type ListUserEventsParams struct {
	UserID uuid.UUID
	To     time.Time
	From   *time.Time
}

// Live events the user organizes or attends in workspaces where they are a member (not a
// guest), possibly overlapping [from, to).
func (q *Queries) ListUserEvents(ctx context.Context, arg ListUserEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listUserEvents, arg.UserID, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceEvents = `-- name: ListWorkspaceEvents :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE workspace_id = $1 AND cancelled_at IS NULL
  AND starts_at < $2 AND (until_at IS NULL OR until_at > $3)
ORDER BY starts_at, id
`

type ListWorkspaceEventsParams struct {
	WorkspaceID uuid.UUID
	To          time.Time
	From        *time.Time
}

// Live events of a workspace with an occurrence possibly overlapping [from, to).
func (q *Queries) ListWorkspaceEvents(ctx context.Context, arg ListWorkspaceEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listWorkspaceEvents, arg.WorkspaceID, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveEventRoomInvite = `-- name: MoveEventRoomInvite :exec
UPDATE room_invites SET not_before = $2, expires_at = $3 WHERE id = $1 AND revoked_at IS NULL
`

type MoveEventRoomInviteParams struct {
	ID        uuid.UUID
	NotBefore *time.Time
	ExpiresAt *time.Time
}

// A meeting moved in time: its unused guest link follows the new window.
func (q *Queries) MoveEventRoomInvite(ctx context.Context, arg MoveEventRoomInviteParams) error {
	_, err := q.db.Exec(ctx, moveEventRoomInvite, arg.ID, arg.NotBefore, arg.ExpiresAt)
	return err
}

const revokeEventRoomInvites = `-- name: RevokeEventRoomInvites :exec
UPDATE room_invites SET revoked_at = now()
WHERE event_id = $1 AND revoked_at IS NULL
  AND ($2::uuid[] IS NULL OR id = ANY($2::uuid[]))
`

type RevokeEventRoomInvitesParams struct {
	EventID *uuid.UUID
	Ids     []uuid.UUID
}

// Guest links of the event (all, or only those of the given ids).
func (q *Queries) RevokeEventRoomInvites(ctx context.Context, arg RevokeEventRoomInvitesParams) error {
	_, err := q.db.Exec(ctx, revokeEventRoomInvites, arg.EventID, arg.Ids)
	return err
}

const setEventAttendeeInvite = `-- name: SetEventAttendeeInvite :exec
UPDATE event_attendees SET invite_id = $3 WHERE event_id = $1 AND email = $2
`

type SetEventAttendeeInviteParams struct {
	EventID  uuid.UUID
	Email    *string
	InviteID *uuid.UUID
}

func (q *Queries) SetEventAttendeeInvite(ctx context.Context, arg SetEventAttendeeInviteParams) error {
	_, err := q.db.Exec(ctx, setEventAttendeeInvite, arg.EventID, arg.Email, arg.InviteID)
	return err
}

const setEventAttendeeStatus = `-- name: SetEventAttendeeStatus :one
UPDATE event_attendees SET status = $3, responded_at = now()
WHERE event_id = $1 AND user_id = $2
RETURNING event_id, user_id, email, required, status, responded_at, invite_id
`

type SetEventAttendeeStatusParams struct {
	EventID uuid.UUID
	UserID  *uuid.UUID
	Status  string
}

func (q *Queries) SetEventAttendeeStatus(ctx context.Context, arg SetEventAttendeeStatusParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, setEventAttendeeStatus, arg.EventID, arg.UserID, arg.Status)
	var i EventAttendee
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Email,
		&i.Required,
		&i.Status,
		&i.RespondedAt,
		&i.InviteID,
	)
	return i, err
}

const setExternalAttendeeStatus = `-- name: SetExternalAttendeeStatus :one
UPDATE event_attendees SET status = $3, responded_at = CASE WHEN status = $3 THEN responded_at ELSE now() END
WHERE event_id = $1 AND email = $2
RETURNING event_id, user_id, email, required, status, responded_at, invite_id
`

type SetExternalAttendeeStatusParams struct {
	EventID uuid.UUID
	Email   *string
	Status  string
}

func (q *Queries) SetExternalAttendeeStatus(ctx context.Context, arg SetExternalAttendeeStatusParams) (EventAttendee, error) {
	row := q.db.QueryRow(ctx, setExternalAttendeeStatus, arg.EventID, arg.Email, arg.Status)
	var i EventAttendee
	err := row.Scan(
		&i.EventID,
		&i.UserID,
		&i.Email,
		&i.Required,
		&i.Status,
		&i.RespondedAt,
		&i.InviteID,
	)
	return i, err
}

const setUserEventReminders = `-- name: SetUserEventReminders :one
UPDATE users SET event_reminders = $2, event_reminders_dnd = $3 WHERE id = $1
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone, email_verified_at, pending_email, locale, presence_status, presence_until, is_bot, birthday_day, birthday_month, birthday_year, birthday_hidden, event_reminders, event_reminders_dnd, storage_quota_bytes, work_start_min, work_end_min, work_days, hide_message_text_in_notifications, username, phone
`

type SetUserEventRemindersParams struct {
	ID                uuid.UUID
	EventReminders    []int16
	EventRemindersDnd bool
}

func (q *Queries) SetUserEventReminders(ctx context.Context, arg SetUserEventRemindersParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserEventReminders, arg.ID, arg.EventReminders, arg.EventRemindersDnd)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.PendingEmail,
		&i.Locale,
		&i.PresenceStatus,
		&i.PresenceUntil,
		&i.IsBot,
		&i.BirthdayDay,
		&i.BirthdayMonth,
		&i.BirthdayYear,
		&i.BirthdayHidden,
		&i.EventReminders,
		&i.EventRemindersDnd,
		&i.StorageQuotaBytes,
		&i.WorkStartMin,
		&i.WorkEndMin,
		&i.WorkDays,
		&i.HideMessageTextInNotifications,
		&i.Username,
		&i.Phone,
	)
	return i, err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET room_id = $2, title = $3, description = $4, starts_at = $5, ends_at = $6, all_day = $7,
    tz = $8, record = $9, rrule = $10, until_at = $11, sequence = sequence + $12::integer, updated_at = now()
WHERE id = $1
RETURNING id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at
`

type UpdateEventParams struct {
	ID          uuid.UUID
	RoomID      *uuid.UUID
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	AllDay      bool
	Tz          string
	Record      bool
	Rrule       *string
	UntilAt     *time.Time
	Bump        int32
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.RoomID,
		arg.Title,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.AllDay,
		arg.Tz,
		arg.Record,
		arg.Rrule,
		arg.UntilAt,
		arg.Bump,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Tz,
		&i.OrganizerID,
		&i.Record,
		&i.Rrule,
		&i.UntilAt,
		&i.Sequence,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CancelledAt,
	)
	return i, err
}

const updateEventAttendeeRequired = `-- name: UpdateEventAttendeeRequired :exec
UPDATE event_attendees SET required = $3 WHERE event_id = $1 AND user_id = $2
`

type UpdateEventAttendeeRequiredParams struct {
	EventID  uuid.UUID
	UserID   *uuid.UUID
	Required bool
}

func (q *Queries) UpdateEventAttendeeRequired(ctx context.Context, arg UpdateEventAttendeeRequiredParams) error {
	_, err := q.db.Exec(ctx, updateEventAttendeeRequired, arg.EventID, arg.UserID, arg.Required)
	return err
}

const updateExternalAttendeeRequired = `-- name: UpdateExternalAttendeeRequired :exec
UPDATE event_attendees SET required = $3 WHERE event_id = $1 AND email = $2
`

type UpdateExternalAttendeeRequiredParams struct {
	EventID  uuid.UUID
	Email    *string
	Required bool
}

func (q *Queries) UpdateExternalAttendeeRequired(ctx context.Context, arg UpdateExternalAttendeeRequiredParams) error {
	_, err := q.db.Exec(ctx, updateExternalAttendeeRequired, arg.EventID, arg.Email, arg.Required)
	return err
}
