// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: freebusy.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimCalDavPushes = `-- name: ClaimCalDavPushes :many
UPDATE caldav_pushes SET next_at = now() + $1::interval
WHERE (user_id, event_id) IN (
    SELECT p.user_id, p.event_id FROM caldav_pushes p
    WHERE p.next_at <= now()
    ORDER BY p.next_at
    LIMIT $2
    FOR UPDATE SKIP LOCKED
)
RETURNING user_id, event_id, gen, attempts, next_at, error, created_at
`

type ClaimCalDavPushesParams struct {
	Lease pgtype.Interval
	Lim   int32
}

// Takes due pushes: next_at moves one lease ahead (a crashed worker's rows come back).
func (q *Queries) ClaimCalDavPushes(ctx context.Context, arg ClaimCalDavPushesParams) ([]CaldavPush, error) {
	rows, err := q.db.Query(ctx, claimCalDavPushes, arg.Lease, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaldavPush{}
	for rows.Next() {
		var i CaldavPush
		if err := rows.Scan(
			&i.UserID,
			&i.EventID,
			&i.Gen,
			&i.Attempts,
			&i.NextAt,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteCalDavAccount = `-- name: DeleteCalDavAccount :execrows
DELETE FROM caldav_accounts WHERE user_id = $1
`

func (q *Queries) DeleteCalDavAccount(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalDavAccount, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteCalDavPush = `-- name: DeleteCalDavPush :exec
DELETE FROM caldav_pushes WHERE user_id = $1 AND event_id = $2 AND gen = $3
`

type DeleteCalDavPushParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Gen     int64
}

func (q *Queries) DeleteCalDavPush(ctx context.Context, arg DeleteCalDavPushParams) error {
	_, err := q.db.Exec(ctx, deleteCalDavPush, arg.UserID, arg.EventID, arg.Gen)
	return err
}

const deleteCalDavPushes = `-- name: DeleteCalDavPushes :exec
DELETE FROM caldav_pushes WHERE user_id = $1
`

func (q *Queries) DeleteCalDavPushes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCalDavPushes, userID)
	return err
}

const deleteExternalBusy = `-- name: DeleteExternalBusy :exec
DELETE FROM external_busy WHERE user_id = $1
`

func (q *Queries) DeleteExternalBusy(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteExternalBusy, userID)
	return err
}

const deleteMyExternalOccurrence = `-- name: DeleteMyExternalOccurrence :execrows
DELETE FROM external_busy WHERE user_id = $1 AND uid = $2 AND starts_at = $3
`

type DeleteMyExternalOccurrenceParams struct {
	UserID   uuid.UUID
	Uid      string
	StartsAt time.Time
}

func (q *Queries) DeleteMyExternalOccurrence(ctx context.Context, arg DeleteMyExternalOccurrenceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMyExternalOccurrence, arg.UserID, arg.Uid, arg.StartsAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMyExternalSeries = `-- name: DeleteMyExternalSeries :execrows
DELETE FROM external_busy WHERE user_id = $1 AND uid = $2
`

type DeleteMyExternalSeriesParams struct {
	UserID uuid.UUID
	Uid    string
}

func (q *Queries) DeleteMyExternalSeries(ctx context.Context, arg DeleteMyExternalSeriesParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMyExternalSeries, arg.UserID, arg.Uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueCalDavPushes = `-- name: EnqueueCalDavPushes :execrows
INSERT INTO caldav_pushes (user_id, event_id)
SELECT a.user_id, $1::uuid FROM caldav_accounts a
WHERE a.user_id = ANY($2::uuid[]) AND a.push AND a.calendar_href IS NOT NULL
ON CONFLICT (user_id, event_id) DO UPDATE SET gen = caldav_pushes.gen + 1, attempts = 0, next_at = now(), error = ''
`

type EnqueueCalDavPushesParams struct {
	EventID uuid.UUID
	Ids     []uuid.UUID
}

// Queues the event for those of the users who push to a chosen calendar; a pending row gets
// the newer change (gen + 1, due now, attempts from zero).
func (q *Queries) EnqueueCalDavPushes(ctx context.Context, arg EnqueueCalDavPushesParams) (int64, error) {
	result, err := q.db.Exec(ctx, enqueueCalDavPushes, arg.EventID, arg.Ids)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalDavAccount = `-- name: GetCalDavAccount :one
SELECT user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind FROM caldav_accounts WHERE user_id = $1
`

func (q *Queries) GetCalDavAccount(ctx context.Context, userID uuid.UUID) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, getCalDavAccount, userID)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}

const getMyExternalEvent = `-- name: GetMyExternalEvent :one
SELECT user_id, uid, starts_at, ends_at, all_day, summary, location, attendees, organizer, url, href, etag, recurring, web_url FROM external_busy
WHERE user_id = $1 AND uid = $2 AND starts_at = $3 AND href = $4::text
LIMIT 1
`

type GetMyExternalEventParams struct {
	UserID   uuid.UUID
	Uid      string
	StartsAt time.Time
	Href     string
}

// One imported occurrence of the caller (ADR-0045, amendment 1): a delete names it by uid, start and href.
func (q *Queries) GetMyExternalEvent(ctx context.Context, arg GetMyExternalEventParams) (ExternalBusy, error) {
	row := q.db.QueryRow(ctx, getMyExternalEvent,
		arg.UserID,
		arg.Uid,
		arg.StartsAt,
		arg.Href,
	)
	var i ExternalBusy
	err := row.Scan(
		&i.UserID,
		&i.Uid,
		&i.StartsAt,
		&i.EndsAt,
		&i.AllDay,
		&i.Summary,
		&i.Location,
		&i.Attendees,
		&i.Organizer,
		&i.Url,
		&i.Href,
		&i.Etag,
		&i.Recurring,
		&i.WebUrl,
	)
	return i, err
}

const insertExternalBusy = `-- name: InsertExternalBusy :exec
INSERT INTO external_busy (user_id, uid, starts_at, ends_at, all_day, summary, location, attendees, organizer, url,
    href, etag, recurring, web_url)
SELECT $1::uuid, unnest($2::text[]), unnest($3::timestamptz[]),
    unnest($4::timestamptz[]), unnest($5::boolean[]), unnest($6::text[]),
    unnest($7::text[]), unnest($8::text[])::jsonb, unnest($9::text[]),
    unnest($10::text[]), unnest($11::text[]), unnest($12::text[]),
    unnest($13::boolean[]), unnest($14::text[])
`

type InsertExternalBusyParams struct {
	UserID     uuid.UUID
	Uids       []string
	Starts     []time.Time
	Ends       []time.Time
	AllDays    []bool
	Summaries  []string
	Locations  []string
	Attendees  []string
	Organizers []string
	Urls       []string
	Hrefs      []string
	Etags      []string
	Recurrings []bool
	WebUrls    []string
}

func (q *Queries) InsertExternalBusy(ctx context.Context, arg InsertExternalBusyParams) error {
	_, err := q.db.Exec(ctx, insertExternalBusy,
		arg.UserID,
		arg.Uids,
		arg.Starts,
		arg.Ends,
		arg.AllDays,
		arg.Summaries,
		arg.Locations,
		arg.Attendees,
		arg.Organizers,
		arg.Urls,
		arg.Hrefs,
		arg.Etags,
		arg.Recurrings,
		arg.WebUrls,
	)
	return err
}

const listBusyEvents = `-- name: ListBusyEvents :many
SELECT e.id, e.workspace_id, e.room_id, e.title, e.description, e.starts_at, e.ends_at, e.all_day, e.tz, e.organizer_id, e.record, e.rrule, e.until_at, e.sequence, e.created_at, e.updated_at, e.cancelled_at FROM events e
WHERE e.cancelled_at IS NULL
  AND e.starts_at < $1 AND (e.until_at IS NULL OR e.until_at > $2)
  AND (e.organizer_id = ANY($3::uuid[])
       OR EXISTS (SELECT 1 FROM event_attendees a WHERE a.event_id = e.id AND a.user_id = ANY($3::uuid[])))
ORDER BY e.starts_at, e.id
`

type ListBusyEventsParams struct {
	To   time.Time
	From *time.Time
	Ids  []uuid.UUID
}

// Live events the users organize or attend (any workspace), possibly overlapping [from, to).
func (q *Queries) ListBusyEvents(ctx context.Context, arg ListBusyEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listBusyEvents, arg.To, arg.From, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueCalDavImports = `-- name: ListDueCalDavImports :many
SELECT user_id FROM caldav_accounts
WHERE import AND calendar_href IS NOT NULL AND (last_sync_at IS NULL OR last_sync_at < $1)
ORDER BY last_sync_at NULLS FIRST
LIMIT $2
`

type ListDueCalDavImportsParams struct {
	Before *time.Time
	Lim    int32
}

// Accounts whose import is due (never synced, or last synced before `before`).
func (q *Queries) ListDueCalDavImports(ctx context.Context, arg ListDueCalDavImportsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listDueCalDavImports, arg.Before, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueExternalReminders = `-- name: ListDueExternalReminders :many
SELECT b.user_id, b.uid, b.starts_at, b.ends_at, b.summary, b.location, b.attendees, b.organizer, b.url,
    b.href, b.recurring, b.web_url, m.minutes::int AS minutes, u.event_reminders_dnd, a.username AS login
FROM caldav_accounts a
JOIN users u ON u.id = a.user_id
CROSS JOIN LATERAL unnest(u.event_reminders) AS m (minutes)
JOIN external_busy b ON b.user_id = a.user_id
WHERE a.remind AND a.import AND a.calendar_href IS NOT NULL
  AND u.disabled_at IS NULL AND NOT u.is_bot AND NOT u.is_guest AND NOT b.all_day
  AND b.starts_at > $1::timestamptz AND b.starts_at <= $2::timestamptz
  AND b.starts_at - m.minutes * interval '1 minute' <= $1::timestamptz
  AND b.starts_at - m.minutes * interval '1 minute' > $3::timestamptz
ORDER BY b.user_id, b.starts_at, b.uid, m.minutes
`

type ListDueExternalRemindersParams struct {
	Now   time.Time
	To    time.Time
	Since time.Time
}

type ListDueExternalRemindersRow struct {
	UserID            uuid.UUID
	Uid               string
	StartsAt          time.Time
	EndsAt            time.Time
	Summary           string
	Location          string
	Attendees         []byte
	Organizer         string
	Url               string
	Href              string
	Recurring         bool
	WebUrl            string
	Minutes           int32
	EventRemindersDnd bool
	Login             string
}

// Reminders of imported events due at now (ADR-0045 amendment 3): accounts that remind and import
// a chosen calendar, enabled people; timed (not all-day) events starting in (now, to] whose moment
// (start − one of the user's event_reminders) is in (since, now] — since = now − the grace.
func (q *Queries) ListDueExternalReminders(ctx context.Context, arg ListDueExternalRemindersParams) ([]ListDueExternalRemindersRow, error) {
	rows, err := q.db.Query(ctx, listDueExternalReminders, arg.Now, arg.To, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDueExternalRemindersRow{}
	for rows.Next() {
		var i ListDueExternalRemindersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Uid,
			&i.StartsAt,
			&i.EndsAt,
			&i.Summary,
			&i.Location,
			&i.Attendees,
			&i.Organizer,
			&i.Url,
			&i.Href,
			&i.Recurring,
			&i.WebUrl,
			&i.Minutes,
			&i.EventRemindersDnd,
			&i.Login,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExternalBusy = `-- name: ListExternalBusy :many
SELECT b.user_id, b.uid, b.starts_at, b.ends_at, b.all_day, b.summary, b.location, b.attendees, b.organizer, b.url, b.href, b.etag, b.recurring, b.web_url, coalesce(a.share_level, 'busy')::text AS share_level FROM external_busy b
LEFT JOIN caldav_accounts a ON a.user_id = b.user_id
WHERE b.user_id = ANY($1::uuid[]) AND b.starts_at < $2 AND b.ends_at > $3
ORDER BY b.user_id, b.starts_at
`

type ListExternalBusyParams struct {
	Ids  []uuid.UUID
	To   time.Time
	From time.Time
}

type ListExternalBusyRow struct {
	ExternalBusy ExternalBusy
	ShareLevel   string
}

// With the owner's share_level (ADR-0045 §4): what of the details others may see.
func (q *Queries) ListExternalBusy(ctx context.Context, arg ListExternalBusyParams) ([]ListExternalBusyRow, error) {
	rows, err := q.db.Query(ctx, listExternalBusy, arg.Ids, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExternalBusyRow{}
	for rows.Next() {
		var i ListExternalBusyRow
		if err := rows.Scan(
			&i.ExternalBusy.UserID,
			&i.ExternalBusy.Uid,
			&i.ExternalBusy.StartsAt,
			&i.ExternalBusy.EndsAt,
			&i.ExternalBusy.AllDay,
			&i.ExternalBusy.Summary,
			&i.ExternalBusy.Location,
			&i.ExternalBusy.Attendees,
			&i.ExternalBusy.Organizer,
			&i.ExternalBusy.Url,
			&i.ExternalBusy.Href,
			&i.ExternalBusy.Etag,
			&i.ExternalBusy.Recurring,
			&i.ExternalBusy.WebUrl,
			&i.ShareLevel,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFreeBusyMembers = `-- name: ListFreeBusyMembers :many
SELECT u.id, u.timezone, u.work_start_min, u.work_end_min, u.work_days FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.user_id = ANY($2::uuid[]) AND m.role <> 'guest'
  AND NOT u.is_bot AND NOT u.is_guest AND u.disabled_at IS NULL
`

type ListFreeBusyMembersParams struct {
	WorkspaceID uuid.UUID
	Ids         []uuid.UUID
}

type ListFreeBusyMembersRow struct {
	ID           uuid.UUID
	Timezone     *string
	WorkStartMin int16
	WorkEndMin   int16
	WorkDays     []int16
}

// Members (not guests) of the workspace among ids that are people (not bots), enabled.
func (q *Queries) ListFreeBusyMembers(ctx context.Context, arg ListFreeBusyMembersParams) ([]ListFreeBusyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFreeBusyMembers, arg.WorkspaceID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFreeBusyMembersRow{}
	for rows.Next() {
		var i ListFreeBusyMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Timezone,
			&i.WorkStartMin,
			&i.WorkEndMin,
			&i.WorkDays,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyExternalEvents = `-- name: ListMyExternalEvents :many
SELECT user_id, uid, starts_at, ends_at, all_day, summary, location, attendees, organizer, url, href, etag, recurring, web_url FROM external_busy
WHERE user_id = $1 AND starts_at < $2 AND ends_at > $3
ORDER BY starts_at, ends_at, uid
`

type ListMyExternalEventsParams struct {
	UserID uuid.UUID
	To     time.Time
	From   time.Time
}

func (q *Queries) ListMyExternalEvents(ctx context.Context, arg ListMyExternalEventsParams) ([]ExternalBusy, error) {
	rows, err := q.db.Query(ctx, listMyExternalEvents, arg.UserID, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExternalBusy{}
	for rows.Next() {
		var i ExternalBusy
		if err := rows.Scan(
			&i.UserID,
			&i.Uid,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Summary,
			&i.Location,
			&i.Attendees,
			&i.Organizer,
			&i.Url,
			&i.Href,
			&i.Etag,
			&i.Recurring,
			&i.WebUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomBusyEvents = `-- name: ListRoomBusyEvents :many
SELECT id, workspace_id, room_id, title, description, starts_at, ends_at, all_day, tz, organizer_id, record, rrule, until_at, sequence, created_at, updated_at, cancelled_at FROM events
WHERE room_id = $1 AND cancelled_at IS NULL
  AND starts_at < $2 AND (until_at IS NULL OR until_at > $3)
ORDER BY starts_at, id
`

type ListRoomBusyEventsParams struct {
	RoomID *uuid.UUID
	To     time.Time
	From   *time.Time
}

// Live events of a room possibly overlapping [from, to).
func (q *Queries) ListRoomBusyEvents(ctx context.Context, arg ListRoomBusyEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRoomBusyEvents, arg.RoomID, arg.To, arg.From)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.AllDay,
			&i.Tz,
			&i.OrganizerID,
			&i.Record,
			&i.Rrule,
			&i.UntilAt,
			&i.Sequence,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCalDavAccount = `-- name: LockCalDavAccount :one
SELECT user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind FROM caldav_accounts WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) LockCalDavAccount(ctx context.Context, userID uuid.UUID) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, lockCalDavAccount, userID)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}

const matchMemberEmails = `-- name: MatchMemberEmails :many
SELECT u.id, lower(u.email)::text AS email FROM workspace_members m
JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.role <> 'guest' AND NOT u.is_bot AND NOT u.is_guest AND u.disabled_at IS NULL
  AND u.email_verified_at IS NOT NULL AND lower(u.email) = ANY($2::text[])
`

type MatchMemberEmailsParams struct {
	WorkspaceID uuid.UUID
	Emails      []string
}

type MatchMemberEmailsRow struct {
	ID    uuid.UUID
	Email string
}

// Members of the workspace (people, not guests; enabled) whose confirmed e-mail is one of emails
// (lower case) — attendees of external events (ADR-0045 §3, §4).
func (q *Queries) MatchMemberEmails(ctx context.Context, arg MatchMemberEmailsParams) ([]MatchMemberEmailsRow, error) {
	rows, err := q.db.Query(ctx, matchMemberEmails, arg.WorkspaceID, arg.Emails)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MatchMemberEmailsRow{}
	for rows.Next() {
		var i MatchMemberEmailsRow
		if err := rows.Scan(&i.ID, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const patchCalDavAccount = `-- name: PatchCalDavAccount :one
UPDATE caldav_accounts SET share_level = coalesce($2::text, share_level),
    remind = coalesce($3::boolean, remind), updated_at = now()
WHERE user_id = $1
RETURNING user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind
`

type PatchCalDavAccountParams struct {
	UserID     uuid.UUID
	ShareLevel *string
	Remind     *bool
}

// What colleagues see (ADR-0045 §2) and the reminders (amendment 3); NULL = unchanged.
func (q *Queries) PatchCalDavAccount(ctx context.Context, arg PatchCalDavAccountParams) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, patchCalDavAccount, arg.UserID, arg.ShareLevel, arg.Remind)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}

const retryCalDavPush = `-- name: RetryCalDavPush :exec
UPDATE caldav_pushes SET attempts = attempts + 1, next_at = $4, error = $5
WHERE user_id = $1 AND event_id = $2 AND gen = $3
`

type RetryCalDavPushParams struct {
	UserID  uuid.UUID
	EventID uuid.UUID
	Gen     int64
	NextAt  time.Time
	Error   string
}

func (q *Queries) RetryCalDavPush(ctx context.Context, arg RetryCalDavPushParams) error {
	_, err := q.db.Exec(ctx, retryCalDavPush,
		arg.UserID,
		arg.EventID,
		arg.Gen,
		arg.NextAt,
		arg.Error,
	)
	return err
}

const setCalDavError = `-- name: SetCalDavError :exec
UPDATE caldav_accounts SET last_error = $2 WHERE user_id = $1
`

type SetCalDavErrorParams struct {
	UserID    uuid.UUID
	LastError string
}

func (q *Queries) SetCalDavError(ctx context.Context, arg SetCalDavErrorParams) error {
	_, err := q.db.Exec(ctx, setCalDavError, arg.UserID, arg.LastError)
	return err
}

const setCalDavSynced = `-- name: SetCalDavSynced :one
UPDATE caldav_accounts SET last_sync_at = $2, last_error = $3 WHERE user_id = $1
RETURNING user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind
`

type SetCalDavSyncedParams struct {
	UserID     uuid.UUID
	LastSyncAt *time.Time
	LastError  string
}

func (q *Queries) SetCalDavSynced(ctx context.Context, arg SetCalDavSyncedParams) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, setCalDavSynced, arg.UserID, arg.LastSyncAt, arg.LastError)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}

const setUserWorkHours = `-- name: SetUserWorkHours :one

UPDATE users SET work_start_min = $2, work_end_min = $3, work_days = $4 WHERE id = $1
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone, email_verified_at, pending_email, locale, presence_status, presence_until, is_bot, birthday_day, birthday_month, birthday_year, birthday_hidden, event_reminders, event_reminders_dnd, storage_quota_bytes, work_start_min, work_end_min, work_days
`

type SetUserWorkHoursParams struct {
	ID           uuid.UUID
	WorkStartMin int16
	WorkEndMin   int16
	WorkDays     []int16
}

// Free / busy, working hours and CalDAV (ADR-0041).
func (q *Queries) SetUserWorkHours(ctx context.Context, arg SetUserWorkHoursParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserWorkHours,
		arg.ID,
		arg.WorkStartMin,
		arg.WorkEndMin,
		arg.WorkDays,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.PendingEmail,
		&i.Locale,
		&i.PresenceStatus,
		&i.PresenceUntil,
		&i.IsBot,
		&i.BirthdayDay,
		&i.BirthdayMonth,
		&i.BirthdayYear,
		&i.BirthdayHidden,
		&i.EventReminders,
		&i.EventRemindersDnd,
		&i.StorageQuotaBytes,
		&i.WorkStartMin,
		&i.WorkEndMin,
		&i.WorkDays,
	)
	return i, err
}

const updateCalDavAccount = `-- name: UpdateCalDavAccount :one
UPDATE caldav_accounts SET calendar_href = $2, import = $3, push = $4, last_error = '', updated_at = now()
WHERE user_id = $1
RETURNING user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind
`

type UpdateCalDavAccountParams struct {
	UserID       uuid.UUID
	CalendarHref *string
	Import       bool
	Push         bool
}

func (q *Queries) UpdateCalDavAccount(ctx context.Context, arg UpdateCalDavAccountParams) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, updateCalDavAccount,
		arg.UserID,
		arg.CalendarHref,
		arg.Import,
		arg.Push,
	)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}

const upsertCalDavAccount = `-- name: UpsertCalDavAccount :one
INSERT INTO caldav_accounts (user_id, url, username, secret_enc, calendars, calendar_href, import, push)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id) DO UPDATE SET url = EXCLUDED.url, username = EXCLUDED.username,
    secret_enc = EXCLUDED.secret_enc, calendars = EXCLUDED.calendars, calendar_href = EXCLUDED.calendar_href,
    import = EXCLUDED.import, push = EXCLUDED.push, last_sync_at = NULL, last_error = '', updated_at = now()
RETURNING user_id, url, username, secret_enc, calendars, calendar_href, import, push, last_sync_at, last_error, created_at, updated_at, share_level, remind
`

type UpsertCalDavAccountParams struct {
	UserID       uuid.UUID
	Url          string
	Username     string
	SecretEnc    []byte
	Calendars    []byte
	CalendarHref *string
	Import       bool
	Push         bool
}

func (q *Queries) UpsertCalDavAccount(ctx context.Context, arg UpsertCalDavAccountParams) (CaldavAccount, error) {
	row := q.db.QueryRow(ctx, upsertCalDavAccount,
		arg.UserID,
		arg.Url,
		arg.Username,
		arg.SecretEnc,
		arg.Calendars,
		arg.CalendarHref,
		arg.Import,
		arg.Push,
	)
	var i CaldavAccount
	err := row.Scan(
		&i.UserID,
		&i.Url,
		&i.Username,
		&i.SecretEnc,
		&i.Calendars,
		&i.CalendarHref,
		&i.Import,
		&i.Push,
		&i.LastSyncAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShareLevel,
		&i.Remind,
	)
	return i, err
}
