// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guests.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const anonymizeGuest = `-- name: AnonymizeGuest :exec
UPDATE users SET display_name = 'Гость (удалён)', status_text = '', status_emoji = '', status_expires_at = NULL,
    avatar_file_id = NULL, settings = '{}', guest_expires_at = NULL, disabled_at = now()
WHERE id = $1 AND is_guest
`

// Messages keep their author row; everything personal is dropped.
func (q *Queries) AnonymizeGuest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, anonymizeGuest, id)
	return err
}

const clearGuestExpiry = `-- name: ClearGuestExpiry :exec
UPDATE users SET guest_expires_at = NULL WHERE id = $1
`

func (q *Queries) ClearGuestExpiry(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearGuestExpiry, id)
	return err
}

const consumeRoomInvite = `-- name: ConsumeRoomInvite :one
UPDATE room_invites SET uses = uses + 1
WHERE id = $1 AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses = 0 OR uses < max_uses)
  AND (not_before IS NULL OR not_before <= now())
RETURNING id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only
`

func (q *Queries) ConsumeRoomInvite(ctx context.Context, id uuid.UUID) (RoomInvite, error) {
	row := q.db.QueryRow(ctx, consumeRoomInvite, id)
	var i RoomInvite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowGuests,
		&i.AllowBits,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NotBefore,
		&i.EventID,
		&i.RequireApproval,
		&i.MembersOnly,
	)
	return i, err
}

const createGuestUser = `-- name: CreateGuestUser :one
INSERT INTO users (email, password_hash, display_name, settings, is_guest, guest_expires_at)
VALUES (NULL, NULL, $1, $2, true, $3)
RETURNING id, email, password_hash, display_name, avatar_file_id, status_text, settings, created_at, disabled_at, status_emoji, status_expires_at, is_guest, guest_expires_at, timezone, email_verified_at, pending_email, locale, presence_status, presence_until, is_bot, birthday_day, birthday_month, birthday_year, birthday_hidden, event_reminders, event_reminders_dnd, storage_quota_bytes, work_start_min, work_end_min, work_days, hide_message_text_in_notifications
`

type CreateGuestUserParams struct {
	DisplayName    string
	Settings       []byte
	GuestExpiresAt *time.Time
}

func (q *Queries) CreateGuestUser(ctx context.Context, arg CreateGuestUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createGuestUser, arg.DisplayName, arg.Settings, arg.GuestExpiresAt)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarFileID,
		&i.StatusText,
		&i.Settings,
		&i.CreatedAt,
		&i.DisabledAt,
		&i.StatusEmoji,
		&i.StatusExpiresAt,
		&i.IsGuest,
		&i.GuestExpiresAt,
		&i.Timezone,
		&i.EmailVerifiedAt,
		&i.PendingEmail,
		&i.Locale,
		&i.PresenceStatus,
		&i.PresenceUntil,
		&i.IsBot,
		&i.BirthdayDay,
		&i.BirthdayMonth,
		&i.BirthdayYear,
		&i.BirthdayHidden,
		&i.EventReminders,
		&i.EventRemindersDnd,
		&i.StorageQuotaBytes,
		&i.WorkStartMin,
		&i.WorkEndMin,
		&i.WorkDays,
		&i.HideMessageTextInNotifications,
	)
	return i, err
}

const createRoomInvite = `-- name: CreateRoomInvite :one
INSERT INTO room_invites (room_id, code, created_by, expires_at, max_uses, allow_guests, allow_bits, require_approval, members_only)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only
`

type CreateRoomInviteParams struct {
	RoomID          uuid.UUID
	Code            string
	CreatedBy       uuid.UUID
	ExpiresAt       *time.Time
	MaxUses         int32
	AllowGuests     bool
	AllowBits       int64
	RequireApproval *bool
	MembersOnly     bool
}

func (q *Queries) CreateRoomInvite(ctx context.Context, arg CreateRoomInviteParams) (RoomInvite, error) {
	row := q.db.QueryRow(ctx, createRoomInvite,
		arg.RoomID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
		arg.AllowGuests,
		arg.AllowBits,
		arg.RequireApproval,
		arg.MembersOnly,
	)
	var i RoomInvite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowGuests,
		&i.AllowBits,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NotBefore,
		&i.EventID,
		&i.RequireApproval,
		&i.MembersOnly,
	)
	return i, err
}

const deleteUserMemberships = `-- name: DeleteUserMemberships :exec
DELETE FROM workspace_members WHERE user_id = $1
`

func (q *Queries) DeleteUserMemberships(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserMemberships, userID)
	return err
}

const deleteUserRoomOverrides = `-- name: DeleteUserRoomOverrides :exec
DELETE FROM room_permissions WHERE target_type = 'user' AND target_id = $1::text
`

func (q *Queries) DeleteUserRoomOverrides(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserRoomOverrides, userID)
	return err
}

const getRoomInviteByCode = `-- name: GetRoomInviteByCode :one
SELECT i.id, i.room_id, i.code, i.created_by, i.expires_at, i.max_uses, i.uses, i.allow_guests, i.allow_bits, i.revoked_at, i.created_at, i.not_before, i.event_id, i.require_approval, i.members_only, r.id, r.workspace_id, r.type, r.name, r.topic, r.position, r.is_private, r.audio_bitrate_kbps, r.max_stream_preset, r.max_streams, r.created_at, r.archived_at, r.category_id, r.user_limit, r.voice_status, r.camera_limit, r.dm_key, r.allow_recording, r.restricted, r.emoji, r.guest_approval, r.expires_at, r.created_by, w.id, w.slug, w.name, w.icon_file_id, w.visibility, w.owner_id, w.created_at, w.default_audio_bitrate_kbps, w.default_max_stream_preset, w.default_max_streams, w.storage_quota_bytes, w.storage_used_bytes, w.allow_self_nickname, w.default_camera_limit, w.suspended_at, w.suspended_reason, w.suspended_by, w.time_format, w.sip_enabled, w.hide_message_text_in_notifications
FROM room_invites i
JOIN rooms r ON r.id = i.room_id AND r.archived_at IS NULL
JOIN workspaces w ON w.id = r.workspace_id
WHERE i.code = $1 AND i.revoked_at IS NULL
  AND (i.expires_at IS NULL OR i.expires_at > now())
  AND (i.max_uses = 0 OR i.uses < i.max_uses)
`

type GetRoomInviteByCodeRow struct {
	RoomInvite RoomInvite
	Room       Room
	Workspace  Workspace
}

func (q *Queries) GetRoomInviteByCode(ctx context.Context, code string) (GetRoomInviteByCodeRow, error) {
	row := q.db.QueryRow(ctx, getRoomInviteByCode, code)
	var i GetRoomInviteByCodeRow
	err := row.Scan(
		&i.RoomInvite.ID,
		&i.RoomInvite.RoomID,
		&i.RoomInvite.Code,
		&i.RoomInvite.CreatedBy,
		&i.RoomInvite.ExpiresAt,
		&i.RoomInvite.MaxUses,
		&i.RoomInvite.Uses,
		&i.RoomInvite.AllowGuests,
		&i.RoomInvite.AllowBits,
		&i.RoomInvite.RevokedAt,
		&i.RoomInvite.CreatedAt,
		&i.RoomInvite.NotBefore,
		&i.RoomInvite.EventID,
		&i.RoomInvite.RequireApproval,
		&i.RoomInvite.MembersOnly,
		&i.Room.ID,
		&i.Room.WorkspaceID,
		&i.Room.Type,
		&i.Room.Name,
		&i.Room.Topic,
		&i.Room.Position,
		&i.Room.IsPrivate,
		&i.Room.AudioBitrateKbps,
		&i.Room.MaxStreamPreset,
		&i.Room.MaxStreams,
		&i.Room.CreatedAt,
		&i.Room.ArchivedAt,
		&i.Room.CategoryID,
		&i.Room.UserLimit,
		&i.Room.VoiceStatus,
		&i.Room.CameraLimit,
		&i.Room.DmKey,
		&i.Room.AllowRecording,
		&i.Room.Restricted,
		&i.Room.Emoji,
		&i.Room.GuestApproval,
		&i.Room.ExpiresAt,
		&i.Room.CreatedBy,
		&i.Workspace.ID,
		&i.Workspace.Slug,
		&i.Workspace.Name,
		&i.Workspace.IconFileID,
		&i.Workspace.Visibility,
		&i.Workspace.OwnerID,
		&i.Workspace.CreatedAt,
		&i.Workspace.DefaultAudioBitrateKbps,
		&i.Workspace.DefaultMaxStreamPreset,
		&i.Workspace.DefaultMaxStreams,
		&i.Workspace.StorageQuotaBytes,
		&i.Workspace.StorageUsedBytes,
		&i.Workspace.AllowSelfNickname,
		&i.Workspace.DefaultCameraLimit,
		&i.Workspace.SuspendedAt,
		&i.Workspace.SuspendedReason,
		&i.Workspace.SuspendedBy,
		&i.Workspace.TimeFormat,
		&i.Workspace.SipEnabled,
		&i.Workspace.HideMessageTextInNotifications,
	)
	return i, err
}

const listExpiredGuests = `-- name: ListExpiredGuests :many
SELECT id FROM users
WHERE is_guest AND guest_expires_at IS NOT NULL AND guest_expires_at < $1 AND disabled_at IS NULL
LIMIT 200
`

func (q *Queries) ListExpiredGuests(ctx context.Context, guestExpiresAt *time.Time) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listExpiredGuests, guestExpiresAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoomInvites = `-- name: ListRoomInvites :many
SELECT id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only FROM room_invites
WHERE room_id = $1 AND revoked_at IS NULL AND (expires_at IS NULL OR expires_at > now())
  AND (max_uses = 0 OR uses < max_uses)
ORDER BY created_at DESC
`

func (q *Queries) ListRoomInvites(ctx context.Context, roomID uuid.UUID) ([]RoomInvite, error) {
	rows, err := q.db.Query(ctx, listRoomInvites, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoomInvite{}
	for rows.Next() {
		var i RoomInvite
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Code,
			&i.CreatedBy,
			&i.ExpiresAt,
			&i.MaxUses,
			&i.Uses,
			&i.AllowGuests,
			&i.AllowBits,
			&i.RevokedAt,
			&i.CreatedAt,
			&i.NotBefore,
			&i.EventID,
			&i.RequireApproval,
			&i.MembersOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFiles = `-- name: ListUserFiles :many
SELECT id, workspace_id, uploader_id, key, thumbnail_key, name, mime, size, width, height, sha256, created_at, voice_duration_ms, voice_waveform FROM files WHERE uploader_id = $1
`

func (q *Queries) ListUserFiles(ctx context.Context, uploaderID uuid.UUID) ([]File, error) {
	rows, err := q.db.Query(ctx, listUserFiles, uploaderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.UploaderID,
			&i.Key,
			&i.ThumbnailKey,
			&i.Name,
			&i.Mime,
			&i.Size,
			&i.Width,
			&i.Height,
			&i.Sha256,
			&i.CreatedAt,
			&i.VoiceDurationMs,
			&i.VoiceWaveform,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredGuest = `-- name: LockExpiredGuest :one
SELECT id FROM users
WHERE id = $1 AND is_guest AND guest_expires_at IS NOT NULL AND guest_expires_at < now() AND disabled_at IS NULL
FOR UPDATE
`

// Re-checks expiry under a row lock inside the cleanup transaction (a refresh may have
// just extended it).
func (q *Queries) LockExpiredGuest(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockExpiredGuest, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const promoteGuest = `-- name: PromoteGuest :one
UPDATE workspace_members SET role = 'member'
WHERE workspace_id = $1 AND user_id = $2 AND role = 'guest'
RETURNING workspace_id, user_id, role, nickname, joined_at, badge_id, achievement_count
`

type PromoteGuestParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) PromoteGuest(ctx context.Context, arg PromoteGuestParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, promoteGuest, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
		&i.BadgeID,
		&i.AchievementCount,
	)
	return i, err
}

const revokeRoomInvite = `-- name: RevokeRoomInvite :execrows
UPDATE room_invites SET revoked_at = now()
WHERE id = $1 AND room_id = $2 AND revoked_at IS NULL
  AND (NOT $3::bool OR members_only)
`

type RevokeRoomInviteParams struct {
	ID              uuid.UUID
	RoomID          uuid.UUID
	OnlyMembersOnly bool
}

// only_members_only: the caller may revoke members-only links only (INVITE_MEMBERS, ADR-0043).
func (q *Queries) RevokeRoomInvite(ctx context.Context, arg RevokeRoomInviteParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRoomInvite, arg.ID, arg.RoomID, arg.OnlyMembersOnly)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setRoomInviteApproval = `-- name: SetRoomInviteApproval :one
UPDATE room_invites SET require_approval = $1
WHERE id = $2 AND room_id = $3 AND revoked_at IS NULL
RETURNING id, room_id, code, created_by, expires_at, max_uses, uses, allow_guests, allow_bits, revoked_at, created_at, not_before, event_id, require_approval, members_only
`

type SetRoomInviteApprovalParams struct {
	RequireApproval *bool
	ID              uuid.UUID
	RoomID          uuid.UUID
}

// require_approval NULL = as the room (ADR-0040).
func (q *Queries) SetRoomInviteApproval(ctx context.Context, arg SetRoomInviteApprovalParams) (RoomInvite, error) {
	row := q.db.QueryRow(ctx, setRoomInviteApproval, arg.RequireApproval, arg.ID, arg.RoomID)
	var i RoomInvite
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Code,
		&i.CreatedBy,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
		&i.AllowGuests,
		&i.AllowBits,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.NotBefore,
		&i.EventID,
		&i.RequireApproval,
		&i.MembersOnly,
	)
	return i, err
}

const touchGuest = `-- name: TouchGuest :exec
UPDATE users SET guest_expires_at = $2 WHERE id = $1 AND is_guest AND guest_expires_at IS NOT NULL
`

type TouchGuestParams struct {
	ID             uuid.UUID
	GuestExpiresAt *time.Time
}

func (q *Queries) TouchGuest(ctx context.Context, arg TouchGuestParams) error {
	_, err := q.db.Exec(ctx, touchGuest, arg.ID, arg.GuestExpiresAt)
	return err
}

const upsertUserOverride = `-- name: UpsertUserOverride :one
INSERT INTO room_permissions (room_id, target_type, target_id, allow, deny)
VALUES ($1, 'user', $2::text, $3, 0)
ON CONFLICT (room_id, target_type, target_id) DO UPDATE
    SET allow = room_permissions.allow | (EXCLUDED.allow & ~room_permissions.deny)
RETURNING room_id, target_type, target_id, allow, deny
`

type UpsertUserOverrideParams struct {
	RoomID uuid.UUID
	UserID string
	Allow  int64
}

// Grants `allow` to one user in a room on top of an existing override. Bits an admin
// explicitly denied to this user stay denied (a link must not lift a deny).
func (q *Queries) UpsertUserOverride(ctx context.Context, arg UpsertUserOverrideParams) (RoomPermission, error) {
	row := q.db.QueryRow(ctx, upsertUserOverride, arg.RoomID, arg.UserID, arg.Allow)
	var i RoomPermission
	err := row.Scan(
		&i.RoomID,
		&i.TargetType,
		&i.TargetID,
		&i.Allow,
		&i.Deny,
	)
	return i, err
}
