// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createBan = `-- name: CreateBan :one
INSERT INTO workspace_bans (workspace_id, user_id, email, reason, banned_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, user_id) DO UPDATE
SET email = EXCLUDED.email, reason = EXCLUDED.reason, banned_by = EXCLUDED.banned_by, created_at = now()
RETURNING workspace_id, user_id, email, reason, banned_by, created_at
`

type CreateBanParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Email       *string
	Reason      string
	BannedBy    *uuid.UUID
}

func (q *Queries) CreateBan(ctx context.Context, arg CreateBanParams) (WorkspaceBan, error) {
	row := q.db.QueryRow(ctx, createBan,
		arg.WorkspaceID,
		arg.UserID,
		arg.Email,
		arg.Reason,
		arg.BannedBy,
	)
	var i WorkspaceBan
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Email,
		&i.Reason,
		&i.BannedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteBan = `-- name: DeleteBan :execrows
DELETE FROM workspace_bans WHERE workspace_id = $1 AND user_id = $2
`

type DeleteBanParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) DeleteBan(ctx context.Context, arg DeleteBanParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBan, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePendingEmailInvitesFor = `-- name: DeletePendingEmailInvitesFor :exec
DELETE FROM workspace_invites i
USING email_invites e
WHERE e.invite_id = i.id AND e.workspace_id = $1 AND e.email = $2 AND e.accepted_at IS NULL
`

type DeletePendingEmailInvitesForParams struct {
	WorkspaceID uuid.UUID
	Email       string
}

// Revokes the pending email invitations of an address in a workspace (their links go with them).
func (q *Queries) DeletePendingEmailInvitesFor(ctx context.Context, arg DeletePendingEmailInvitesForParams) error {
	_, err := q.db.Exec(ctx, deletePendingEmailInvitesFor, arg.WorkspaceID, arg.Email)
	return err
}

const insertAdminLog = `-- name: InsertAdminLog :exec
INSERT INTO workspace_admin_log (workspace_id, actor_id, action, reason)
VALUES ($1, $2, $3, $4)
`

type InsertAdminLogParams struct {
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	Reason      string
}

func (q *Queries) InsertAdminLog(ctx context.Context, arg InsertAdminLogParams) error {
	_, err := q.db.Exec(ctx, insertAdminLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Action,
		arg.Reason,
	)
	return err
}

const inviteWorkspaceSuspended = `-- name: InviteWorkspaceSuspended :one
SELECT EXISTS (
    SELECT 1 FROM workspace_invites i
    JOIN workspaces w ON w.id = i.workspace_id
    WHERE i.code = $1 AND w.suspended_at IS NOT NULL
)::boolean
`

// Whether the workspace of an invite code is suspended (false for unknown codes).
func (q *Queries) InviteWorkspaceSuspended(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, inviteWorkspaceSuspended, code)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const isBanned = `-- name: IsBanned :one
SELECT EXISTS (
    SELECT 1 FROM workspace_bans b
    WHERE b.workspace_id = $1
      AND (b.user_id = $2
           OR ($3::citext IS NOT NULL AND b.email = $3::citext))
)::boolean
`

type IsBannedParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Email       *string
}

// Whether a user (or, if given, their address) is banned from a workspace.
func (q *Queries) IsBanned(ctx context.Context, arg IsBannedParams) (bool, error) {
	row := q.db.QueryRow(ctx, isBanned, arg.WorkspaceID, arg.UserID, arg.Email)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const listBans = `-- name: ListBans :many
SELECT b.workspace_id, b.user_id, b.email, b.reason, b.banned_by, b.created_at, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days, u.hide_message_text_in_notifications, u.username, u.phone
FROM workspace_bans b
JOIN users u ON u.id = b.user_id
WHERE b.workspace_id = $1
ORDER BY b.created_at DESC, b.user_id
`

type ListBansRow struct {
	WorkspaceBan WorkspaceBan
	User         User
}

func (q *Queries) ListBans(ctx context.Context, workspaceID uuid.UUID) ([]ListBansRow, error) {
	rows, err := q.db.Query(ctx, listBans, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBansRow{}
	for rows.Next() {
		var i ListBansRow
		if err := rows.Scan(
			&i.WorkspaceBan.WorkspaceID,
			&i.WorkspaceBan.UserID,
			&i.WorkspaceBan.Email,
			&i.WorkspaceBan.Reason,
			&i.WorkspaceBan.BannedBy,
			&i.WorkspaceBan.CreatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.User.HideMessageTextInNotifications,
			&i.User.Username,
			&i.User.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const messageWorkspaceSuspended = `-- name: MessageWorkspaceSuspended :one
SELECT EXISTS (
    SELECT 1 FROM messages m
    JOIN rooms r ON r.id = m.room_id
    JOIN workspaces w ON w.id = r.workspace_id
    WHERE m.id = $1 AND w.suspended_at IS NOT NULL
)::boolean
`

// Whether the workspace of a message's room is suspended (false for DMs / unknown ids).
func (q *Queries) MessageWorkspaceSuspended(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, messageWorkspaceSuspended, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const setWorkspaceSuspension = `-- name: SetWorkspaceSuspension :one
UPDATE workspaces
SET suspended_at     = $1,
    suspended_reason = $2,
    suspended_by     = $3
WHERE id = $4
RETURNING id, slug, name, icon_file_id, visibility, owner_id, created_at, default_audio_bitrate_kbps, default_max_stream_preset, default_max_streams, storage_quota_bytes, storage_used_bytes, allow_self_nickname, default_camera_limit, suspended_at, suspended_reason, suspended_by, time_format, sip_enabled
`

type SetWorkspaceSuspensionParams struct {
	SuspendedAt *time.Time
	Reason      string
	SuspendedBy *uuid.UUID
	ID          uuid.UUID
}

// Suspends (at = now) or resumes (at NULL) a workspace; the reason / actor are cleared on resume.
func (q *Queries) SetWorkspaceSuspension(ctx context.Context, arg SetWorkspaceSuspensionParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceSuspension,
		arg.SuspendedAt,
		arg.Reason,
		arg.SuspendedBy,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IconFileID,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DefaultAudioBitrateKbps,
		&i.DefaultMaxStreamPreset,
		&i.DefaultMaxStreams,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.AllowSelfNickname,
		&i.DefaultCameraLimit,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.SuspendedBy,
		&i.TimeFormat,
		&i.SipEnabled,
	)
	return i, err
}

const workspaceSuspended = `-- name: WorkspaceSuspended :one
SELECT EXISTS (SELECT 1 FROM workspaces WHERE id = $1 AND suspended_at IS NOT NULL)::boolean
`

// Whether a workspace is suspended (false for an unknown id).
func (q *Queries) WorkspaceSuspended(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, workspaceSuspended, id)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
