// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Achievement struct {
	ID             uuid.UUID
	Title          string
	Description    string
	ImageSize      int32
	Width          int32
	Height         int32
	Position       int32
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	ArchivedAt     *time.Time
	WorkspaceID    uuid.UUID
	FileID         *uuid.UUID
	LegacyImageKey *string
}

type AchievementLegacyBlob struct {
	Key string
}

type BirthdayGreeting struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Day         pgtype.Date
	MessageID   *uuid.UUID
	CreatedAt   time.Time
}

type Board struct {
	ID               uuid.UUID
	WorkspaceID      uuid.UUID
	Name             string
	Key              string
	Emoji            string
	IconFileID       *uuid.UUID
	Description      string
	IsPrivate        bool
	Position         int32
	NextNumber       int32
	AutoArchiveDays  int32
	DefaultViewID    *uuid.UUID
	CreatedBy        *uuid.UUID
	CreatedAt        time.Time
	ArchivedAt       *time.Time
	Restricted       bool
	CategoryID       *uuid.UUID
	DisabledFeatures int64
	EstimateScale    string
}

type BoardCategory struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Position    int32
	CreatedAt   time.Time
}

type BoardForm struct {
	ID         uuid.UUID
	BoardID    uuid.UUID
	Code       string
	Definition []byte
	Revision   int32
	CreatedBy  *uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type BoardFormSubmission struct {
	ID          uuid.UUID
	FormID      uuid.UUID
	Nonce       uuid.UUID
	RequestHash []byte
	ActorID     *uuid.UUID
	TaskID      *uuid.UUID
	CreatedAt   time.Time
}

type BoardGit struct {
	BoardID     uuid.UUID
	Provider    string
	SecretEnc   []byte
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	LastEventAt *time.Time
	LastError   string
	EventsCount int32
}

type BoardLabel struct {
	ID       uuid.UUID
	BoardID  uuid.UUID
	Name     string
	Color    int32
	Position int32
}

type BoardMilestone struct {
	ID       uuid.UUID
	BoardID  uuid.UUID
	Name     string
	DueOn    pgtype.Date
	Position int32
}

type BoardPermission struct {
	BoardID    uuid.UUID
	TargetType string
	TargetID   string
	Allow      int64
	Deny       int64
}

type BoardRule struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	Name        string
	Enabled     bool
	Position    int32
	TriggerKind string
	Trigger     []byte
	Condition   []byte
	Actions     []byte
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	RunsCount   int32
	LastRunAt   *time.Time
	LastError   string
}

type BoardRuleRun struct {
	ID             uuid.UUID
	RuleID         uuid.UUID
	TaskID         *uuid.UUID
	TriggerKind    string
	Ok             bool
	Error          string
	ActionsApplied int16
	SchedKey       pgtype.Date
	CreatedAt      time.Time
}

type BoardStatus struct {
	ID        uuid.UUID
	BoardID   uuid.UUID
	Name      string
	Type      string
	Color     int32
	Position  int32
	IsDefault bool
}

type BoardView struct {
	ID        uuid.UUID
	BoardID   uuid.UUID
	Name      string
	Kind      string
	Filter    []byte
	GroupBy   string
	Sort      string
	Shared    bool
	CreatedBy uuid.UUID
	Position  int32
	CreatedAt time.Time
}

type BoardWebhook struct {
	BoardID      uuid.UUID
	Url          string
	SecretEnc    []byte
	DisabledAt   *time.Time
	FailingSince *time.Time
	LastOkAt     *time.Time
	LastError    string
	NextSeq      int64
	CreatedBy    *uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type BoardWebhookDelivery struct {
	ID          uuid.UUID
	BoardID     uuid.UUID
	Seq         int64
	EventType   string
	Payload     []byte
	Attempts    int32
	NextAt      time.Time
	CreatedAt   time.Time
	DeliveredAt *time.Time
	FailedAt    *time.Time
	Error       string
}

type Bot struct {
	UserID              uuid.UUID
	OwnerUserID         uuid.UUID
	WorkspaceID         uuid.UUID
	Username            string
	Description         string
	TokenID             *uuid.UUID
	TokenHash           []byte
	TokenPrefix         string
	WebhookUrl          *string
	WebhookSecretEnc    []byte
	WebhookDisabledAt   *time.Time
	WebhookFailingSince *time.Time
	WebhookLastOkAt     *time.Time
	WebhookLastError    string
	CreatedAt           time.Time
	RevokedAt           *time.Time
}

type BotBlock struct {
	UserID    uuid.UUID
	BotUserID uuid.UUID
	CreatedAt time.Time
}

type BotCommand struct {
	BotUserID   uuid.UUID
	Name        string
	Description string
	Position    int16
}

type BotWebhookDelivery struct {
	ID          uuid.UUID
	BotUserID   uuid.UUID
	Payload     []byte
	Attempts    int32
	NextAt      time.Time
	CreatedAt   time.Time
	DeliveredAt *time.Time
	FailedAt    *time.Time
	Error       string
}

type CaldavAccount struct {
	UserID       uuid.UUID
	Url          string
	Username     string
	SecretEnc    []byte
	Calendars    []byte
	CalendarHref *string
	Import       bool
	Push         bool
	LastSyncAt   *time.Time
	LastError    string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	ShareLevel   string
	Remind       bool
}

type CaldavPush struct {
	UserID    uuid.UUID
	EventID   uuid.UUID
	Gen       int64
	Attempts  int32
	NextAt    time.Time
	Error     string
	CreatedAt time.Time
}

type DirectoryObject struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	DirectoryID       uuid.UUID
	ObjectGuid        uuid.UUID
	UserID            *uuid.UUID
	DistinguishedName string
	Status            string
	Version           int64
	LastSeenRunID     *uuid.UUID
	MissingFullScans  int32
	UpdatedAt         time.Time
}

type DirectorySyncObject struct {
	WorkspaceID       uuid.UUID
	DirectoryID       uuid.UUID
	RunID             uuid.UUID
	ObjectGuid        uuid.UUID
	DistinguishedName string
	Eligible          bool
	Disabled          bool
}

type DirectorySyncRun struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	DirectoryID   uuid.UUID
	FullScan      bool
	ConfigVersion int64
	Generation    int64
	LeaseUntil    time.Time
	Status        string
	Complete      bool
	ObjectsSeen   int32
	StartedAt     time.Time
	FinishedAt    *time.Time
}

type DmMember struct {
	RoomID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
}

type DmState struct {
	UserID        uuid.UUID
	RoomID        uuid.UUID
	ArchivedAt    *time.Time
	ClearedBefore *uuid.UUID
}

type EmailCode struct {
	UserID    uuid.UUID
	Purpose   string
	CodeHash  string
	ExpiresAt time.Time
	Attempts  int32
	CreatedAt time.Time
}

type EmailInvite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Email       string
	Role        string
	InvitedBy   uuid.UUID
	InviteID    uuid.UUID
	ExpiresAt   time.Time
	LastSentAt  time.Time
	AcceptedAt  *time.Time
	CreatedAt   time.Time
}

type Event struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	RoomID      *uuid.UUID
	Title       string
	Description string
	StartsAt    time.Time
	EndsAt      time.Time
	AllDay      bool
	Tz          string
	OrganizerID uuid.UUID
	Record      bool
	Rrule       *string
	UntilAt     *time.Time
	Sequence    int32
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CancelledAt *time.Time
}

type EventAttendee struct {
	EventID     uuid.UUID
	UserID      *uuid.UUID
	Email       *string
	Required    bool
	Status      string
	RespondedAt *time.Time
	InviteID    *uuid.UUID
}

type EventException struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
}

type EventRecording struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	RecordingID  uuid.UUID
}

type EventRemindersSent struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	UserID       uuid.UUID
	Minutes      int16
	SentAt       time.Time
}

type EventRoomSignal struct {
	EventID      uuid.UUID
	OccurrenceAt time.Time
	Kind         string
	SentAt       time.Time
}

type ExternalBusy struct {
	UserID    uuid.UUID
	Uid       string
	StartsAt  time.Time
	EndsAt    time.Time
	AllDay    bool
	Summary   string
	Location  string
	Attendees []byte
	Organizer string
	Url       string
	Href      string
	Etag      string
	Recurring bool
	WebUrl    string
}

type ExternalRemindersSent struct {
	UserID       uuid.UUID
	Uid          string
	OccurrenceAt time.Time
	Minutes      int16
	SentAt       time.Time
}

type File struct {
	ID              uuid.UUID
	WorkspaceID     *uuid.UUID
	UploaderID      uuid.UUID
	Key             string
	ThumbnailKey    *string
	Name            string
	Mime            string
	Size            int64
	Width           *int32
	Height          *int32
	Sha256          string
	CreatedAt       time.Time
	VoiceDurationMs *int32
	VoiceWaveform   []byte
}

type IdentityInvalidationOutbox struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        *uuid.UUID
	SessionID     *uuid.UUID
	PolicyVersion int64
	AccessVersion int64
	Reason        string
	CreatedAt     time.Time
	DeliveredAt   *time.Time
}

type IdentityLoginTransaction struct {
	ID                uuid.UUID
	WorkspaceID       uuid.UUID
	ConnectionID      uuid.UUID
	ConnectionVersion int64
	Purpose           string
	SessionID         *uuid.UUID
	UserID            *uuid.UUID
	StateHash         []byte
	BrowserHash       []byte
	NonceHash         []byte
	VerifierBox       []byte
	ReturnUri         string
	NativeChallenge   *string
	BrowserStartHash  []byte
	BrowserStartedAt  *time.Time
	ResultBox         []byte
	CompletedAt       *time.Time
	FinishedAt        *time.Time
	ExpiresAt         time.Time
	ConsumedAt        *time.Time
	CreatedAt         time.Time
}

type IdentityNativeHandoff struct {
	ID            uuid.UUID
	TransactionID uuid.UUID
	TicketHash    []byte
	Challenge     string
	ResultBox     []byte
	ExpiresAt     time.Time
	ConsumedAt    *time.Time
}

type MailOutbox struct {
	ID        uuid.UUID
	ToAddr    string
	Template  string
	Locale    string
	Params    []byte
	Priority  int16
	Attempts  int32
	NextAt    time.Time
	ExpiresAt time.Time
	CreatedAt time.Time
	SentAt    *time.Time
	FailedAt  *time.Time
	Error     string
}

type MemberAchievement struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	UserID        uuid.UUID
	AchievementID uuid.UUID
	GrantedBy     *uuid.UUID
	Note          string
	MessageID     *uuid.UUID
	GrantedAt     time.Time
	RevokedAt     *time.Time
	RevokedBy     *uuid.UUID
}

type MemberRole struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	RoleID      uuid.UUID
}

type Message struct {
	ID               uuid.UUID
	RoomID           uuid.UUID
	AuthorID         uuid.UUID
	Content          string
	ReplyToID        *uuid.UUID
	Nonce            *string
	CreatedAt        time.Time
	EditedAt         *time.Time
	DeletedAt        *time.Time
	PinnedAt         *time.Time
	PinnedBy         *uuid.UUID
	EmbedsHidden     bool
	Kind             string
	Payload          []byte
	StickerID        *uuid.UUID
	ForwardedFrom    *uuid.UUID
	ForwardAuthorID  *uuid.UUID
	ForwardSentAt    *time.Time
	InlineKeyboard   []byte
	KeyboardRevision int64
}

type MessageAttachment struct {
	MessageID uuid.UUID
	FileID    uuid.UUID
	Position  int16
	Forwarded bool
}

type MessageEveryoneMention struct {
	MessageID uuid.UUID
	RoomID    uuid.UUID
}

type MessageInteraction struct {
	ID               uuid.UUID
	MessageID        uuid.UUID
	UserID           uuid.UUID
	Nonce            string
	ButtonID         string
	KeyboardRevision int64
	CreatedAt        time.Time
}

type MessageMention struct {
	UserID    uuid.UUID
	MessageID uuid.UUID
	RoomID    uuid.UUID
}

type MessageReaction struct {
	MessageID uuid.UUID
	UserID    uuid.UUID
	Emoji     string
	CreatedAt time.Time
}

type OauthAuthorizationCode struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	GrantID       uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	CodeHash      []byte
	RedirectUri   string
	PkceChallenge string
	Nonce         string
	CreatedAt     time.Time
	ExpiresAt     time.Time
	ConsumedAt    *time.Time
}

type OauthAuthorizationRequest struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	ClientID        uuid.UUID
	Issuer          string
	ClientVersion   int64
	HandleHash      []byte
	BrowserHash     []byte
	CsrfHash        []byte
	SessionID       *uuid.UUID
	UserID          *uuid.UUID
	RedirectUri     string
	Scopes          []string
	State           string
	Nonce           string
	PkceChallenge   string
	Prompt          string
	MaxAgeSeconds   *int32
	ExpiresAt       time.Time
	ConsumedAt      *time.Time
	CreatedAt       time.Time
	ClientIpHash    []byte
	ShownClientName *string
}

type OauthClient struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	ClientID       string
	Name           string
	ClientType     string
	RefreshEnabled bool
	AllowedOrigins []string
	AuthMethod     string
	Scopes         []string
	Version        int64
	DisabledAt     *time.Time
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
}

type OauthClientRedirect struct {
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	RedirectUri string
}

type OauthClientSecret struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ClientID    uuid.UUID
	SecretHash  []byte
	CreatedAt   time.Time
	ValidUntil  time.Time
	RevokedAt   *time.Time
}

type OauthConsent struct {
	ID             uuid.UUID
	WorkspaceID    uuid.UUID
	UserID         uuid.UUID
	ClientID       uuid.UUID
	Scopes         []string
	Version        int64
	RefreshAllowed bool
	ClientName     string
	GrantedAt      time.Time
	RevokedAt      *time.Time
}

type OauthGrant struct {
	ID                 uuid.UUID
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	ClientID           uuid.UUID
	ConsentID          uuid.UUID
	SessionID          uuid.UUID
	Scopes             []string
	Issuer             string
	ClientVersion      int64
	ConsentVersion     int64
	PolicyVersion      int64
	AccessVersion      int64
	EntitlementVersion int64
	SessionVersion     int64
	AuthenticatedAt    time.Time
	AssuranceExpiresAt *time.Time
	CreatedAt          time.Time
	ExpiresAt          time.Time
	IdleExpiresAt      time.Time
	RevokedAt          *time.Time
	RevokedReason      *string
}

type OauthSubject struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Subject     string
}

type OauthToken struct {
	ID            uuid.UUID
	WorkspaceID   uuid.UUID
	GrantID       uuid.UUID
	UserID        uuid.UUID
	ClientID      uuid.UUID
	TokenHash     []byte
	TokenType     string
	Generation    int64
	ParentTokenID *uuid.UUID
	CreatedAt     time.Time
	ExpiresAt     time.Time
	UsedAt        *time.Time
	RevokedAt     *time.Time
}

type ProductAdminGrant struct {
	UserID       uuid.UUID
	GrantedAt    time.Time
	RevokedAt    *time.Time
	OperatorNote string
}

type PushDelivery struct {
	ID              uuid.UUID
	DeviceID        uuid.UUID
	DeviceVersion   int64
	EventKey        string
	Kind            int16
	ReferenceID     uuid.UUID
	RoomID          *uuid.UUID
	ActorID         *uuid.UUID
	NoticeKind      int16
	ContextID       *uuid.UUID
	OccurrenceAt    *time.Time
	ReminderMinutes int16
	ExpiresAt       time.Time
	NotBefore       time.Time
	Attempts        int16
	LeaseID         *uuid.UUID
	LeaseUntil      *time.Time
	CreatedAt       time.Time
	DeliveredAt     *time.Time
}

type PushDevice struct {
	ID                   uuid.UUID
	UserID               uuid.UUID
	SessionID            uuid.UUID
	InstallationID       uuid.UUID
	Provider             int16
	Environment          string
	AppID                string
	Token                string
	TokenHash            []byte
	Version              int64
	NotificationsEnabled bool
	CallsEnabled         bool
	MentionsEnabled      bool
	AllEnabled           bool
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ExpiresAt            time.Time
}

type PushIntent struct {
	ID              uuid.UUID
	RecipientID     *uuid.UUID
	EventKey        string
	Kind            int16
	ReferenceID     uuid.UUID
	RoomID          *uuid.UUID
	ActorID         *uuid.UUID
	NoticeKind      int16
	ContextID       *uuid.UUID
	OccurrenceAt    *time.Time
	ReminderMinutes int16
	ExpiresAt       time.Time
	NotBefore       time.Time
	AfterUser       uuid.UUID
	Attempts        int16
	LeaseID         *uuid.UUID
	LeaseUntil      *time.Time
	CompletedAt     *time.Time
}

type ReadState struct {
	UserID            uuid.UUID
	RoomID            uuid.UUID
	LastReadMessageID uuid.UUID
}

type Room struct {
	ID               uuid.UUID
	WorkspaceID      *uuid.UUID
	Type             string
	Name             string
	Topic            string
	Position         int32
	IsPrivate        bool
	AudioBitrateKbps *int32
	MaxStreamPreset  *string
	MaxStreams       *int32
	CreatedAt        time.Time
	ArchivedAt       *time.Time
	CategoryID       *uuid.UUID
	UserLimit        int32
	VoiceStatus      *string
	CameraLimit      *int32
	DmKey            *string
	AllowRecording   bool
	Restricted       bool
	Emoji            string
	GuestApproval    bool
	ExpiresAt        *time.Time
	CreatedBy        *uuid.UUID
}

type RoomAdmission struct {
	RoomID      uuid.UUID
	UserID      uuid.UUID
	InviteID    *uuid.UUID
	Status      string
	RequestedAt time.Time
	DecidedBy   *uuid.UUID
	DecidedAt   *time.Time
}

type RoomCategory struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Position    int32
	CreatedAt   time.Time
}

type RoomInvite struct {
	ID              uuid.UUID
	RoomID          uuid.UUID
	Code            string
	CreatedBy       uuid.UUID
	ExpiresAt       *time.Time
	MaxUses         int32
	Uses            int32
	AllowGuests     bool
	AllowBits       int64
	RevokedAt       *time.Time
	CreatedAt       time.Time
	NotBefore       *time.Time
	EventID         *uuid.UUID
	RequireApproval *bool
	MembersOnly     bool
}

type RoomNotificationSetting struct {
	UserID     uuid.UUID
	RoomID     uuid.UUID
	Level      string
	MutedUntil *time.Time
}

type RoomPermission struct {
	RoomID     uuid.UUID
	TargetType string
	TargetID   string
	Allow      int64
	Deny       int64
}

type RoomRecording struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	RoomID          uuid.UUID
	StartedBy       *uuid.UUID
	StoppedBy       *uuid.UUID
	Status          string
	StopReason      string
	EgressID        *string
	File            string
	SizeBytes       int64
	DurationSec     int32
	StartedAt       time.Time
	StoppedAt       *time.Time
	EmptySince      *time.Time
	GptunnelID      string
	WebUrl          string
	Error           string
	MessageID       *uuid.UUID
	Attempts        int32
	NextAt          *time.Time
	ProcessingSince *time.Time
	FileDeletedAt   *time.Time
	UpdatedAt       time.Time
	Reuploads       int32
	ReuploadAt      *time.Time
	DoneAt          *time.Time
	Summary         string
	Language        string
	TranscriptJson  []byte
	ResultState     string
	ResultAttempts  int32
	ResultNextAt    *time.Time
	FileID          *uuid.UUID
	DeletedAt       *time.Time
	DeletedBy       *uuid.UUID
	TranscriptText  *string
}

type Session struct {
	ID                      uuid.UUID
	UserID                  uuid.UUID
	RefreshTokenHash        []byte
	PrevRefreshTokenHash    []byte
	RotatedAt               *time.Time
	DeviceName              string
	Ip                      string
	UserAgent               string
	CreatedAt               time.Time
	LastSeenAt              time.Time
	ExpiresAt               time.Time
	RevokedAt               *time.Time
	RefreshGen              int64
	RefreshUsedAt           *time.Time
	ReplaySeal              []byte
	RevokedReason           *string
	AuthorityKind           string
	AuthorityWorkspaceID    *uuid.UUID
	AuthorityConnectionID   *uuid.UUID
	LocalAuthenticatedAt    *time.Time
	RecoveryAuthenticatedAt *time.Time
	AuthorityVersion        int64
}

type SessionWorkspaceAssurance struct {
	SessionID          uuid.UUID
	WorkspaceID        uuid.UUID
	UserID             uuid.UUID
	ConnectionID       uuid.UUID
	IdentityID         uuid.UUID
	AuthenticatedAt    time.Time
	ValidUntil         time.Time
	PolicyVersion      int64
	AccessVersion      int64
	ConnectionVersion  int64
	IdentityVersion    int64
	EntitlementVersion int64
	SessionVersion     int64
	RevokedAt          *time.Time
}

type SipAccount struct {
	WorkspaceID     uuid.UUID
	Provider        string
	Host            string
	Transport       string
	Username        string
	AuthUsername    string
	Port            int32
	PasswordEnc     []byte
	CallerID        string
	OutboundPrefix  string
	AllowedPrefixes []string
	TrunkID         string
	Enabled         bool
	LastError       string
	UpdatedAt       time.Time
	UpdatedBy       *uuid.UUID
}

type SipCall struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	RoomID              *uuid.UUID
	Number              string
	Direction           string
	StartedBy           *uuid.UUID
	ParticipantIdentity string
	SipCallID           string
	Status              string
	Reason              string
	EndedBy             *uuid.UUID
	StartedAt           time.Time
	AnsweredAt          *time.Time
	EndedAt             *time.Time
}

type Sticker struct {
	ID        uuid.UUID
	PackID    uuid.UUID
	FileID    *uuid.UUID
	Emoji     string
	Position  int32
	Width     int32
	Height    int32
	Animated  bool
	CreatedAt time.Time
	DeletedAt *time.Time
}

type StickerPack struct {
	ID             uuid.UUID
	WorkspaceID    *uuid.UUID
	Name           string
	ShortName      string
	CoverStickerID *uuid.UUID
	CreatedBy      *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
}

type Task struct {
	ID               uuid.UUID
	BoardID          uuid.UUID
	Number           int32
	Title            string
	Description      string
	StatusID         uuid.UUID
	Priority         int16
	CreatedBy        *uuid.UUID
	Estimate         *int16
	StartOn          pgtype.Date
	DueOn            pgtype.Date
	ParentID         *uuid.UUID
	MilestoneID      *uuid.UUID
	Position         float64
	RoomID           uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	StartedAt        *time.Time
	CompletedAt      *time.Time
	CompletedBy      *uuid.UUID
	ArchivedAt       *time.Time
	ApprovalRequired int16
	TaskMilestoneID  *uuid.UUID
}

type TaskActivity struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	BoardID   uuid.UUID
	ActorID   *uuid.UUID
	Kind      string
	Before    []byte
	After     []byte
	CreatedAt time.Time
	RuleID    *uuid.UUID
}

type TaskApprover struct {
	TaskID      uuid.UUID
	UserID      uuid.UUID
	State       string
	Comment     string
	DecidedAt   *time.Time
	AddedBy     *uuid.UUID
	AddedAt     time.Time
	RequestedAt time.Time
	Reminders   int16
	RemindedAt  *time.Time
}

type TaskAssignee struct {
	TaskID     uuid.UUID
	UserID     uuid.UUID
	IsLead     bool
	Note       string
	AssignedBy *uuid.UUID
	AssignedAt time.Time
}

type TaskAttachment struct {
	TaskID   uuid.UUID
	FileID   uuid.UUID
	Position int16
}

type TaskChecklist struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	Title     string
	Position  int32
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type TaskChecklistItem struct {
	ID          uuid.UUID
	ChecklistID uuid.UUID
	TaskID      uuid.UUID
	Text        string
	Done        bool
	DoneBy      *uuid.UUID
	DoneAt      *time.Time
	Position    float64
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
}

type TaskGitLink struct {
	ID        uuid.UUID
	TaskID    uuid.UUID
	Kind      string
	Provider  string
	Repo      string
	Ref       string
	Title     string
	Url       string
	State     string
	Author    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TaskLabel struct {
	TaskID  uuid.UUID
	LabelID uuid.UUID
}

type TaskMilestone struct {
	ID          uuid.UUID
	TaskID      uuid.UUID
	Name        string
	DueOn       pgtype.Date
	Position    float64
	CompletedAt *time.Time
	CompletedBy *uuid.UUID
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type TaskRelation struct {
	TaskID    uuid.UUID
	RelatedID uuid.UUID
	Kind      string
	CreatedBy *uuid.UUID
	CreatedAt time.Time
}

type TaskSubscriber struct {
	TaskID     uuid.UUID
	UserID     uuid.UUID
	Muted      bool
	NotifiedAt *time.Time
	SeenAt     *time.Time
}

type User struct {
	ID                uuid.UUID
	Email             *string
	PasswordHash      *string
	DisplayName       string
	AvatarFileID      *uuid.UUID
	StatusText        string
	Settings          []byte
	CreatedAt         time.Time
	DisabledAt        *time.Time
	StatusEmoji       string
	StatusExpiresAt   *time.Time
	IsGuest           bool
	GuestExpiresAt    *time.Time
	Timezone          *string
	EmailVerifiedAt   *time.Time
	PendingEmail      *string
	Locale            *string
	PresenceStatus    *int16
	PresenceUntil     *time.Time
	IsBot             bool
	BirthdayDay       *int16
	BirthdayMonth     *int16
	BirthdayYear      *int16
	BirthdayHidden    bool
	EventReminders    []int16
	EventRemindersDnd bool
	StorageQuotaBytes *int64
	WorkStartMin      int16
	WorkEndMin        int16
	WorkDays          []int16
}

type UserNote struct {
	AuthorID  uuid.UUID
	SubjectID uuid.UUID
	Text      string
	UpdatedAt time.Time
}

type UserStickerPack struct {
	UserID   uuid.UUID
	PackID   uuid.UUID
	Position int32
	AddedAt  time.Time
}

type Workspace struct {
	ID                      uuid.UUID
	Slug                    string
	Name                    string
	IconFileID              *uuid.UUID
	Visibility              string
	OwnerID                 uuid.UUID
	CreatedAt               time.Time
	DefaultAudioBitrateKbps int32
	DefaultMaxStreamPreset  string
	DefaultMaxStreams       int32
	StorageQuotaBytes       int64
	StorageUsedBytes        int64
	AllowSelfNickname       bool
	DefaultCameraLimit      int32
	SuspendedAt             *time.Time
	SuspendedReason         string
	SuspendedBy             *uuid.UUID
	TimeFormat              string
	SipEnabled              bool
}

type WorkspaceAdminLog struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	Reason      string
	CreatedAt   time.Time
}

type WorkspaceApp struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Url         string
	IconFileID  *uuid.UUID
	Position    float64
	CreatedBy   *uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type WorkspaceBackground struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	FileID      uuid.UUID
	Position    int16
	CreatedAt   time.Time
}

type WorkspaceBadge struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	FileID      uuid.UUID
	Position    int16
	CreatedAt   time.Time
}

type WorkspaceBan struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Email       *string
	Reason      string
	BannedBy    *uuid.UUID
	CreatedAt   time.Time
}

type WorkspaceDirectory struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	Name                string
	Host                string
	Url                 string
	AllowedGroupDns     []string
	Generation          int64
	Port                int32
	BaseDn              string
	BindDn              string
	BindSecretBox       []byte
	CaPem               string
	SyncIntervalSeconds int32
	MaxStalenessSeconds int32
	Version             int64
	LastSuccessAt       *time.Time
	CursorBox           []byte
	LastError           string
	DisabledAt          *time.Time
	CreatedAt           time.Time
}

type WorkspaceExternalIdentity struct {
	ID           uuid.UUID
	WorkspaceID  uuid.UUID
	ConnectionID uuid.UUID
	UserID       uuid.UUID
	Issuer       string
	Subject      string
	Status       string
	Version      int64
	LinkedAt     time.Time
}

type WorkspaceIdentityAccess struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Status      string
	Version     int64
	Reason      string
	UpdatedAt   time.Time
}

type WorkspaceIdentityAudit struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Action      string
	TargetID    *uuid.UUID
	Outcome     string
	CreatedAt   time.Time
}

type WorkspaceIdentityConnection struct {
	ID              uuid.UUID
	WorkspaceID     uuid.UUID
	Name            string
	Status          string
	TenantID        string
	Provider        string
	Issuer          string
	ClientID        string
	ClientSecretBox []byte
	Scopes          []string
	Version         int64
	TestedVersion   *int64
	TestedAt        *time.Time
	DisabledAt      *time.Time
	CreatedBy       *uuid.UUID
	CreatedAt       time.Time
}

type WorkspaceIdentityGrant struct {
	WorkspaceID uuid.UUID
	Feature     string
	Enabled     bool
	Source      string
	ValidUntil  *time.Time
	RevokedAt   *time.Time
	Version     int64
	UpdatedBy   *uuid.UUID
	UpdatedAt   time.Time
}

type WorkspaceIdentityPolicy struct {
	WorkspaceID            uuid.UUID
	EntitlementVersion     int64
	Mode                   string
	Version                int64
	AssuranceMaxAgeSeconds int32
	UpdatedBy              *uuid.UUID
	UpdatedAt              time.Time
}

type WorkspaceIdentityRecoveryCode struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	OwnerID     uuid.UUID
	CodeHash    []byte
	ExpiresAt   time.Time
	ConsumedAt  *time.Time
	CreatedAt   time.Time
}

type WorkspaceIntegration struct {
	WorkspaceID uuid.UUID
	Kind        string
	TokenEnc    []byte
	DeviceID    string
	DeviceName  string
	Account     string
	WebUrl      string
	PairedBy    *uuid.UUID
	PairedAt    time.Time
	RevokedAt   *time.Time
}

type WorkspaceInvite struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Code        string
	CreatedBy   uuid.UUID
	MaxUses     int32
	Uses        int32
	ExpiresAt   *time.Time
	CreatedAt   time.Time
}

type WorkspaceMember struct {
	WorkspaceID      uuid.UUID
	UserID           uuid.UUID
	Role             string
	Nickname         string
	JoinedAt         time.Time
	BadgeID          *uuid.UUID
	AchievementCount int32
}

type WorkspaceNotificationSetting struct {
	UserID      uuid.UUID
	WorkspaceID uuid.UUID
	Level       string
	MutedUntil  *time.Time
	TaskLevel   string
}

type WorkspacePlan struct {
	WorkspaceID uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	UpdatedBy   *uuid.UUID
	UpdatedAt   time.Time
}

type WorkspacePlanLog struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	CreatedAt   time.Time
}

type WorkspaceRole struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Color       int32
	Position    int32
	Permissions int64
	Builtin     *string
	Mentionable bool
	CreatedAt   time.Time
}

type WorkspaceSound struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	Name        string
	Emoji       string
	FileID      uuid.UUID
	DurationMs  int32
	Position    int16
	CreatedAt   time.Time
}
