// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminSearchWorkspaces = `-- name: AdminSearchWorkspaces :many
SELECT w.id
FROM workspaces w
JOIN users u ON u.id = w.owner_id
WHERE $1::text = ''
   OR w.name ILIKE '%' || $1::text || '%'
   OR w.slug ILIKE '%' || $1::text || '%'
   OR u.email::text ILIKE '%' || $1::text || '%'
ORDER BY w.id DESC
LIMIT 50
`

// Superadmin search by name, slug or owner email (pattern already escaped for LIKE; empty =
// all), newest first.
func (q *Queries) AdminSearchWorkspaces(ctx context.Context, pattern string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, adminSearchWorkspaces, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminWorkspaceDetails = `-- name: AdminWorkspaceDetails :many
SELECT w.id, w.slug, w.name, w.icon_file_id, w.visibility, w.owner_id, w.created_at, w.default_audio_bitrate_kbps, w.default_max_stream_preset, w.default_max_streams, w.storage_quota_bytes, w.storage_used_bytes, w.allow_self_nickname, w.default_camera_limit, w.suspended_at, w.suspended_reason, w.suspended_by, w.time_format, w.sip_enabled, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days, u.hide_message_text_in_notifications, u.username, u.phone,
    p.note AS plan_note, p.updated_by AS plan_updated_by, p.updated_at AS plan_updated_at,
    sb.email AS suspended_by_email,
    (SELECT count(*) FROM workspace_members m WHERE m.workspace_id = w.id AND m.role <> 'guest')::integer AS members,
    (SELECT count(*) FROM rooms r WHERE r.workspace_id = w.id AND r.archived_at IS NULL AND r.type <> 'task')::integer AS rooms,
    (SELECT count(*) FROM workspace_members m JOIN users bu ON bu.id = m.user_id WHERE m.workspace_id = w.id AND bu.is_bot)::integer AS bots,
    (SELECT count(*) FROM sticker_packs sp WHERE sp.workspace_id = w.id AND sp.deleted_at IS NULL)::integer AS sticker_packs,
    coalesce((SELECT max(lm.created_at) FROM rooms r
        CROSS JOIN LATERAL (SELECT m.created_at FROM messages m WHERE m.room_id = r.id ORDER BY m.id DESC LIMIT 1) lm
        WHERE r.workspace_id = w.id), 'epoch'::timestamptz)::timestamptz AS last_activity
FROM workspaces w
JOIN users u ON u.id = w.owner_id
LEFT JOIN workspace_plans p ON p.workspace_id = w.id
LEFT JOIN users sb ON sb.id = w.suspended_by
WHERE w.id = ANY($1::uuid[])
`

type AdminWorkspaceDetailsRow struct {
	Workspace        Workspace
	User             User
	PlanNote         *string
	PlanUpdatedBy    *uuid.UUID
	PlanUpdatedAt    *time.Time
	SuspendedByEmail *string
	Members          int32
	Rooms            int32
	Bots             int32
	StickerPacks     int32
	LastActivity     time.Time
}

// Workspaces with their owner, plan row and usage (members without guests, live rooms,
// time of the newest message; epoch = none).
func (q *Queries) AdminWorkspaceDetails(ctx context.Context, ids []uuid.UUID) ([]AdminWorkspaceDetailsRow, error) {
	rows, err := q.db.Query(ctx, adminWorkspaceDetails, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminWorkspaceDetailsRow{}
	for rows.Next() {
		var i AdminWorkspaceDetailsRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Slug,
			&i.Workspace.Name,
			&i.Workspace.IconFileID,
			&i.Workspace.Visibility,
			&i.Workspace.OwnerID,
			&i.Workspace.CreatedAt,
			&i.Workspace.DefaultAudioBitrateKbps,
			&i.Workspace.DefaultMaxStreamPreset,
			&i.Workspace.DefaultMaxStreams,
			&i.Workspace.StorageQuotaBytes,
			&i.Workspace.StorageUsedBytes,
			&i.Workspace.AllowSelfNickname,
			&i.Workspace.DefaultCameraLimit,
			&i.Workspace.SuspendedAt,
			&i.Workspace.SuspendedReason,
			&i.Workspace.SuspendedBy,
			&i.Workspace.TimeFormat,
			&i.Workspace.SipEnabled,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.User.HideMessageTextInNotifications,
			&i.User.Username,
			&i.User.Phone,
			&i.PlanNote,
			&i.PlanUpdatedBy,
			&i.PlanUpdatedAt,
			&i.SuspendedByEmail,
			&i.Members,
			&i.Rooms,
			&i.Bots,
			&i.StickerPacks,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspacePlan = `-- name: GetWorkspacePlan :one
SELECT workspace_id, plan, limits, valid_until, note, updated_by, updated_at, source FROM workspace_plans WHERE workspace_id = $1
`

func (q *Queries) GetWorkspacePlan(ctx context.Context, workspaceID uuid.UUID) (WorkspacePlan, error) {
	row := q.db.QueryRow(ctx, getWorkspacePlan, workspaceID)
	var i WorkspacePlan
	err := row.Scan(
		&i.WorkspaceID,
		&i.Plan,
		&i.Limits,
		&i.ValidUntil,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}

const insertPlanLog = `-- name: InsertPlanLog :exec
INSERT INTO workspace_plan_log (workspace_id, actor_id, plan, limits, valid_until, note)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertPlanLogParams struct {
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
}

func (q *Queries) InsertPlanLog(ctx context.Context, arg InsertPlanLogParams) error {
	_, err := q.db.Exec(ctx, insertPlanLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Plan,
		arg.Limits,
		arg.ValidUntil,
		arg.Note,
	)
	return err
}

const listPlanLog = `-- name: ListPlanLog :many
SELECT l.id, l.workspace_id, l.actor_id, l.plan, l.limits, l.valid_until, l.note, l.created_at, l.source, u.email AS actor_email
FROM workspace_plan_log l
LEFT JOIN users u ON u.id = l.actor_id
WHERE l.workspace_id = $1
ORDER BY l.id DESC
LIMIT 100
`

type ListPlanLogRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	CreatedAt   time.Time
	Source      string
	ActorEmail  *string
}

func (q *Queries) ListPlanLog(ctx context.Context, workspaceID uuid.UUID) ([]ListPlanLogRow, error) {
	rows, err := q.db.Query(ctx, listPlanLog, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanLogRow{}
	for rows.Next() {
		var i ListPlanLogRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.Plan,
			&i.Limits,
			&i.ValidUntil,
			&i.Note,
			&i.CreatedAt,
			&i.Source,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWorkspacePlan = `-- name: UpsertWorkspacePlan :one
INSERT INTO workspace_plans (workspace_id, plan, limits, valid_until, note, updated_by, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (workspace_id) DO UPDATE SET
    plan = EXCLUDED.plan, limits = EXCLUDED.limits, valid_until = EXCLUDED.valid_until,
    note = EXCLUDED.note, updated_by = EXCLUDED.updated_by, updated_at = now()
WHERE workspace_plans.source = 'manual'
RETURNING workspace_id, plan, limits, valid_until, note, updated_by, updated_at, source
`

type UpsertWorkspacePlanParams struct {
	WorkspaceID uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	UpdatedBy   *uuid.UUID
}

// The manual plan (superadmin). A billing-managed plan (source = 'billing', ADR-0080) is not
// touched: no row comes back (409 BILLING_PLAN_MANAGED).
func (q *Queries) UpsertWorkspacePlan(ctx context.Context, arg UpsertWorkspacePlanParams) (WorkspacePlan, error) {
	row := q.db.QueryRow(ctx, upsertWorkspacePlan,
		arg.WorkspaceID,
		arg.Plan,
		arg.Limits,
		arg.ValidUntil,
		arg.Note,
		arg.UpdatedBy,
	)
	var i WorkspacePlan
	err := row.Scan(
		&i.WorkspaceID,
		&i.Plan,
		&i.Limits,
		&i.ValidUntil,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Source,
	)
	return i, err
}
