// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const adminSearchWorkspaces = `-- name: AdminSearchWorkspaces :many
SELECT w.id
FROM workspaces w
JOIN users u ON u.id = w.owner_id
WHERE $1::text = ''
   OR w.name ILIKE '%' || $1::text || '%'
   OR w.slug ILIKE '%' || $1::text || '%'
   OR u.email::text ILIKE '%' || $1::text || '%'
ORDER BY w.id DESC
LIMIT 50
`

// Superadmin search by name, slug or owner email (pattern already escaped for LIKE; empty =
// all), newest first.
func (q *Queries) AdminSearchWorkspaces(ctx context.Context, pattern string) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, adminSearchWorkspaces, pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminWorkspaceDetails = `-- name: AdminWorkspaceDetails :many
SELECT w.id, w.slug, w.name, w.icon_file_id, w.visibility, w.owner_id, w.created_at, w.default_audio_bitrate_kbps, w.default_max_stream_preset, w.default_max_streams, w.storage_quota_bytes, w.storage_used_bytes, w.allow_self_nickname, w.default_camera_limit, w.suspended_at, w.suspended_reason, w.suspended_by, w.time_format, w.sip_enabled, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot, u.birthday_day, u.birthday_month, u.birthday_year, u.birthday_hidden, u.event_reminders, u.event_reminders_dnd, u.storage_quota_bytes, u.work_start_min, u.work_end_min, u.work_days, u.hide_message_text_in_notifications, u.username, u.phone,
    p.note AS plan_note, p.updated_by AS plan_updated_by, p.updated_at AS plan_updated_at,
    sb.email AS suspended_by_email,
    (SELECT count(*) FROM workspace_members m WHERE m.workspace_id = w.id AND m.role <> 'guest')::integer AS members,
    (SELECT count(*) FROM rooms r WHERE r.workspace_id = w.id AND r.archived_at IS NULL AND r.type <> 'task')::integer AS rooms,
    (SELECT count(*) FROM workspace_members m JOIN users bu ON bu.id = m.user_id WHERE m.workspace_id = w.id AND bu.is_bot)::integer AS bots,
    (SELECT count(*) FROM sticker_packs sp WHERE sp.workspace_id = w.id AND sp.deleted_at IS NULL)::integer AS sticker_packs,
    coalesce((SELECT max(lm.created_at) FROM rooms r
        CROSS JOIN LATERAL (SELECT m.created_at FROM messages m WHERE m.room_id = r.id ORDER BY m.id DESC LIMIT 1) lm
        WHERE r.workspace_id = w.id), 'epoch'::timestamptz)::timestamptz AS last_activity
FROM workspaces w
JOIN users u ON u.id = w.owner_id
LEFT JOIN workspace_plans p ON p.workspace_id = w.id
LEFT JOIN users sb ON sb.id = w.suspended_by
WHERE w.id = ANY($1::uuid[])
`

type AdminWorkspaceDetailsRow struct {
	Workspace        Workspace
	User             User
	PlanNote         *string
	PlanUpdatedBy    *uuid.UUID
	PlanUpdatedAt    *time.Time
	SuspendedByEmail *string
	Members          int32
	Rooms            int32
	Bots             int32
	StickerPacks     int32
	LastActivity     time.Time
}

// Workspaces with their owner, plan row and usage (members without guests, live rooms,
// time of the newest message; epoch = none).
func (q *Queries) AdminWorkspaceDetails(ctx context.Context, ids []uuid.UUID) ([]AdminWorkspaceDetailsRow, error) {
	rows, err := q.db.Query(ctx, adminWorkspaceDetails, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminWorkspaceDetailsRow{}
	for rows.Next() {
		var i AdminWorkspaceDetailsRow
		if err := rows.Scan(
			&i.Workspace.ID,
			&i.Workspace.Slug,
			&i.Workspace.Name,
			&i.Workspace.IconFileID,
			&i.Workspace.Visibility,
			&i.Workspace.OwnerID,
			&i.Workspace.CreatedAt,
			&i.Workspace.DefaultAudioBitrateKbps,
			&i.Workspace.DefaultMaxStreamPreset,
			&i.Workspace.DefaultMaxStreams,
			&i.Workspace.StorageQuotaBytes,
			&i.Workspace.StorageUsedBytes,
			&i.Workspace.AllowSelfNickname,
			&i.Workspace.DefaultCameraLimit,
			&i.Workspace.SuspendedAt,
			&i.Workspace.SuspendedReason,
			&i.Workspace.SuspendedBy,
			&i.Workspace.TimeFormat,
			&i.Workspace.SipEnabled,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.User.BirthdayDay,
			&i.User.BirthdayMonth,
			&i.User.BirthdayYear,
			&i.User.BirthdayHidden,
			&i.User.EventReminders,
			&i.User.EventRemindersDnd,
			&i.User.StorageQuotaBytes,
			&i.User.WorkStartMin,
			&i.User.WorkEndMin,
			&i.User.WorkDays,
			&i.User.HideMessageTextInNotifications,
			&i.User.Username,
			&i.User.Phone,
			&i.PlanNote,
			&i.PlanUpdatedBy,
			&i.PlanUpdatedAt,
			&i.SuspendedByEmail,
			&i.Members,
			&i.Rooms,
			&i.Bots,
			&i.StickerPacks,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkspacePlan = `-- name: GetWorkspacePlan :one
SELECT workspace_id, plan, limits, valid_until, note, updated_by, updated_at, source, display_name, description FROM workspace_plans WHERE workspace_id = $1
`

func (q *Queries) GetWorkspacePlan(ctx context.Context, workspaceID uuid.UUID) (WorkspacePlan, error) {
	row := q.db.QueryRow(ctx, getWorkspacePlan, workspaceID)
	var i WorkspacePlan
	err := row.Scan(
		&i.WorkspaceID,
		&i.Plan,
		&i.Limits,
		&i.ValidUntil,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Source,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const getWorkspacePlanUsage = `-- name: GetWorkspacePlanUsage :one
SELECT
    (SELECT count(*) FROM workspace_members m WHERE m.workspace_id = $1::uuid AND m.role <> 'guest')::bigint AS members,
    (SELECT count(*) FROM workspace_members m JOIN users u ON u.id = m.user_id
        WHERE m.workspace_id = $1::uuid AND u.is_bot)::bigint AS bots,
    (SELECT w.storage_used_bytes FROM workspaces w WHERE w.id = $1::uuid)::bigint AS storage_bytes,
    (SELECT count(*) FROM boards b WHERE b.workspace_id = $1::uuid)::bigint AS boards,
    (SELECT count(*) FROM sticker_packs p WHERE p.workspace_id = $1::uuid AND p.deleted_at IS NULL)::bigint AS sticker_packs,
    (SELECT count(*) FROM stickers s JOIN sticker_packs p ON p.id = s.pack_id AND p.deleted_at IS NULL
        WHERE p.workspace_id = $1::uuid AND s.deleted_at IS NULL)::bigint AS stickers,
    (SELECT coalesce(array_agg(r.user_limit), '{}') FROM rooms r
        WHERE r.workspace_id = $1::uuid AND r.type = 'voice' AND r.archived_at IS NULL AND r.user_limit > 0)::integer[] AS room_user_limits,
    (SELECT coalesce(max(x.n), 0) FROM (SELECT count(*) AS n FROM board_forms f JOIN boards b ON b.id = f.board_id
        WHERE b.workspace_id = $1::uuid GROUP BY f.board_id) x)::bigint AS max_board_forms,
    (SELECT count(*) FROM board_rules r JOIN boards b ON b.id = r.board_id
        WHERE b.workspace_id = $1::uuid AND r.enabled)::bigint AS automations,
    (SELECT count(*) FROM board_webhooks h JOIN boards b ON b.id = h.board_id
        WHERE b.workspace_id = $1::uuid AND h.disabled_at IS NULL)::bigint AS board_webhooks,
    (SELECT count(*) FROM sip_accounts a WHERE a.workspace_id = $1::uuid AND a.enabled)::bigint AS telephony,
    (SELECT count(*) FROM workspace_identity_connections c WHERE c.workspace_id = $1::uuid AND c.status = 'active')::bigint AS sso,
    (SELECT count(*) FROM workspace_directories d WHERE d.workspace_id = $1::uuid AND d.disabled_at IS NULL)::bigint AS directories,
    (SELECT count(*) FROM oauth_clients o WHERE o.workspace_id = $1::uuid AND o.disabled_at IS NULL)::bigint AS oauth_apps,
    (SELECT coalesce(array_agg(g.feature), '{}') FROM workspace_identity_grants g
        WHERE g.workspace_id = $1::uuid AND g.source = 'onprem_enterprise' AND g.enabled AND g.revoked_at IS NULL)::text[] AS operator_features
`

type GetWorkspacePlanUsageRow struct {
	Members          int64
	Bots             int64
	StorageBytes     int64
	Boards           int64
	StickerPacks     int64
	Stickers         int64
	RoomUserLimits   []int32
	MaxBoardForms    int64
	Automations      int64
	BoardWebhooks    int64
	Telephony        int64
	Sso              int64
	Directories      int64
	OauthApps        int64
	OperatorFeatures []string
}

// What a plan transition is checked against (ADR-0086, plans.Violations): every counted limit and
// every plan-gated feature in use, in one read. Identity features granted by the operator
// (onprem_enterprise) do not depend on the plan and come back in operator_features.
func (q *Queries) GetWorkspacePlanUsage(ctx context.Context, workspaceID uuid.UUID) (GetWorkspacePlanUsageRow, error) {
	row := q.db.QueryRow(ctx, getWorkspacePlanUsage, workspaceID)
	var i GetWorkspacePlanUsageRow
	err := row.Scan(
		&i.Members,
		&i.Bots,
		&i.StorageBytes,
		&i.Boards,
		&i.StickerPacks,
		&i.Stickers,
		&i.RoomUserLimits,
		&i.MaxBoardForms,
		&i.Automations,
		&i.BoardWebhooks,
		&i.Telephony,
		&i.Sso,
		&i.Directories,
		&i.OauthApps,
		&i.OperatorFeatures,
	)
	return i, err
}

const insertPlanLog = `-- name: InsertPlanLog :exec
INSERT INTO workspace_plan_log (workspace_id, actor_id, plan, limits, valid_until, note, display_name, description)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPlanLogParams struct {
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	DisplayName string
	Description string
}

func (q *Queries) InsertPlanLog(ctx context.Context, arg InsertPlanLogParams) error {
	_, err := q.db.Exec(ctx, insertPlanLog,
		arg.WorkspaceID,
		arg.ActorID,
		arg.Plan,
		arg.Limits,
		arg.ValidUntil,
		arg.Note,
		arg.DisplayName,
		arg.Description,
	)
	return err
}

const listPlanLog = `-- name: ListPlanLog :many
SELECT l.id, l.workspace_id, l.actor_id, l.plan, l.limits, l.valid_until, l.note, l.created_at, l.source, l.display_name, l.description, u.email AS actor_email
FROM workspace_plan_log l
LEFT JOIN users u ON u.id = l.actor_id
WHERE l.workspace_id = $1
ORDER BY l.id DESC
LIMIT 100
`

type ListPlanLogRow struct {
	ID          uuid.UUID
	WorkspaceID uuid.UUID
	ActorID     *uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	CreatedAt   time.Time
	Source      string
	DisplayName string
	Description string
	ActorEmail  *string
}

func (q *Queries) ListPlanLog(ctx context.Context, workspaceID uuid.UUID) ([]ListPlanLogRow, error) {
	rows, err := q.db.Query(ctx, listPlanLog, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlanLogRow{}
	for rows.Next() {
		var i ListPlanLogRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.ActorID,
			&i.Plan,
			&i.Limits,
			&i.ValidUntil,
			&i.Note,
			&i.CreatedAt,
			&i.Source,
			&i.DisplayName,
			&i.Description,
			&i.ActorEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockWorkspacePlanRow = `-- name: LockWorkspacePlanRow :one
SELECT workspace_id, plan, limits, valid_until, note, updated_by, updated_at, source, display_name, description FROM workspace_plans WHERE workspace_id = $1 FOR UPDATE
`

// The plan row under a lock (ADR-0086): a self-serve start decides whether a superadmin assigned the
// plan while the superadmin's upsert waits for it.
func (q *Queries) LockWorkspacePlanRow(ctx context.Context, workspaceID uuid.UUID) (WorkspacePlan, error) {
	row := q.db.QueryRow(ctx, lockWorkspacePlanRow, workspaceID)
	var i WorkspacePlan
	err := row.Scan(
		&i.WorkspaceID,
		&i.Plan,
		&i.Limits,
		&i.ValidUntil,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Source,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}

const upsertWorkspacePlan = `-- name: UpsertWorkspacePlan :one
INSERT INTO workspace_plans (workspace_id, plan, limits, valid_until, note, updated_by, updated_at, display_name, description)
VALUES ($1, $2, $3, $4, $5, $6, now(), $7, $8)
ON CONFLICT (workspace_id) DO UPDATE SET
    plan = EXCLUDED.plan, limits = EXCLUDED.limits, valid_until = EXCLUDED.valid_until,
    note = EXCLUDED.note, updated_by = EXCLUDED.updated_by, updated_at = now(),
    display_name = EXCLUDED.display_name, description = EXCLUDED.description
WHERE workspace_plans.source = 'manual'
RETURNING workspace_id, plan, limits, valid_until, note, updated_by, updated_at, source, display_name, description
`

type UpsertWorkspacePlanParams struct {
	WorkspaceID uuid.UUID
	Plan        string
	Limits      []byte
	ValidUntil  *time.Time
	Note        string
	UpdatedBy   *uuid.UUID
	DisplayName string
	Description string
}

// The manual plan (superadmin). A billing-managed plan (source = 'billing', ADR-0080) is not
// touched: no row comes back (409 BILLING_PLAN_MANAGED).
func (q *Queries) UpsertWorkspacePlan(ctx context.Context, arg UpsertWorkspacePlanParams) (WorkspacePlan, error) {
	row := q.db.QueryRow(ctx, upsertWorkspacePlan,
		arg.WorkspaceID,
		arg.Plan,
		arg.Limits,
		arg.ValidUntil,
		arg.Note,
		arg.UpdatedBy,
		arg.DisplayName,
		arg.Description,
	)
	var i WorkspacePlan
	err := row.Scan(
		&i.WorkspaceID,
		&i.Plan,
		&i.Limits,
		&i.ValidUntil,
		&i.Note,
		&i.UpdatedBy,
		&i.UpdatedAt,
		&i.Source,
		&i.DisplayName,
		&i.Description,
	)
	return i, err
}
