// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_token_hash, device_name, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version
`

type CreateSessionParams struct {
	UserID           uuid.UUID
	RefreshTokenHash []byte
	DeviceName       string
	Ip               string
	UserAgent        string
	ExpiresAt        time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshTokenHash,
		arg.DeviceName,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RefreshGen,
		&i.RefreshUsedAt,
		&i.ReplaySeal,
		&i.RevokedReason,
		&i.AuthorityKind,
		&i.AuthorityWorkspaceID,
		&i.AuthorityConnectionID,
		&i.LocalAuthenticatedAt,
		&i.RecoveryAuthenticatedAt,
		&i.AuthorityVersion,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RefreshGen,
		&i.RefreshUsedAt,
		&i.ReplaySeal,
		&i.RevokedReason,
		&i.AuthorityKind,
		&i.AuthorityWorkspaceID,
		&i.AuthorityConnectionID,
		&i.LocalAuthenticatedAt,
		&i.RecoveryAuthenticatedAt,
		&i.AuthorityVersion,
	)
	return i, err
}

const getSessionForUpdate = `-- name: GetSessionForUpdate :one
SELECT id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version FROM sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetSessionForUpdate(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUpdate, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RefreshGen,
		&i.RefreshUsedAt,
		&i.ReplaySeal,
		&i.RevokedReason,
		&i.AuthorityKind,
		&i.AuthorityWorkspaceID,
		&i.AuthorityConnectionID,
		&i.LocalAuthenticatedAt,
		&i.RecoveryAuthenticatedAt,
		&i.AuthorityVersion,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version FROM sessions
WHERE user_id = $1 AND revoked_at IS NULL AND expires_at > now()
ORDER BY last_seen_at DESC
`

func (q *Queries) ListActiveSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.PrevRefreshTokenHash,
			&i.RotatedAt,
			&i.DeviceName,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RefreshGen,
			&i.RefreshUsedAt,
			&i.ReplaySeal,
			&i.RevokedReason,
			&i.AuthorityKind,
			&i.AuthorityWorkspaceID,
			&i.AuthorityConnectionID,
			&i.LocalAuthenticatedAt,
			&i.RecoveryAuthenticatedAt,
			&i.AuthorityVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByIDs = `-- name: ListSessionsByIDs :many
SELECT id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version FROM sessions WHERE id = ANY($1::uuid[])
`

func (q *Queries) ListSessionsByIDs(ctx context.Context, ids []uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RefreshTokenHash,
			&i.PrevRefreshTokenHash,
			&i.RotatedAt,
			&i.DeviceName,
			&i.Ip,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
			&i.RefreshGen,
			&i.RefreshUsedAt,
			&i.ReplaySeal,
			&i.RevokedReason,
			&i.AuthorityKind,
			&i.AuthorityWorkspaceID,
			&i.AuthorityConnectionID,
			&i.LocalAuthenticatedAt,
			&i.RecoveryAuthenticatedAt,
			&i.AuthorityVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshGenUsed = `-- name: MarkRefreshGenUsed :exec
UPDATE sessions SET refresh_used_at = now(), replay_seal = NULL
WHERE id = $1 AND refresh_gen = $2 AND refresh_used_at IS NULL AND revoked_at IS NULL
`

type MarkRefreshGenUsedParams struct {
	ID         uuid.UUID
	RefreshGen int64
}

// The first use of refresh generation refresh_gen (an access token minted for it was presented).
// The seal is not needed any more: the previous token is reuse from now on.
func (q *Queries) MarkRefreshGenUsed(ctx context.Context, arg MarkRefreshGenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshGenUsed, arg.ID, arg.RefreshGen)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :many
UPDATE sessions SET revoked_at = now(), revoked_reason = $2::text, replay_seal = NULL
WHERE user_id = $1 AND revoked_at IS NULL
RETURNING id
`

type RevokeAllUserSessionsParams struct {
	UserID uuid.UUID
	Reason string
}

func (q *Queries) RevokeAllUserSessions(ctx context.Context, arg RevokeAllUserSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeAllUserSessions, arg.UserID, arg.Reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeOtherUserSessions = `-- name: RevokeOtherUserSessions :many
UPDATE sessions SET revoked_at = now(), revoked_reason = $3::text, replay_seal = NULL
WHERE user_id = $1 AND id <> $2 AND revoked_at IS NULL
RETURNING id
`

type RevokeOtherUserSessionsParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
	Reason string
}

func (q *Queries) RevokeOtherUserSessions(ctx context.Context, arg RevokeOtherUserSessionsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, revokeOtherUserSessions, arg.UserID, arg.ID, arg.Reason)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSession = `-- name: RevokeSession :execrows
UPDATE sessions SET revoked_at = now(), revoked_reason = $2::text, replay_seal = NULL
WHERE id = $1 AND revoked_at IS NULL
`

type RevokeSessionParams struct {
	ID     uuid.UUID
	Reason string
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserSession = `-- name: RevokeUserSession :execrows
UPDATE sessions SET revoked_at = now(), revoked_reason = $3::text, replay_seal = NULL
WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Reason string
}

func (q *Queries) RevokeUserSession(ctx context.Context, arg RevokeUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeUserSession, arg.ID, arg.UserID, arg.Reason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSession = `-- name: RotateSession :one
UPDATE sessions SET
    prev_refresh_token_hash = refresh_token_hash,
    refresh_token_hash      = $2,
    refresh_gen             = refresh_gen + 1,
    refresh_used_at         = NULL,
    replay_seal             = $6,
    rotated_at              = now(),
    last_seen_at            = now(),
    expires_at              = $3,
    ip                      = $4,
    user_agent              = $5
WHERE id = $1
RETURNING id, user_id, refresh_token_hash, prev_refresh_token_hash, rotated_at, device_name, ip, user_agent, created_at, last_seen_at, expires_at, revoked_at, refresh_gen, refresh_used_at, replay_seal, revoked_reason, authority_kind, authority_workspace_id, authority_connection_id, local_authenticated_at, recovery_authenticated_at, authority_version
`

type RotateSessionParams struct {
	ID               uuid.UUID
	RefreshTokenHash []byte
	ExpiresAt        time.Time
	Ip               string
	UserAgent        string
	ReplaySeal       []byte
}

// A new refresh generation: unused, with its secret sealed under the previous one (replay.go).
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, rotateSession,
		arg.ID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
		arg.ReplaySeal,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshTokenHash,
		&i.PrevRefreshTokenHash,
		&i.RotatedAt,
		&i.DeviceName,
		&i.Ip,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.RefreshGen,
		&i.RefreshUsedAt,
		&i.ReplaySeal,
		&i.RevokedReason,
		&i.AuthorityKind,
		&i.AuthorityWorkspaceID,
		&i.AuthorityConnectionID,
		&i.LocalAuthenticatedAt,
		&i.RecoveryAuthenticatedAt,
		&i.AuthorityVersion,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now()
WHERE id = $1 AND revoked_at IS NULL AND last_seen_at < now() - interval '5 minutes'
`

// "Last activity" of a session between refreshes (access tokens live 24 h): bumped by the
// periodic session recheck (auth/sessioncheck.go), at most every 5 minutes.
func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
