// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sip.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const finishSipCall = `-- name: FinishSipCall :one
UPDATE sip_calls
SET status = $1, reason = $2, ended_by = $3, ended_at = now(),
    sip_call_id = CASE WHEN $4::text <> '' THEN $4::text ELSE sip_call_id END
WHERE id = $5 AND status IN ('dialing', 'ringing', 'active')
RETURNING id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at
`

type FinishSipCallParams struct {
	Status    string
	Reason    string
	EndedBy   *uuid.UUID
	SipCallID string
	ID        uuid.UUID
}

// ENDED / FAILED once: a call that is already final is left as it is (no row).
func (q *Queries) FinishSipCall(ctx context.Context, arg FinishSipCallParams) (SipCall, error) {
	row := q.db.QueryRow(ctx, finishSipCall,
		arg.Status,
		arg.Reason,
		arg.EndedBy,
		arg.SipCallID,
		arg.ID,
	)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const getLiveSipCallByRoom = `-- name: GetLiveSipCallByRoom :one
SELECT id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at FROM sip_calls WHERE room_id = $1 AND status IN ('dialing', 'ringing', 'active')
`

func (q *Queries) GetLiveSipCallByRoom(ctx context.Context, roomID *uuid.UUID) (SipCall, error) {
	row := q.db.QueryRow(ctx, getLiveSipCallByRoom, roomID)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const getSipAccount = `-- name: GetSipAccount :one
SELECT workspace_id, provider, host, transport, username, auth_username, port, password_enc, caller_id, outbound_prefix, allowed_prefixes, trunk_id, enabled, last_error, updated_at, updated_by FROM sip_accounts WHERE workspace_id = $1
`

func (q *Queries) GetSipAccount(ctx context.Context, workspaceID uuid.UUID) (SipAccount, error) {
	row := q.db.QueryRow(ctx, getSipAccount, workspaceID)
	var i SipAccount
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.Host,
		&i.Transport,
		&i.Username,
		&i.AuthUsername,
		&i.Port,
		&i.PasswordEnc,
		&i.CallerID,
		&i.OutboundPrefix,
		&i.AllowedPrefixes,
		&i.TrunkID,
		&i.Enabled,
		&i.LastError,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getSipCall = `-- name: GetSipCall :one
SELECT id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at FROM sip_calls WHERE id = $1
`

func (q *Queries) GetSipCall(ctx context.Context, id uuid.UUID) (SipCall, error) {
	row := q.db.QueryRow(ctx, getSipCall, id)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const insertSipCall = `-- name: InsertSipCall :one
INSERT INTO sip_calls (id, workspace_id, room_id, number, direction, started_by, participant_identity)
VALUES ($1, $2, $3, $4, 'out', $5, $6)
RETURNING id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at
`

type InsertSipCallParams struct {
	ID                  uuid.UUID
	WorkspaceID         uuid.UUID
	RoomID              *uuid.UUID
	Number              string
	StartedBy           *uuid.UUID
	ParticipantIdentity string
}

func (q *Queries) InsertSipCall(ctx context.Context, arg InsertSipCallParams) (SipCall, error) {
	row := q.db.QueryRow(ctx, insertSipCall,
		arg.ID,
		arg.WorkspaceID,
		arg.RoomID,
		arg.Number,
		arg.StartedBy,
		arg.ParticipantIdentity,
	)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const listLiveSipCalls = `-- name: ListLiveSipCalls :many
SELECT id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at FROM sip_calls
WHERE status IN ('dialing', 'ringing', 'active') AND started_at < $1
ORDER BY started_at
LIMIT 200
`

// The sweeper: live calls placed before the cutoff, oldest first.
func (q *Queries) ListLiveSipCalls(ctx context.Context, startedAt time.Time) ([]SipCall, error) {
	rows, err := q.db.Query(ctx, listLiveSipCalls, startedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SipCall{}
	for rows.Next() {
		var i SipCall
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Number,
			&i.Direction,
			&i.StartedBy,
			&i.ParticipantIdentity,
			&i.SipCallID,
			&i.Status,
			&i.Reason,
			&i.EndedBy,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveSipCallsByWorkspace = `-- name: ListLiveSipCallsByWorkspace :many
SELECT id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at FROM sip_calls
WHERE workspace_id = $1 AND room_id IS NOT NULL AND status IN ('dialing', 'ringing', 'active')
ORDER BY id
`

// WorkspaceSnapshot.sip_calls: the live calls of the workspace's rooms.
func (q *Queries) ListLiveSipCallsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]SipCall, error) {
	rows, err := q.db.Query(ctx, listLiveSipCallsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SipCall{}
	for rows.Next() {
		var i SipCall
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Number,
			&i.Direction,
			&i.StartedBy,
			&i.ParticipantIdentity,
			&i.SipCallID,
			&i.Status,
			&i.Reason,
			&i.EndedBy,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSipCalls = `-- name: ListSipCalls :many
SELECT id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at FROM sip_calls
WHERE workspace_id = $1
  AND ($2::timestamptz IS NULL OR started_at >= $2::timestamptz)
  AND ($3::timestamptz IS NULL OR started_at < $3::timestamptz)
  AND ($4::uuid IS NULL OR id < $4::uuid)
ORDER BY id DESC
LIMIT $5
`

type ListSipCallsParams struct {
	WorkspaceID uuid.UUID
	From        *time.Time
	To          *time.Time
	Cursor      *uuid.UUID
	Lim         int32
}

// The journal, newest first; from / to bound started_at, cursor = the last id of the previous page.
func (q *Queries) ListSipCalls(ctx context.Context, arg ListSipCallsParams) ([]SipCall, error) {
	rows, err := q.db.Query(ctx, listSipCalls,
		arg.WorkspaceID,
		arg.From,
		arg.To,
		arg.Cursor,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SipCall{}
	for rows.Next() {
		var i SipCall
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.RoomID,
			&i.Number,
			&i.Direction,
			&i.StartedBy,
			&i.ParticipantIdentity,
			&i.SipCallID,
			&i.Status,
			&i.Reason,
			&i.EndedBy,
			&i.StartedAt,
			&i.AnsweredAt,
			&i.EndedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSipAccount = `-- name: LockSipAccount :exec

SELECT pg_advisory_xact_lock(hashtext('calaba.sip.' || $1::uuid::text))
`

// ADR-0046: SIP telephony — the provider account and the call journal.
// Serializes saves of one workspace's settings (LiveKit trunk create / replace / delete).
func (q *Queries) LockSipAccount(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockSipAccount, workspaceID)
	return err
}

const markSipCallActive = `-- name: MarkSipCallActive :one
UPDATE sip_calls
SET status = 'active', answered_at = coalesce(answered_at, now()),
    sip_call_id = CASE WHEN $1::text <> '' THEN $1::text ELSE sip_call_id END
WHERE id = $2 AND status IN ('dialing', 'ringing')
RETURNING id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at
`

type MarkSipCallActiveParams struct {
	SipCallID string
	ID        uuid.UUID
}

func (q *Queries) MarkSipCallActive(ctx context.Context, arg MarkSipCallActiveParams) (SipCall, error) {
	row := q.db.QueryRow(ctx, markSipCallActive, arg.SipCallID, arg.ID)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const markSipCallRinging = `-- name: MarkSipCallRinging :one
UPDATE sip_calls SET status = 'ringing'
WHERE id = $1 AND status = 'dialing'
RETURNING id, workspace_id, room_id, number, direction, started_by, participant_identity, sip_call_id, status, reason, ended_by, started_at, answered_at, ended_at
`

func (q *Queries) MarkSipCallRinging(ctx context.Context, id uuid.UUID) (SipCall, error) {
	row := q.db.QueryRow(ctx, markSipCallRinging, id)
	var i SipCall
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.RoomID,
		&i.Number,
		&i.Direction,
		&i.StartedBy,
		&i.ParticipantIdentity,
		&i.SipCallID,
		&i.Status,
		&i.Reason,
		&i.EndedBy,
		&i.StartedAt,
		&i.AnsweredAt,
		&i.EndedAt,
	)
	return i, err
}

const putSipAccount = `-- name: PutSipAccount :one
INSERT INTO sip_accounts (workspace_id, provider, host, transport, username, password_enc, caller_id,
                          outbound_prefix, allowed_prefixes, trunk_id, enabled, last_error, updated_at, updated_by,
                          auth_username, port)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, '', now(), $12, $13, $14)
ON CONFLICT (workspace_id) DO UPDATE
SET provider = excluded.provider, host = excluded.host, transport = excluded.transport,
    username = excluded.username, auth_username = excluded.auth_username, port = excluded.port,
    password_enc = excluded.password_enc, caller_id = excluded.caller_id,
    outbound_prefix = excluded.outbound_prefix, allowed_prefixes = excluded.allowed_prefixes,
    trunk_id = excluded.trunk_id, enabled = excluded.enabled, last_error = '',
    updated_at = now(), updated_by = excluded.updated_by
RETURNING workspace_id, provider, host, transport, username, auth_username, port, password_enc, caller_id, outbound_prefix, allowed_prefixes, trunk_id, enabled, last_error, updated_at, updated_by
`

type PutSipAccountParams struct {
	WorkspaceID     uuid.UUID
	Provider        string
	Host            string
	Transport       string
	Username        string
	PasswordEnc     []byte
	CallerID        string
	OutboundPrefix  string
	AllowedPrefixes []string
	TrunkID         string
	Enabled         bool
	UpdatedBy       *uuid.UUID
	AuthUsername    string
	Port            int32
}

func (q *Queries) PutSipAccount(ctx context.Context, arg PutSipAccountParams) (SipAccount, error) {
	row := q.db.QueryRow(ctx, putSipAccount,
		arg.WorkspaceID,
		arg.Provider,
		arg.Host,
		arg.Transport,
		arg.Username,
		arg.PasswordEnc,
		arg.CallerID,
		arg.OutboundPrefix,
		arg.AllowedPrefixes,
		arg.TrunkID,
		arg.Enabled,
		arg.UpdatedBy,
		arg.AuthUsername,
		arg.Port,
	)
	var i SipAccount
	err := row.Scan(
		&i.WorkspaceID,
		&i.Provider,
		&i.Host,
		&i.Transport,
		&i.Username,
		&i.AuthUsername,
		&i.Port,
		&i.PasswordEnc,
		&i.CallerID,
		&i.OutboundPrefix,
		&i.AllowedPrefixes,
		&i.TrunkID,
		&i.Enabled,
		&i.LastError,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const setSipLastError = `-- name: SetSipLastError :exec
INSERT INTO sip_accounts (workspace_id, last_error) VALUES ($1, $2)
ON CONFLICT (workspace_id) DO UPDATE SET last_error = excluded.last_error
`

type SetSipLastErrorParams struct {
	WorkspaceID uuid.UUID
	LastError   string
}

// A refused save or a failed connection test: only last_error changes (” clears it).
func (q *Queries) SetSipLastError(ctx context.Context, arg SetSipLastErrorParams) error {
	_, err := q.db.Exec(ctx, setSipLastError, arg.WorkspaceID, arg.LastError)
	return err
}

const setWorkspaceSipEnabled = `-- name: SetWorkspaceSipEnabled :one
UPDATE workspaces SET sip_enabled = $2 WHERE id = $1 RETURNING id, slug, name, icon_file_id, visibility, owner_id, created_at, default_audio_bitrate_kbps, default_max_stream_preset, default_max_streams, storage_quota_bytes, storage_used_bytes, allow_self_nickname, default_camera_limit, suspended_at, suspended_reason, suspended_by, time_format, sip_enabled
`

type SetWorkspaceSipEnabledParams struct {
	ID         uuid.UUID
	SipEnabled bool
}

func (q *Queries) SetWorkspaceSipEnabled(ctx context.Context, arg SetWorkspaceSipEnabledParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, setWorkspaceSipEnabled, arg.ID, arg.SipEnabled)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IconFileID,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DefaultAudioBitrateKbps,
		&i.DefaultMaxStreamPreset,
		&i.DefaultMaxStreams,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.AllowSelfNickname,
		&i.DefaultCameraLimit,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.SuspendedBy,
		&i.TimeFormat,
		&i.SipEnabled,
	)
	return i, err
}
