// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const addMember = `-- name: AddMember :one
INSERT INTO workspace_members (workspace_id, user_id, role)
VALUES ($1, $2, $3)
ON CONFLICT (workspace_id, user_id) DO NOTHING
RETURNING workspace_id, user_id, role, nickname, joined_at
`

type AddMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
	Role        string
}

func (q *Queries) AddMember(ctx context.Context, arg AddMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const countOwnedWorkspaces = `-- name: CountOwnedWorkspaces :one
SELECT count(*)::integer FROM workspaces WHERE owner_id = $1
`

func (q *Queries) CountOwnedWorkspaces(ctx context.Context, ownerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countOwnedWorkspaces, ownerID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (slug, name, visibility, owner_id, storage_quota_bytes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, slug, name, icon_file_id, visibility, owner_id, created_at, default_audio_bitrate_kbps, default_max_stream_preset, default_max_streams, storage_quota_bytes, storage_used_bytes, allow_self_nickname, default_camera_limit, suspended_at, suspended_reason, suspended_by, time_format
`

type CreateWorkspaceParams struct {
	Slug              string
	Name              string
	Visibility        string
	OwnerID           uuid.UUID
	StorageQuotaBytes int64
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.Slug,
		arg.Name,
		arg.Visibility,
		arg.OwnerID,
		arg.StorageQuotaBytes,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IconFileID,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DefaultAudioBitrateKbps,
		&i.DefaultMaxStreamPreset,
		&i.DefaultMaxStreams,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.AllowSelfNickname,
		&i.DefaultCameraLimit,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.SuspendedBy,
		&i.TimeFormat,
	)
	return i, err
}

const deleteUserOverridesInWorkspace = `-- name: DeleteUserOverridesInWorkspace :exec
DELETE FROM room_permissions rp
USING rooms r
WHERE rp.room_id = r.id AND r.workspace_id = $1::uuid
  AND rp.target_type = 'user' AND rp.target_id = $2::text
`

type DeleteUserOverridesInWorkspaceParams struct {
	WorkspaceID uuid.UUID
	UserID      string
}

func (q *Queries) DeleteUserOverridesInWorkspace(ctx context.Context, arg DeleteUserOverridesInWorkspaceParams) error {
	_, err := q.db.Exec(ctx, deleteUserOverridesInWorkspace, arg.WorkspaceID, arg.UserID)
	return err
}

const deleteWorkspace = `-- name: DeleteWorkspace :execrows
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspace, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMember = `-- name: GetMember :one
SELECT workspace_id, user_id, role, nickname, joined_at FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type GetMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) GetMember(ctx context.Context, arg GetMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, getMember, arg.WorkspaceID, arg.UserID)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const getMemberWithUser = `-- name: GetMemberWithUser :one
SELECT m.workspace_id, m.user_id, m.role, m.nickname, m.joined_at, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot,
       coalesce((SELECT array_agg(mr.role_id ORDER BY wr.position DESC)
                 FROM member_roles mr JOIN workspace_roles wr ON wr.id = mr.role_id
                 WHERE mr.workspace_id = m.workspace_id AND mr.user_id = m.user_id), '{}')::uuid[] AS role_ids
FROM workspace_members m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.user_id = $2
`

type GetMemberWithUserParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

type GetMemberWithUserRow struct {
	WorkspaceMember WorkspaceMember
	User            User
	RoleIds         []uuid.UUID
}

func (q *Queries) GetMemberWithUser(ctx context.Context, arg GetMemberWithUserParams) (GetMemberWithUserRow, error) {
	row := q.db.QueryRow(ctx, getMemberWithUser, arg.WorkspaceID, arg.UserID)
	var i GetMemberWithUserRow
	err := row.Scan(
		&i.WorkspaceMember.WorkspaceID,
		&i.WorkspaceMember.UserID,
		&i.WorkspaceMember.Role,
		&i.WorkspaceMember.Nickname,
		&i.WorkspaceMember.JoinedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.DisplayName,
		&i.User.AvatarFileID,
		&i.User.StatusText,
		&i.User.Settings,
		&i.User.CreatedAt,
		&i.User.DisabledAt,
		&i.User.StatusEmoji,
		&i.User.StatusExpiresAt,
		&i.User.IsGuest,
		&i.User.GuestExpiresAt,
		&i.User.Timezone,
		&i.User.EmailVerifiedAt,
		&i.User.PendingEmail,
		&i.User.Locale,
		&i.User.PresenceStatus,
		&i.User.PresenceUntil,
		&i.User.IsBot,
		&i.RoleIds,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, slug, name, icon_file_id, visibility, owner_id, created_at, default_audio_bitrate_kbps, default_max_stream_preset, default_max_streams, storage_quota_bytes, storage_used_bytes, allow_self_nickname, default_camera_limit, suspended_at, suspended_reason, suspended_by, time_format FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IconFileID,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DefaultAudioBitrateKbps,
		&i.DefaultMaxStreamPreset,
		&i.DefaultMaxStreams,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.AllowSelfNickname,
		&i.DefaultCameraLimit,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.SuspendedBy,
		&i.TimeFormat,
	)
	return i, err
}

const listMemberNames = `-- name: ListMemberNames :many
SELECT m.user_id, CASE WHEN m.nickname <> '' THEN m.nickname ELSE u.display_name END AS name
FROM workspace_members m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1 AND m.user_id = ANY($2::uuid[])
`

type ListMemberNamesParams struct {
	WorkspaceID uuid.UUID
	UserIds     []uuid.UUID
}

type ListMemberNamesRow struct {
	UserID uuid.UUID
	Name   interface{}
}

// Voice display names: nickname if set, else the user's display name.
func (q *Queries) ListMemberNames(ctx context.Context, arg ListMemberNamesParams) ([]ListMemberNamesRow, error) {
	rows, err := q.db.Query(ctx, listMemberNames, arg.WorkspaceID, arg.UserIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMemberNamesRow{}
	for rows.Next() {
		var i ListMemberNamesRow
		if err := rows.Scan(&i.UserID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT m.workspace_id, m.user_id, m.role, m.nickname, m.joined_at, u.id, u.email, u.password_hash, u.display_name, u.avatar_file_id, u.status_text, u.settings, u.created_at, u.disabled_at, u.status_emoji, u.status_expires_at, u.is_guest, u.guest_expires_at, u.timezone, u.email_verified_at, u.pending_email, u.locale, u.presence_status, u.presence_until, u.is_bot,
       coalesce((SELECT array_agg(mr.role_id ORDER BY wr.position DESC)
                 FROM member_roles mr JOIN workspace_roles wr ON wr.id = mr.role_id
                 WHERE mr.workspace_id = m.workspace_id AND mr.user_id = m.user_id), '{}')::uuid[] AS role_ids
FROM workspace_members m JOIN users u ON u.id = m.user_id
WHERE m.workspace_id = $1
ORDER BY m.joined_at
`

type ListMembersRow struct {
	WorkspaceMember WorkspaceMember
	User            User
	RoleIds         []uuid.UUID
}

func (q *Queries) ListMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMembersRow{}
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.WorkspaceMember.WorkspaceID,
			&i.WorkspaceMember.UserID,
			&i.WorkspaceMember.Role,
			&i.WorkspaceMember.Nickname,
			&i.WorkspaceMember.JoinedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.DisplayName,
			&i.User.AvatarFileID,
			&i.User.StatusText,
			&i.User.Settings,
			&i.User.CreatedAt,
			&i.User.DisabledAt,
			&i.User.StatusEmoji,
			&i.User.StatusExpiresAt,
			&i.User.IsGuest,
			&i.User.GuestExpiresAt,
			&i.User.Timezone,
			&i.User.EmailVerifiedAt,
			&i.User.PendingEmail,
			&i.User.Locale,
			&i.User.PresenceStatus,
			&i.User.PresenceUntil,
			&i.User.IsBot,
			&i.RoleIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenWorkspacesForUser = `-- name: ListOpenWorkspacesForUser :many
SELECT w.id, w.slug, w.name, w.icon_file_id, w.visibility, w.owner_id, w.created_at, w.default_audio_bitrate_kbps, w.default_max_stream_preset, w.default_max_streams, w.storage_quota_bytes, w.storage_used_bytes, w.allow_self_nickname, w.default_camera_limit, w.suspended_at, w.suspended_reason, w.suspended_by, w.time_format FROM workspaces w
WHERE w.visibility = 'open'
  AND NOT EXISTS (SELECT 1 FROM workspace_members m WHERE m.workspace_id = w.id AND m.user_id = $1)
ORDER BY w.name
LIMIT 200
`

func (q *Queries) ListOpenWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listOpenWorkspacesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IconFileID,
			&i.Visibility,
			&i.OwnerID,
			&i.CreatedAt,
			&i.DefaultAudioBitrateKbps,
			&i.DefaultMaxStreamPreset,
			&i.DefaultMaxStreams,
			&i.StorageQuotaBytes,
			&i.StorageUsedBytes,
			&i.AllowSelfNickname,
			&i.DefaultCameraLimit,
			&i.SuspendedAt,
			&i.SuspendedReason,
			&i.SuspendedBy,
			&i.TimeFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkspaceIDs = `-- name: ListUserWorkspaceIDs :many
SELECT workspace_id FROM workspace_members WHERE user_id = $1
`

func (q *Queries) ListUserWorkspaceIDs(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaceIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var workspace_id uuid.UUID
		if err := rows.Scan(&workspace_id); err != nil {
			return nil, err
		}
		items = append(items, workspace_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.id, w.slug, w.name, w.icon_file_id, w.visibility, w.owner_id, w.created_at, w.default_audio_bitrate_kbps, w.default_max_stream_preset, w.default_max_streams, w.storage_quota_bytes, w.storage_used_bytes, w.allow_self_nickname, w.default_camera_limit, w.suspended_at, w.suspended_reason, w.suspended_by, w.time_format FROM workspaces w
JOIN workspace_members m ON m.workspace_id = w.id
WHERE m.user_id = $1
ORDER BY m.joined_at
`

func (q *Queries) ListUserWorkspaces(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaces, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Workspace{}
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IconFileID,
			&i.Visibility,
			&i.OwnerID,
			&i.CreatedAt,
			&i.DefaultAudioBitrateKbps,
			&i.DefaultMaxStreamPreset,
			&i.DefaultMaxStreams,
			&i.StorageQuotaBytes,
			&i.StorageUsedBytes,
			&i.AllowSelfNickname,
			&i.DefaultCameraLimit,
			&i.SuspendedAt,
			&i.SuspendedReason,
			&i.SuspendedBy,
			&i.TimeFormat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUserWorkspaces = `-- name: LockUserWorkspaces :exec
SELECT pg_advisory_xact_lock(hashtext('calaba.ws.create:' || $1::text))
`

// Serializes workspace creation per user (limit check + insert).
func (q *Queries) LockUserWorkspaces(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, lockUserWorkspaces, userID)
	return err
}

const removeMember = `-- name: RemoveMember :execrows
DELETE FROM workspace_members WHERE workspace_id = $1 AND user_id = $2
`

type RemoveMemberParams struct {
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) RemoveMember(ctx context.Context, arg RemoveMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeMember, arg.WorkspaceID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMember = `-- name: UpdateMember :one
UPDATE workspace_members SET
    role     = coalesce($1, role),
    nickname = coalesce($2, nickname)
WHERE workspace_id = $3 AND user_id = $4
RETURNING workspace_id, user_id, role, nickname, joined_at
`

type UpdateMemberParams struct {
	Role        *string
	Nickname    *string
	WorkspaceID uuid.UUID
	UserID      uuid.UUID
}

func (q *Queries) UpdateMember(ctx context.Context, arg UpdateMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, updateMember,
		arg.Role,
		arg.Nickname,
		arg.WorkspaceID,
		arg.UserID,
	)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.Nickname,
		&i.JoinedAt,
	)
	return i, err
}

const updateWorkspace = `-- name: UpdateWorkspace :one
UPDATE workspaces SET
    slug                       = coalesce($1, slug),
    name                       = coalesce($2, name),
    visibility                 = coalesce($3, visibility),
    icon_file_id               = CASE WHEN $4::boolean THEN $5::uuid ELSE icon_file_id END,
    default_audio_bitrate_kbps = coalesce($6, default_audio_bitrate_kbps),
    default_max_stream_preset  = coalesce($7, default_max_stream_preset),
    default_max_streams        = coalesce($8, default_max_streams),
    default_camera_limit       = coalesce($9, default_camera_limit),
    allow_self_nickname        = coalesce($10, allow_self_nickname),
    time_format                = coalesce($11, time_format)
WHERE id = $12
RETURNING id, slug, name, icon_file_id, visibility, owner_id, created_at, default_audio_bitrate_kbps, default_max_stream_preset, default_max_streams, storage_quota_bytes, storage_used_bytes, allow_self_nickname, default_camera_limit, suspended_at, suspended_reason, suspended_by, time_format
`

type UpdateWorkspaceParams struct {
	Slug                    *string
	Name                    *string
	Visibility              *string
	SetIcon                 bool
	IconFileID              *uuid.UUID
	DefaultAudioBitrateKbps *int32
	DefaultMaxStreamPreset  *string
	DefaultMaxStreams       *int32
	DefaultCameraLimit      *int32
	AllowSelfNickname       *bool
	TimeFormat              *string
	ID                      uuid.UUID
}

func (q *Queries) UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, updateWorkspace,
		arg.Slug,
		arg.Name,
		arg.Visibility,
		arg.SetIcon,
		arg.IconFileID,
		arg.DefaultAudioBitrateKbps,
		arg.DefaultMaxStreamPreset,
		arg.DefaultMaxStreams,
		arg.DefaultCameraLimit,
		arg.AllowSelfNickname,
		arg.TimeFormat,
		arg.ID,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.IconFileID,
		&i.Visibility,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DefaultAudioBitrateKbps,
		&i.DefaultMaxStreamPreset,
		&i.DefaultMaxStreams,
		&i.StorageQuotaBytes,
		&i.StorageUsedBytes,
		&i.AllowSelfNickname,
		&i.DefaultCameraLimit,
		&i.SuspendedAt,
		&i.SuspendedReason,
		&i.SuspendedBy,
		&i.TimeFormat,
	)
	return i, err
}
